### ISSUE TITLE
Using external JS lib

### ISSUE THREAD

**Issue by sloba-byte** [a-h/templ#106]
Hi,

I think this has potential, however I failed to find a way to use some external JS library?

For example, lets say => https://github.com/tradingview/lightweight-charts would there be a way to somehow use this with templ? Goal would be to still not write JS, or maybe do it minimally (write JS wrappers which are called from go?)

**Comment by a-h** [comment]
Thanks for trying templ!

The docs were only hinting at what's possible, so I've made it more explicit, and also included an example in the repo in the following commit: https://github.com/a-h/templ/commit/6d8379950cb21f9c48cec753afebe0cbeac7ee32

See here for an example: https://github.com/a-h/templ/tree/main/examples/external-libraries

I've also updated the docs here: https://templ.guide/syntax-and-usage/script-templates

Does that give you what you were looking for?

**Comment by joerdav** [comment]
On the goal of not writing JS, someone is always going to have to write _some_ JS. Using what @a-h has documented someone could package and export lightweight-charts as a sort of "templ component library", which prevents others from having to write the JS.

**Comment by sloba-byte** [comment]
Thanks for the answer! I will try it out tomorrow no time today. 

I look always to write bare minimum or no JS, as I don't like it:
1) Dynamically typed - usually slow to iterate and find bugs.
2) If you want types you need to add so much complexity and external tooling - again it's very poor experience

Usually, I am crafting rather simple UIs, reports etc read only. I prefer to do all the work in go.

I would love to get somehow type safety in "templ body() {
    <script> ... </script>" part... Even some half measure would be rather useful. 
   What are you thoughts @a-h @joerdav

**Comment by joerdav** [comment]
@sloba-byte did you take a look at the documentation @a-h added here: https://templ.guide/syntax-and-usage/script-templates/

**Comment by sloba-byte** [comment]
I tried it out and it works great!

My point is: 
```golang
script graph(data []TimeValue) {
	const chart = LightweightCharts.createChart(document.body, { width: 400, height: 300 });
	const lineSeries = chart.addLineSeries();
	lineSeries.setData(data);
}
```
This is just a string, you can write what ever you want:

1. It has not context about parameter passed (you can write lineSeries.setData(someParamName) and it will compile and execute)
2. It has no context of JS

1) Should be easy to have at last ; 2) Is what I am looking for and that sounds like a hard thing.

**Comment by a-h** [comment]
In some work I've been doing, I've been using TypeScriptify to create TypeScript interfaces from Go structs. That then allows compile-time checks in TypeScript against the Go code definitions: https://github.com/tkrajina/typescriptify-golang-structs

**Comment by sloba-byte** [comment]
Thanks for the help and all the info. Good luck with the tool.

**Comment by pezdel** [comment]
Hi, so I'm very new to this library and was playing around with the lightweight chart example but wanted to have a hx-get -> update the chart data.  I got the below example to work but not sure if there is a better way to get it to work with tools from the library. 

Thanks

Not a lot of changes from the original.
```
script onLoad(data []TimeValue) {
    //changed to lets
    chart = LightweightCharts.createChart(document.body, { width: 300, height: 400 });
    lineSeries = chart.addLineSeries();
    lineSeries.setData(data)
}
```
```
templ page(data []TimeValue) {
	<script>
              let lineSeries = {} //NEW
         </script>
	<html>
		<head>
			<meta charset="UTF-8"/>
			<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
			<title>Graphs</title>
			<script src="https://unpkg.com/htmx.org@1.9.6"></script>
			<script src="https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js"></script>
		</head>
		<body id="body" onload={ onLoad(data) }>
			<button hx-get="/data">Click me</button> //NEW
		</body>
	</html>
}
```
New Route
```
mux.HandleFunc("/data", func(w http.ResponseWriter, r *http.Request) {
      data := []TimeValue{}   //just empted it out since its just a example
      jsonData, _ := json.Marshal(data)
      jsCode := fmt.Sprintf("<script>lineSeries.setData(%s)</script>", jsonData)
      w.Write([]byte(jsCode))
}
```

**Comment by a-h** [comment]
In this case, I don't think it makes sense to use HTMX to do the work.

With HTMX you'd be rendering a HTML script tag containing JSON just so that you can pass some JSON to client-side JavaScript, so I think it makes sense to use the browser's fetch API to get the JSON directly - https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API and update the variable.

i.e. something like this. (I haven't tested it all, don't expect it to work, it's just an example).

```html
templ page(data []TimeValue) {
	<script>
              let lineSeries = {} //NEW
         </script>
	<html>
		<head>
			<meta charset="UTF-8"/>
			<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
			<title>Graphs</title>
			<script src="https://unpkg.com/htmx.org@1.9.6"></script>
			<script src="https://unpkg.com/lightweight-charts/dist/lightweight-charts.standalone.production.js"></script>
		</head>
		<body id="body" onload={ onLoad(data) }>
			<button onclick="() => fetch("/data").then((result) => lineSeries = result)">Click me</button> //NEW
		</body>
	</html>
}
```

**Comment by a-h** [comment]
By the way, there's a Slack channel in the Go #gophers Slack called templ for general discussions.

**Comment by eussam** [comment]
> By the way, there's a Slack channel in the Go #gophers Slack called templ for general discussions.

Hi @a-h , any reason why this info is not part of the https://templ.guide/media/ section of the doc ?

**Comment by a-h** [comment]
No reason, just hasn't been done.

Probably needs a new page in the docs, something like "Getting help" which links to the Slack channel, Github discussions, and details how to raise a good issue.

**Comment by a-h** [comment]
I've updated the docs to add a new page in https://github.com/a-h/templ/commit/bedd9c4e374975fa626e42cc5d7fe26997077837
