### ISSUE TITLE
Publish plugin on Open VSX Registry for VSCodium

### ISSUE THREAD

**Issue by ElnuDev** [a-h/templ#111]
Currently, [templ-vscode](/a-h/templ-vscode) is only available on Microsoft's official plugin marketplace. Unfortunately, Microsoft blocks other VSCode-compatible editors (i.e. [VSCodium](https://vscodium.com/), a libre build of VSCode) from using their marketplace, so VSCodium uses the [Open VSX Registry](https://open-vsx.org/) instead. templ-vscode doesn't appear to be currently published there. Would it be possible to publish it onto Open VSX? It'd make getting up and running with templ much faster for people using VSCodium.

Currently, the plugin has to be installed manually. For anybody using VSCodium and seeing this issue, [here is the direct download link for templ-vscode 0.0.6](https://a-h.gallery.vsassets.io/_apis/public/gallery/publisher/a-h/extension/templ/0.0.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage). After downloading, change the file extension to .vsix and run the "Install from VSIX" command.

Thank you!

**Comment by a-h** [comment]
This is a bit of a mess about. Had to setup an Eclipse account, claim a namespace by creating https://github.com/EclipseFdn/open-vsx.org/issues/2092

**Comment by a-h** [comment]
Hi @ElnuDev - got my namespace claimed, and setup automated deployment.

templ-vscode is on the registry at https://open-vsx.org/extension/a-h/templ and will be kept up-to-date by the Github workflow.

If you could give it a try out, and close this issue if you're able to use it, that would be great.

Thanks!

**Comment by a-h** [comment]
Closing this as done.

**Comment by nkev** [comment]
Unfortunately, manually installing any version (I just tried 0.0.35) of the VSIX at https://open-vsx.org/extension/a-h/templ  displays the error "not compatible with VSCodium". I have the latest version of VSCodium installed.

Anyone have it working in VSCodium?

**Comment by a-h** [comment]
VSCodium 1.88 looks to be a year old. Are you sure you've got the latest version installed?
