### ISSUE TITLE
bugs: Incorrect coloring in templ plugin with elements behind bracket being the issue

### ISSUE THREAD

**Issue by benjiro29** [a-h/templ#121]
Issue1: 

```
package Template

templ title(typeID int){
	if typeID == 1 {
                // whatever
	} else if typeID == 2 {
                // whatever
	}
}
```

The following code result in all the coloring going wrong right after the ==1 { bracket. Contaminating the whole file. Isolating this code to the above, shows where it goes wrong. Tested on the last 0.0.7 VSC plugin with 0.2.304.

The issue is that "} else" is not recognized and the space right behind "}" messes up the coloring.

```
package Template

templ title(typeID int){
	if typeID == 1 {
                // whatever
	}

	if typeID == 2 {
                // whatever
	}
}
```

This works perfectly fine without color issues. The else and especially the SPACE right behind the close bracket breaks the coloring.

Issue2:

Any open bracket like { creates issues with code coloring IF there are hidden elements behind it. For instance, a tab or a space. These seem to be not stripped correctly and messes up the VSC plugin its coloring.

Same as issue 1 but it also influences open brackets. But it gets isolated to the code block itself and not the entire file.

**Comment by a-h** [comment]
Thanks for the report. Taking a look, I can see that I added `else if` support in https://github.com/a-h/templ/commit/67b2d8789d7fdbb6455b113d430455aacaa00cb1 but it looks like the highlighting support `else if` is some sort of overlap of the existing `else` and `if` highlighting - https://github.com/a-h/templ-vscode/blob/baaab627ad32fff89490f2d4569e6ca841b57f19/syntaxes/templ.tmLanguage.json#L236-L275

Probably just needs a new regular expression to explicitly handle the `else if` case.

<img width="560" alt="Screenshot 2023-08-06 at 21 34 33" src="https://github.com/a-h/templ/assets/1029947/61d63028-f175-49ad-8ce0-ec31d3522048">

```
templ CheckIfElse(a, b bool) {
	if a {
		<div>A</div>
	} else if b {
		<div>B</div>
	} else {
		<div>C</div>
	}
}
```

Same deal for the open brace:

<img width="424" alt="Screenshot 2023-08-06 at 21 36 00" src="https://github.com/a-h/templ/assets/1029947/8d41afda-5f2a-4226-bbba-99228f5fb646">

```
templ CheckBrace(a bool) {
	if a { 
		<div>A</div>
	}
}
```
