### ISSUE TITLE
Ability to call script templates outside of on* event attributes

### ISSUE THREAD

**Issue by mgkpete** [a-h/templ#126]
Is it possible to call script templates outside of on* event attributes? For example, within htmx events (https://htmx.org/attributes/hx-on/):

```
script beforeRequest(msg string) {
    alert(msg)
}

templ button(msg string) {
    <button hx-get="/info" hx-on::before-request={ beforeRequest(msg) }></button>
}
```
 or directly from a  script tag to have the script execute on render? a contrived example:

```
script runOnRender(id string) {
    document.getElementById(id).innerHTML = "Hello World!";
}

templ example(id string) {
    <div id={id} ></div>
    <script>{runOnRender(id)}</script>
}
```
Thanks

**Comment by mgkpete** [comment]
Another option would be to allow variables within script tags but to enforce JSON encoding them (that same way as standard html/template package does, see https://pkg.go.dev/html/template#hdr-Contexts). The syntax might have to be modified slightly from ```{ varname }``` to something like ```{> varname }``` so not to clash with javascript syntax. Doing so would be useful for sharing data structures with client side scripts.  A simple example:

```

type SumParts struct {X,Y int}

templ Example(id string, sum SumParts) {
    <div id={id} ></div>
    <script>
        const sum = {> sum };
        const answer = sum.X + sum.Y
        document.getElementById({> id }).innerHTML = `The sum of ${sum.X} + ${sum.Y} is ${answer}`;
    </script>
}
```

calling  ```Example("exampleID", SumParts{X: 2, Y:3})``` would render to

```
    <div id="exampleID" ></div>
    <script>
        const sum = {"X": 2, "Y": 3};
        const answer = sum.X + sum.Y;
        document.getElementById("exampleID").innerHTML = `The sum of ${sum.X} + ${sum.Y} is ${answer}`;
    </script>
```

Thanks

**Comment by a-h** [comment]
Good points here. Thanks for your thinking on this.

# `hx-on`

I think it would be reasonable to enable support for this within the code itself. The generator is where the special handling for the `on*` attributes happens:

https://github.com/a-h/templ/blob/5d4f3651915caf1721682b3f51578744f6552276/generator/generator.go#L910 
https://github.com/a-h/templ/blob/5d4f3651915caf1721682b3f51578744f6552276/generator/generator.go#L1010

In this case, the generator could, instead, have a set of well-known attribute handlers. As it stands, at code generation time, in addition to checking whether the attribute prefix is `on` (current behaviour), it would also check for `hx-on:` (new behaviour) before rendering out a call to a script template.

Pretty straightforward change to implement. I'm working on hot reload at the moment, then I need to re-loop back around to take care of some requests for changes to the `templ fmt` operation.

It's a hack, but it's possible to use `on*` events on empty images. 😂 

```
<img src onerror='alert()'>
```

**Comment by a-h** [comment]
Thinking more about running the script template on load events - it's possible to define a `templ.Component` as code, and use it, as per https://templ.guide/core-concepts/components

So, in your Go code, you can have this:

```go
func onLoad(script templ.ComponentScript) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		if _, err = io.WriteString(w, `<script type="text/javascript">`+"\r\n"+script.Call+"\r\n</script>"); err != nil {
			return err
		}
		return nil
	})
}
```

And in your templ code:

```html
script withoutParameters() {
	alert("hello");
}

templ ThreeButtons() {
	<button onMouseover="console.log(&#39;mouseover&#39;)" type="button">Button C</button>
	@onLoad(withoutParameters())
}
```

And after the button, you'll get:

```
                 Button C
                </button>
        +       <script type="text/javascript">
        +        __templ_withoutParameters_6bbf()
        +       </script>
```

**Comment by a-h** [comment]
Would shipping that little `onLoad` function as part of the templ runtime solve the issue?

I called it `onLoad` above, but it could be accessed via `templ.RunScript(scripts templ.ComponentScript...)` (not sure of the name, suggestions welcome), and explain it in the docs.

I think that keeps the script templates as pure functions that can't accidentally take in state from elsewhere.

**Comment by mgkpete** [comment]
Thanks for the response. That ```onLoad``` function solves the issue of running a script on render perfectly for me and I agree it keeps things aligned to the original intent of the script templates. 

As for the ```hx-on``` and other script attributes, I think it'd be good to allow the whitelist to be configurable, possibly via a flag, rather than hardcoded - or alternatively to remove the requirement to specify which attributes are allowed? As a work around I should be able to use a similar approach to the ```onload``` function above.

**Comment by a-h** [comment]
I've linked a PR that I think solves the first part of the issue. I'm quite happy for the attributes to be non-configurable for now. If it keeps happening, I can make a CLI flag for the generator to allow people to work around it, or remove the requirement to specify the attributes that are allowed to have scripts attached to them like you suggested.

Can you check the PR over and make sure it's doing what you need?

Any comment on the inclusion of an `onLoad` function, and, what the name should be?

**Comment by mgkpete** [comment]
Thanks for your work on this, I've checked the PR and all look good.

As for the name of the ```onLoad``` function, it's a tricky one, as the code would actually be executed when the browser parses the tag rather than when the body onload event would be triggered, so ```onLoad``` could be confusing but I'm struggling for a better alternative, maybe something along the lines of ```onParse``` or ```callScript```/```invokeScript```?

**Comment by g5becks** [comment]
> I've linked a PR that I think solves the first part of the issue. I'm quite happy for the attributes to be non-configurable for now. If it keeps happening, I can make a CLI flag for the generator to allow people to work around it, or remove the requirement to specify the attributes that are allowed to have scripts attached to them like you suggested.

Making it  configurable would really be great. I would like to be able to use the script templates to pass data to AlpineJs, as opposed to having it in strings inside the template.

**Comment by joerdav** [comment]
This does raise a question of project config. It could easily be a cli flag to expand the whitelist, but would we want it to be needed for every excecution of `templ generate`? Or is this something that might want to be bundled in a templ.(toml|yaml) at the root of a project?

**Comment by a-h** [comment]
Still thinking about the extensibility and `<script>` tag stuff, but thought I'd drop this PR in the meantime.

**Comment by gamebox** [comment]
As someone who is evaluating Templ as an option to move away from go templates, I'd like to register that I have a use case where my script template needs to be rendered as `type="module"` to function correctly.  Also, sometimes scripts may want to purposely be rendered more than once, i.e., loading a web component (or other small client-side component) in a parameterized way.

I think that supporting just inlining the script contents directly into the script tag if the injection site is there makes a lot of sense, without trying to do any sort of guessing about the intentions of the author about the need for idempotence.

In my local, I've done some manual editing to test out the idea.  What I've come up with is two changes:

First is what I'm calling the `ScriptCall` function which would be used to create the `Call` field of the `ComponentScript` struct:

```go
func ScriptCall(functionName string, params ...interface{}) string {
	encodedParams := make([]string, len(params))
	for i := 0; i < len(encodedParams); i++ {
		enc, _ := json.Marshal(params[i])
		encodedParams[i] = string(enc)
	}
	sb := new(strings.Builder)
	sb.WriteString(functionName)
	sb.WriteRune('(')
	sb.WriteString(strings.Join(encodedParams, ","))
	sb.WriteRune(')')
	return sb.String()
}
```

And then I just do this when I encounter the template call:

```go
	var var_2 templ.ComponentScript = loadComponent(id, props)
	_, err = templBuffer.WriteString(var_2.Function)
	if err != nil {
		return err
	}
        _, err = templBuffer.WriteString(var_2.Call)
        if err != nil {
            return err
        }
```

I.e., just call it right after it is defined.  I also remove the call to `RenderScriptItems` at the top of the component render function.  I could probably put together a PR to implement this sort of change if you are interested (haven't hacked it myself yet).

Thanks for taking the feedback!

**Comment by a-h** [comment]
It's now possible to use script templates as templ components, outside of attributes: https://github.com/a-h/templ/pull/285

There's an update to the docs here: https://templ.guide/syntax-and-usage/script-templates#script-templates
