### ISSUE TITLE
LSP auto-import mangles templ files

### ISSUE THREAD

**Issue by jwhitaker-swiftnav** [a-h/templ#135]
Heya, thanks heaps for building this, it is I think the best high-level design for how templating should work I've ever seen.

I'm just seen some funniness in the VSCode extension (have been for ages, it's not introduced recently) - accepting the suggestion for an auto-import seems to mangle things up.

Video (two examples, one at start one at end):

https://github.com/a-h/templ/assets/113399675/badc7bb8-018d-4b2e-9fc7-4007fec37a49

Exact behaviour seems to be affected by whether the generated code is up to date, but there is some level of mangling in either case.

**Comment by agalbenus** [comment]
I was looking to open a ticket for the same issue. Other than this, everything is awesome. 
Thank you for such a great work!

**Comment by a-h** [comment]
Thanks for the nice feedback, and great bug report @jwhitaker-swiftnav, and thanks for looking into the issue @agalbenus 

Looking at the LSP logs when it happened didn't tell me much, but I added some extra logging to print out the full object model of the autocompletion options.

The completion items include "additionalTextEdits" - i.e. they change text that isn't just the bit you're autocompleting - selecting the item also changes the import list.

templ isn't currently rewriting those additional text edits at all, but even if it was, as @agalbenus points out, the imports don't exist in the source file, so there's no proper mapping.

```go
	p.Log.Info("completion: received items", zap.Int("count", len(result.Items)), zap.Any("items", result.Items))
	for i := 0; i < len(result.Items); i++ {
		item := result.Items[i]
		if item.TextEdit != nil {
			item.TextEdit.Range = p.convertGoRangeToTemplRange(templURI, item.TextEdit.Range)
		}
		result.Items[i] = item
	}
```

Here's the completion list.

```json
{
  "level": "info",
  "ts": "2023-09-03T18:34:45+01:00",
  "caller": "proxy/server.go:335",
  "msg": "completion: received items",
  "count": 7,
  "items": [
    {
      "additionalTextEdits": [
        {
          "range": {
            "start": {
              "line": 6,
              "character": 7
            },
            "end": {
              "line": 6,
              "character": 7
            }
          },
          "newText": "(\n\t"
        },
        {
          "range": {
            "start": {
              "line": 6,
              "character": 8
            },
            "end": {
              "line": 6,
              "character": 10
            }
          },
          "newText": "by"
        },
        {
          "range": {
            "start": {
              "line": 6,
              "character": 11
            },
            "end": {
              "line": 9,
              "character": 1
            }
          },
          "newText": "es\"\n\t\"context\"\n\t\"io\"\n\t\"strconv\"\n\n\t\"github.com/a-h/te"
        },
        {
          "range": {
            "start": {
              "line": 9,
              "character": 3
            },
            "end": {
              "line": 9,
              "character": 13
            }
          },
          "newText": "l"
        },
        {
          "range": {
            "start": {
              "line": 9,
              "character": 14
            },
            "end": {
              "line": 9,
              "character": 14
            }
          },
          "newText": "\n)"
        }
      ],
      "detail": "\"strconv\"",
      "documentation": {
        "kind": "markdown",
        "value": ""
      },
      "filterText": "strconv",
      "insertTextFormat": 2,
      "kind": 9,
      "label": "strconv",
      "preselect": true,
      "sortText": "00000",
      "textEdit": {
        "range": {
          "start": {
            "line": 24,
            "character": 21
          },
          "end": {
            "line": 24,
            "character": 25
          }
        },
        "newText": "strconv"
      }
    },
...
}
```

I think the way to solve this might be to get templ to do its own addition of import statements. The LSP returns an enum called https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItemKind and `export const Module = 9;`.

```json
      "filterText": "strconv",
      "insertTextFormat": 2,
      "kind": 9,
```

So it might be a case of if `kind == 9` in the message received from gopls, and additionalTextEdits are present, remove them and replace them with a plain Go import statement in the templ file.

**Comment by a-h** [comment]
Modifying `server.go` in the LSP section shows good promise.

```go
        // Rewrite the result positions.
-       p.Log.Info("completion: received items", zap.Int("count", len(result.Items)))
+       p.Log.Info("completion: received items", zap.Int("count", len(result.Items)), zap.Any("items", result.Items))
        for i := 0; i < len(result.Items); i++ {
                item := result.Items[i]
                if item.TextEdit != nil {
                        item.TextEdit.Range = p.convertGoRangeToTemplRange(templURI, item.TextEdit.Range)
                }
+               if item.Kind == lsp.CompletionItemKindModule && len(item.AdditionalTextEdits) > 0 {
+                       item.AdditionalTextEdits = []lsp.TextEdit{
+                               {
+                                       Range: lsp.Range{
+                                               Start: lsp.Position{Line: 1, Character: 0},
+                                               End:   lsp.Position{Line: 1, Character: 0},
+                                       },
+                                       NewText: fmt.Sprintf(`import "%s"`, item.Label),
+                               },
+                       }
+               }
                result.Items[i] = item
        }
```

This change is really basic - it just puts an import statement in as the first line in the file - it doesn't format the code in that section, e.g. insert appropriate newlines, which I'd really want it to do.

![import](https://github.com/a-h/templ/assets/1029947/235a006f-3caa-40fc-893e-f6ea1fee9684)

**Comment by a-h** [comment]
This is more like it...

![import](https://github.com/a-h/templ/assets/1029947/c3a71424-dd14-41e3-9716-e5b52f3187d8)
![import2](https://github.com/a-h/templ/assets/1029947/1137c95c-54c3-42a3-9722-c6d873affbe1)

**Comment by a-h** [comment]
OK, @jwhitaker-swiftnav, @agalbenus - if you have a chance to check over the changes in that PR, I'd appreciate it!

**Comment by a-h** [comment]
The PR is https://github.com/a-h/templ/pull/136

I've just realised that it does a good job of the import, but if you import a function after the package, it still mangles it. I'll take a look at that before I merge.

**Comment by agalbenus** [comment]
I just added a PR to fix imports on completions that contain functions/structs and so on

https://github.com/a-h/templ/pull/138

**Comment by jwhitaker-swiftnav** [comment]
this looks fab, thanks both!
