### ISSUE TITLE
Bug: <div>: expected end tag not present or invalid tag contents

### ISSUE THREAD

**Issue by benjiro29** [a-h/templ#141]
Take the following code:

			<div class="row">
				<div> Price </div>
				<div> Free </div>
				<div> for X month </div>
				<div> for X month </div>
			</div>

Looks perfectly valid, right? Yet, we get the "expected end tag not present or invalid tag contents" error.

No hidden characters, ... every div is properly closed. Guess where it fails on ;)

If your guessed "for", you win a price! For some reason "for" inside the div, messes with the regex of templ, and it creates an unrelated error. Remove the two times "for" and code compiles perfectly with no errors.

**Comment by gondo** [comment]
Also discussed at #653
