### ISSUE TITLE
Cannot parse empty attribute

### ISSUE THREAD

**Issue by Joe-Davidson1802** [a-h/templ#15]
nav.templ:

```
    1 {% package templates %}
    2 
    3 {% import "container/types" %}
    4 
    5 {% templ NavTemplate(apps []types.AppConfig) %}
    6     <nav data-turbo-permanent>       
    7         <h1>{%= "Go Feed Me" %}</h1>
    8         <ul>
    9             {% for _, a := range apps %}
   10                 <li>
   11                     <a href={%= a.Url %}  data-turbo-frame="container">{%= a.Name %}</a>
   12                 </li>
   13             {% endfor %}
   14         </ul>
   15     </nav>
   16 {% endtempl %}
```

nav_templ.go (it stops after the imports):

```
>>  1 // Code generated by templ DO NOT EDIT.
    2 
    3 package templates
    4 
>>  5 import "github.com/a-h/templ"
>>  6 import "context"
>>  7 import "io"
>>  8 import "container/types"
```

Strangely enough this also fails when I try 'data-turbo-permanent="true"' potentially todo with the dashes aswell?

Tried doing a "valueless" attribute without dashes like "hidden". That also resulted in the same outut.

**Comment by a-h** [comment]
Believe it not, it was just that I set the maximum length of an attribute name to 15 characters. I've updated this to 128.

**Comment by a-h** [comment]
Wouldn't mind your thoughts on: https://github.com/a-h/templ/pull/16

It would likely break your code above which uses a string:

```
{%= a.Url %}
```

This would have to be changed to:

```
{%= templ.URL(a.URL) %}
```

This would then ensure that `a.URL` is sanitised by templ, to remove potential attack vectors from the href attribute. To avoid the extra sanitisation, you'd use `templ.SafeURL(a.URL)` to mark the variable content as trusted.
