### ISSUE TITLE
docs: create an example integration with I18n for translations

### ISSUE THREAD

**Issue by gedw99** [a-h/templ#154]
Wondering if language translation workflow has been thought about yet ? 

Maybe a proper way to do it leveraging the architecture of templ.

I normally Setup these systems to do real time machine translation and then a person can check it later.

**Comment by joerdav** [comment]
Currently, with no additional changes to templ you could use it in conjunction with https://github.com/nicksnyder/go-i18n for localisation, but I think what you are suggesting is something a bit more intertwined?

```
templ myLocalisedPage() {
	if text, err := l.LocalizeMessage(ptr("page_text")); err != nil {
		<p>{text}</p>
	}
}
```

Of course you could wrap i18n for a bit more convenience, and sensible defaults:

```
templ myLocalisedPage() {
	<p>{message("page_text")}</p>
}
```

**Comment by eduardolat** [comment]
You can use a library like this: https://github.com/eduardolat/goeasyi18n

**Comment by joerdav** [comment]
Maybe this issue should be resolved via some example code and a docs page? Any takers?

**Comment by vigneshsankariyer1234567890** [comment]
Hey, I would love to take on this issue!

**Comment by gedw99** [comment]
BTW

https://github.com/invopop/gobl.html is the example that uses  https://github.com/invopop/ctxi18n

**Comment by vigneshsankariyer1234567890** [comment]
Hey, got some time to complete this. Just to clarify: would a fix for this involve adding the example within `/docs/docs/12-integrations/index.md`? Likewise, would it be sufficient to simply add an example with [ctxi18n](https://github.com/invopop/ctxi18n)?

**Comment by joerdav** [comment]
@vigneshsankariyer1234567890 it might warrant its own page, rather than being added to the integrations page. Maybe could be a child page instead?

And then an `internationalization` example within the folder https://github.com/a-h/templ/tree/main/examples

**Comment by vigneshsankariyer1234567890** [comment]
Hey @a-h @joerdav , submitted a PR a couple weeks ago! Please do take a look at it!
