### ISSUE TITLE
Handle type mismatch better

### ISSUE THREAD

**Issue by vikstrous2** [a-h/templ#158]
The first template I tried after "hello world" was
```
package main

templ Hello(name string, age int) {
	<div>Hello, { name }, { age }</div>
}
```

This actually successfully generated code, but the generated code was invalid:
![image](https://github.com/a-h/templ/assets/35113446/058c9677-3fec-4b8c-bde8-0bc1943942ee)

I would prefer it if this was either automatically handled or it errored at codegen time rather than at compile time.

FWIW the LSP did flag it
![image](https://github.com/a-h/templ/assets/35113446/d7b70b58-d7ef-4a2c-998a-9c94515d337b)

**Comment by joerdav** [comment]
@vikstrous2 thanks for the bug report, the templ compiler tries to be as hands off with the Go-part of parsing and compiling as possible, and leaves it to the Go toolchain to surface these errors. I do agree that this should not be a successful codegen though.

Currently, just before the generated file is written it is passed through go format (https://github.com/a-h/templ/blob/main/cmd/templ/generatecmd/main.go#L276), I wonder if it could be possible to pass the generated code through the Go package analyser first too.

**Comment by joerdav** [comment]
Closing for now, as you will find out about this before runtime.
