### ISSUE TITLE
Unexpected error: expected declaration, found 'package'

### ISSUE THREAD

**Issue by st3fan** [a-h/templ#159]
This version of my test project ...

https://github.com/st3fan/hello-templ/tree/2180138d135afbc505cc8960dfaa4eab61fb69d7

... is giving me the following errors that I don't understand:

```
templ generate
Processing path: /Users/stefan/go/src/github.com/st3fan/hello-templ
Generated code for "/Users/stefan/go/src/github.com/st3fan/hello-templ/hello.templ" in 1.097917ms
Error processing path: /Users/stefan/go/src/github.com/st3fan/hello-templ/page.templ source formatting error: 16:1: expected declaration, found 'package'
/Users/stefan/go/src/github.com/st3fan/hello-templ/counter.templ source formatting error: 16:1: expected declaration, found 'package' (and 1 more errors)
Generated code for 3 templates with 2 errors in 1.704333ms
```

Neither `page.templ` or `counter.templ` have a `package` declaration on line 16.

I'm really confused where this went wrong. I had working code. But after splitting it up in two files (page.templ and counter.templ) things stopped working. As an experiment I merged the code back into one file but I am still getting the `source formatting error: 16:1: expected declaration, found 'package' (and 1 more errors)` error.

Is anything cached anywhere?

**Comment by st3fan** [comment]
Ohhh removing the license header comment made the errors go away ... are comments not allowed?

```
diff --git a/counter.templ b/counter.templ
index 5be0d2a..6d6a3a7 100644
--- a/counter.templ
+++ b/counter.templ
@@ -1,7 +1,3 @@
-// This Source Code Form is subject to the terms of the Mozilla Public
-// License, v. 2.0. If a copy of the MPL was not distributed with this
-// file, You can obtain one at http://mozilla.org/MPL/2.0/
-
 package main

 import (
diff --git a/page.templ b/page.templ
index a759250..8744088 100644
--- a/page.templ
+++ b/page.templ
@@ -1,7 +1,3 @@
-// This Source Code Form is subject to the terms of the Mozilla Public
-// License, v. 2.0. If a copy of the MPL was not distributed with this
-// file, You can obtain one at http://mozilla.org/MPL/2.0/
-
 package main

 templ page() {
```

**Comment by st3fan** [comment]
Answering my own question here after a bit more debugging .. comments are certainly allowed but it seems a comment _before_ the `package` declaration is not. (It is in Go, but not in Templ)

I'm tempted to turn this issue into a bug report or feature request - what do you think @a-h ?

**Comment by joerdav** [comment]
This relates closely to #79, not quite a duplicate but something to consider when we're reworking comments!

**Comment by a-h** [comment]
I think that allowing comments before the package declaration is completely reasonable. It's common in the standard library, for example https://cs.opensource.google/go/go/+/refs/tags/go1.21.1:src/time/format.go

templ doesn't really need to parse the `package` declaration at all in the current design. In earlier verisons, you could leave out the `package` declaration). In the current version, up until you type `templ ` or `css ` or `script ` to make a template, it's just Go code. So maybe it's time to rethink that section of the parser and make it more general.

v2 has been out since June 2022. In another 9 months, it will be time to consider dropping the v1 parser and the `templ migrate` command from the codebase.

**Comment by a-h** [comment]
I've started work on this at https://github.com/a-h/templ/tree/issue_159_go_comments_before_package

Need to add tests though.

**Comment by a-h** [comment]
I believe I've resolved this issue in https://github.com/a-h/templ/commit/c1998f6ad53c473a3bbc6ab299e0410099640143

It will be included in the next release.

Feel free to re-open this issue if it hasn't solved your issue.
