### ISSUE TITLE
URL parameters are rendered with sanitized quotes

### ISSUE THREAD

**Issue by ezynda3** [a-h/templ#165]
I have some js that depends on a URL set in an Env variable. I pass it as a string parameter to my my component and then use a script component to run the actual js.

```
// HTML component
templ myComponent(url string) {
<div onload={ myScript( templ.URL(url)) }>
 ....
</div>
}
```

```
// Script component
script myScript(url templ.SafeURL) {
...
}
```

```go
myComponent(os.Getenv("URL_VAR").Render(ctx, w)
```

The problem is the url is always rendered like this in the final html
```html
<div onload="__templ_myScript_bab0(&quot;http://127.0.0.1:8090&quot;)"></div>
```

This obviously breaks my JS code as it's not a valid URL...

What's the best way to pass URLs like this to JS?

**Comment by a-h** [comment]
Hi, thanks for trying out templ.

I've tried to reproduce the issue here https://github.com/a-h/templ-issue-165 - but for me, it appears to be working fine.

```html
package main

script show(message string) {
	alert(message)
}

templ page(message string) {
	<!DOCTYPE html>
	<html>
		<head><title>Test</title></head>
		<body>
			<h1>Test</h1>
			<input type="button" value="Click me" onclick={ show(message) }/>
		</body>
	</html>
}
```

It renders out to this (I ran it through a formatter for legibility):

```html
<!doctype html>
<html>
   <head>
      <title>Test</title>
   </head>
   <body>
      <h1>Test</h1>
      <script type="text/javascript">function __templ_show_3e0b(message){alert(message)}</script><input type="button" value="Click me" onclick="__templ_show_3e0b(&#34;https://www.google.com&#34;)">
   </body>
</html>
```

And clicking the button shows the expected URL.

<img width="998" alt="Screenshot 2023-09-24 at 17 17 39" src="https://github.com/a-h/templ/assets/1029947/107fe88e-124e-4aaa-8700-37dd9219292b">

What error are you seeing?

**Comment by ezynda3** [comment]
Ok. Looks like the URL is represented correctly when it reaches my script. I guess I was doing something wrong before. I just thought it was weird that it is represented as unescaped in the event declaration.

i.e. `onclick="__templ_show_3e0b(&#34;https://www.google.com&#34;)"`

Thanks again.

**Comment by ezynda3** [comment]
Closing
