### ISSUE TITLE
How to handle literal text that contains a reserved word?

### ISSUE THREAD

**Issue by nics** [a-h/templ#168]
```
templ contact(link, text string) {
 <p>Contact <a href={ link }>{ text }</a> for more information.</p>
}
```

This generates a templ compile error because of the for in "for more information":

```
for: unterminated (missing closing '{'): line 15, col 1
```

**Comment by joerdav** [comment]
Thanks for raising this issue, it has in fact already been raised at #141 

We're looking to improve the error messaging to suggest what @evanlurvey has written here, rather than allowing a potentially invalid for loop to be leaked to a frontend.

**Comment by a-h** [comment]
Now that the docs are updated, and the change has been released (https://github.com/a-h/templ/releases/tag/v0.2.408), I'm going to close this.

Thanks for raising the issue!
