### ISSUE TITLE
Logo for vscode material icon theme 

### ISSUE THREAD

**Issue by kidus-tiliksew** [a-h/templ#171]
It would be nice to include the templ logo to the material icon theme here

https://github.com/PKief/vscode-material-icon-theme

**Comment by a-h** [comment]
If someone is up for making that change, that would be great.

The contribution guide is pretty clear https://github.com/PKief/vscode-material-icon-theme/blob/main/CONTRIBUTING.md#add-new-icons

There's an SVG of the templ logo https://github.com/a-h/templ/blob/main/logo/logo.svg - it's basically just a specific font being used to draw a `</>` for use as a base.

**Comment by kidus-tiliksew** [comment]
Done 

https://github.com/PKief/vscode-material-icon-theme/pull/2102

**Comment by a-h** [comment]
Thanks a lot for doing that, much appreciated!
