### ISSUE TITLE
Compiler won't accept CSS component class name as parameter to KV func

### ISSUE THREAD

**Issue by mkraft** [a-h/templ#186]
I have a CSS component

```
css foo() {
    background-color: red;
}
```

and I'm trying to use it conditionally [as outlined in the docs](https://templ.guide/syntax-and-usage/css-style-management/#css-components) 

```
<div class={templ.KV(foo, true)}></div>
```

but the compiler is rejecting it with the error

```
func() templ.CSSClass does not satisfy comparable
```

**Comment by a-h** [comment]
Oops, that looks a problem with the docs. It should probably read `foo()` not `foo`.

```
<div class={templ.KV(foo(), true)}></div>
```

Since without the brackets, it passes a function as the key, not the result of calling the function.

**Comment by a-h** [comment]
I've  pushed an update to the docs, sorry for the confusion, and thanks for trying templ. Of course, feel free to reopen this, or raise something else if it's not resolved for you.
