### ISSUE TITLE
Bug with CSS components

### ISSUE THREAD

**Issue by wdscxsj** [a-h/templ#195]
In the example for [CSS components](https://templ.guide/syntax-and-usage/css-style-management/#css-components), if `isPrimary == true`, then the class name for `primaryClassName` is properly generated, but its CSS styles are missing in the output. `isPrimary == false` works fine.

**Comment by a-h** [comment]
Oh no! Nice catch for that one, much appreciated! I've fixed the issue, thanks for discovering and reporting the issue.
