### ISSUE TITLE
Get this tool into awesome-go

### ISSUE THREAD

**Issue by a-h** [a-h/templ#196]
To get into the awesome-go repo, this repo needs to meet some standards... https://github.com/avelino/awesome-go/blob/main/CONTRIBUTING.md

I added the Code Coverage label today, but we need a link to the Go Report Card in the README. I can also see one or two formatting things to fix on there (ignore the cyclomatic stuff).

The formatting of those badges is usually on one line. Maybe copy what another Go repo has done.

Does someone want to pick up those nits and do the PR into awesome-go?

**Comment by valxntine** [comment]
Happy to pick this up! Though it looks like awesome-go expects >=80% coverage? 

> if the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data-related packages. (Note: the tests will be reviewed too. We will check your coverage manually if your package's coverage is just a benchmark result);

**Comment by a-h** [comment]
I think that a lot of the low coverage is due to `if err != nil` checks in the generated code. 😁 Lots of those error branches are therefore untested. I'd expect people to exercise a  bit of common sense - templ is well tested with unit and integration (generation / render) tests.

It did get me thinking about how I could create an `io.Writer` that returns an error after `x` bytes though. In that way, I could run the render function multiple times, returning errors after every 4 bytes to check that the error is returned to the caller.

But... I have to question the utility of that. I think that's more about sport than it is about quality.

On the same side, there's a lot of parser error branches that aren't tested for similar reasons. However, the parsers will never throw errors, so it's very hard to test those lines!

If you spot an untested area that's clearly just missing some decent tests, if you raise an issue, that would be great!

**Comment by valxntine** [comment]
Nothing short of awesome for sure 😂

Sounds good, I'll have a look over the codebase this evening, fix up the README with the badges and once all is in order I'll raise the PR in awesome-go, highlighting the reason for low coverage. Is there any way we can get a coverage stat disregarding the generated files? I could do so locally and provide that on the PR to awesome-go, just wondering if that can be done for the badge in this repo?

**Comment by a-h** [comment]
Oops, I've closed this too early! It's not in awesome-go yet.

**Comment by valxntine** [comment]
Haha, didn't even realise! Had a super busy week after my holiday - got some down time this weekend though and it's on my list of todos 😄

**Comment by valxntine** [comment]
Just got an email notifcation @a-h that my PR was merged: https://github.com/avelino/awesome-go#template-engines

**Comment by a-h** [comment]
Legend. Thanks @valxntine ! 😁
