### ISSUE TITLE
cmd: Add an option to output to file or stdout

### ISSUE THREAD

**Issue by rowan-gud** [a-h/templ#197]
## Problem

It doesn't seem like there is an option to output to stdout or to a file location.

## Reasoning for wanting this feature

Trying to use templ with bazel and add a custom rule and want to do something like
```starlark
genrule(
  name = "index_templ",
  srcs = ["index.templ"],
  outs = ["index_templ.go"],
  cmd = "templ generate -f $< -o $@", # or templ generate -f $< > $@
)
```

If there is another way to do this or something I am missing in the docs please let me know!

**Comment by a-h** [comment]
I'm not familiar with Bazel.

From reading the docs, it looks like it tries to do some stuff around caching build outputs, but the Go tooling does that already for Go packages.

Can you explain the use case a bit more? Are you trying to use it to remember to run `templ generate` if the `*.templ` files have changed?

**Comment by rowan-gud** [comment]
Yeah so my use case for Bazel is having a mono repo with multiple build artifacts and Bazel handles the dependency tree + build caching etc.

My reasoning for wanting to put templ generate into Bazel is more of convenience of having a single build command. Right now I'm not checking in my `_templ.go` files but I could see having my CI incrementally build those too.

I will take another look at the PR. Thank you!

**Comment by rowan-gud** [comment]
Yeah it would be able to accomplish that with `templ generate -o /path/to/location/dir`

**Comment by ReneHollander** [comment]
To workaround the missing option to specify the output directory for now, the following works for a genrule in a directory called `frontend`:

```
genrule(
    name = "main_templ",
    srcs = ["main.templ"],
    outs = ["main_templ.go"],
    cmd = "$(location @com_github_a_h_templ//cmd/templ:templ) generate -f $< && cp frontend/main_templ.go $@",  # or templ generate -f $< > $@
    tools = ["@com_github_a_h_templ//cmd/templ"],
)
```

It might be possible to improve on this. The hardcoded `frontend/main_templ.go` value would need to be changed if the input file of `main.templ` is moved/renamed.

**Comment by moshe5745** [comment]
+1

**Comment by moshe5745** [comment]
I think it will be just better DX to have all the generated files in one place so they don't mix with our code.

**Comment by joerdav** [comment]
So it looks as though the way forward here is to support printing generated files out to stdout, this will allow greater flexibility for those with different use cases.

This could work similarly to the `fmt` command? `templ generate < file.templ`

**Comment by jimafisk** [comment]
It would be awesome if there was an "output" flag (`-o`) to generate to a different directory :)

**Comment by joerdav** [comment]
I will mark this to reflect the state, we are looking to add the option to take a templ file from stdin and pipe it to stdout. That way anyone is free to create their own CI pipelines that generate and put their generated files in other folders if that suits them, though this approach would not work with the current tooling around templ so wouldn't be supported out of the box.

**Comment by joerdav** [comment]
The module file is checked because there are 2 dependencies for templ, the binary for generation, and the runtime dependency that is defined in the go.mod, a difference here can sometimes result in undefined behaviour. It should just be a warning rather than a failure though.

In terms of your suggestion 2 @yesudeep that's the goal of this issue, to support a simple stdin stdout option.

**Comment by a-h** [comment]
To clarify, if the go mod check fails, it's just a message on stdout, it doesn't set a non-zero exit code.

There was a recent PR to add a stdout mode to the `templ fmt` command. I'd be up for something similar on `templ generate` for single files. The PR is here, for a reference implementation: https://github.com/a-h/templ/commit/e3085d083da57fcac60961f14bcc1a63ccb8ceac

I'm not interested in setting a different output directory to the directory the Go code is in.

**Comment by joerdav** [comment]
I've implemented a fix for this. I started with the same API as `templ fmt` wherein if no path is specified the it accepts from stdin, however this can't work, as the generation process requires context such as the filename of the template, so I opted for a stdout flag in combination with the -f flag.

**Comment by jimafisk** [comment]
I'm not sure if this is the right approach, but I don't track the templ generated `.go` files with git and they make it difficult to navigate the directory with the `.templ` files I want to edit, so I just updated my build process (using [air](https://github.com/cosmtrek/air)) to move the generated files to a `tmp/` directory.

Here's the relevant parts of my `.air.toml` file:

```toml
root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/myproj serve"
  cmd = "templ generate && mv views/*.go tmp/views/. && go build -o ./tmp/myproj ."
```

Then just update your imports to point to the right place:
```go
import (
  "github.com/myorg/myproj/tmp/views"
)
```

And `.gitignore` your `tmp*` directory. 

It works, although doing this does seem to make the language server throw errors in the editor that imported components are undefined.
