### ISSUE TITLE
vscode: slight syntax-coloring bug encountered within a <script> inside a `templ`

### ISSUE THREAD

**Issue by metaleap** [a-h/templ#204]
**Note: low-prio issue because the workaround is double-quoted instead of single-quoted JS strings  =)** — but for the curious dev/maintainer...

Check out the red ones in lines 9-10, in this Color Theme this is not my "string color" but my "lexical/syntax error (aka unrecognizable token sequence) at the theme's selector/regex stage" color:

![image](https://github.com/a-h/templ/assets/22109/40b7a420-e5c8-4f6e-8152-fd512d06812c)

Sufficiently shortened repro pastie:

```templ
package client

templ Page_Login(it *Ctx) {
	@Page(it, "Login") {
        <script>
        function refrBtns() {
            document.title = new Date().getTime().toString() // temp to see calls
            refreshEnabled({
                'login_submit': ['user_email', 'user_pass'],
                'login_forgot': ['user_email']
            })
        }
        </script>
		<div>
        </div>
        <script>refrBtns();</script>
	}
}
```

To reproduce, might have to flip through a few of your Color Themes before finding one with specific lexical-error rendition defined.

Btw **side note 1:** I was originally declaring this function not in a `<script>` but templ's `script` notation. But notice the call at the bottom, that failed because it did not translate to the auto-generated function identifier.

Which inspires **side node 2:** when generating Go code, might want to output similarly-generated-identifiers for `ctx` and `w` and `err`, so they are freed up for custom usage inside `templ`s. Right now the generated ones would shadow own ones if one were to have them.

**Comment by a-h** [comment]
Thanks for raising this. I did read it earlier, but didn't have time to think about it properly.

On your second side note, that's resolved in the latest release. There's now much more complex names for generated code, to prevent accidental variable shadowing.

If someone wants to have a go at fixing the highlighting, then the task is...

* Modify this file and map the contents of `script` tags to the built-in `source.js` TextMate grammar - https://github.com/a-h/templ-vscode/blob/main/syntaxes/templ.tmLanguage.json
* You can test it by opening the `templ-vscode` project and hitting run. There's an "inspect" feature in VS Code that lets you see which regexp sections have been applied to the file.

<img width="804" alt="Screenshot 2023-10-15 at 16 04 39" src="https://github.com/a-h/templ/assets/1029947/9a37cfdb-5cde-40f7-bd6e-9abb2dc9e923">

**Comment by metaleap** [comment]
I'd probably take a stab at this except I changed direction toward client-side (vanjs) not server-side rendering, seeing how in the apps I'm tackling, the bulk of frontend work is scripting not markup.

Still will remember this brilliant alternative for Golang-driven SSR when the arises.  =)

**Comment by a-h** [comment]
Is this still a problem? There's been a lot of improvements to the vs code syntax highlighting by @alehechka and @sirgallifrey

**Comment by joerdav** [comment]
I have verified that these tokens are now being marked correctly as `string.quoted.single.js`.
