### ISSUE TITLE
Templ fmt does not format go code

### ISSUE THREAD

**Issue by gungun974** [a-h/templ#208]
### Introduction (you can skip that part if you want)
So I like go.

I like this project which for me gives even more reason to like go (because the HTML template module seems horrible to me when used in comparison)

**The thing that makes me love this project even more than its syntax is its LSP server**

In general, HTML is error prone to a lot of things. Including just misspell a variable to inject. 
So need to manage all of this without a good support from my editor like JSX is a deal breaker for me.

But fortunately the LSP server of Templ is here to save me and I'm very happy with it ^^

### Problem

However, I have a problem with the formatting aspect of Templ.

Templ is a kind of superset of Go. You can declare in your file package, variable, function like you do in normal go.
In fact the generator just insert the raw go code in generated files.

This work great, specially with the LSP and reuse of Gopls.

However I can't said it's the same for `templ format`.
This command only format Templ syntax when the parser produce a formated code.

So in example like this :

```go
type Link struct {
  	Name string
	Url  string
}

      var a = false;

func test() {
    	log.Print("hoi")

      if (a) {
        log.Fatal("OH NO !")
      }
}
```

`templ fmt` don't produce what `gofmt` would do, this in this case :

```go
type Link struct {
	Name string
	Url  string
}

var a = false

func test() {
	log.Print("hoi")

	if a {
		log.Fatal("OH NO !")
	}
}
```

This is very annoying cause I love the idea of creating variable and function in the same file of the templeting for tiny function but the fact I need to manually format my file make me stress :eyes:

So as in my new tradition of wanting absolutely everything as quickly and without the slightest effort for the maintainers to exist. ***I created a PR to resolve the issue which I'm happy to share*** #209.

**Comment by a-h** [comment]
Thanks for raising this issue, and for providing a PR to fix it. Much appreciated!
