### ISSUE TITLE
How to add a "safe" CSP for templ generated HTML and Javascript

### ISSUE THREAD

**Issue by leonyork** [a-h/templ#220]
When I use a script in templ, if I want to use a content security policy (CSP), then I need to include a `script-src 'unsafe-hashes'` CSP because any javascript included in an html attribute (e.g. onload) needs the unsafe-hashes CSP.

The suggestion from [the unsafe-hashes CSP page](https://content-security-policy.com/unsafe-hashes/) is:

> Whenever you see the prefix unsafe in a CSP keyword, that means that using this is not the most secure way to go. It is better to refactor your code to avoid using HTML event handler attributes (such as onload, onclick, onmouseover etc.)

Of course you might accept the risk of having an unsafe CSP depending on what your app does, but many organisations will enforce a "safe" CSP.

The example in [this repo](https://github.com/leonyork/templ-csp-example) has a [page with a script](https://github.com/leonyork/templ-csp-example/blob/main/components/page.templ). When served, this generates a page that looks like:

```html
<!doctype html>
<html lang="en">
    <head></head>
    <script type="text/javascript">
        function __templ_App_1e4f() {
            console.log("Loaded!")
        }
    </script>
    <body onload="__templ_App_1e4f()">
        <h1>Check the console for a log!</h1>
    </body>
</html>
```

Since the `body` tag includes an `onload` attribute with javascript in it, we need to include `unsafe-hashes` in the CSP.

Note that the repo above has some tests in to validate any fix.

Looking at the conversation in https://github.com/a-h/templ/issues/126 a potential solution could be what I've done on the `no-changes` branch (see [the diff](https://github.com/leonyork/templ-csp-example/compare/main...no-changes)). So potentially this could just be a change to the documentation to explain how to use a safe CSP. 

As an improvement to what's on the `no-changes` branch we could add the scripts or the `sha-256`'s to the context too to allow them to be picked up separately and added to the header. I don't want to go too far down this route though before hearing other opinions and ideas!

**Comment by joerdav** [comment]
Just thinking outloud here, but how would this work with something like HTMX? I wonder if a partial update of a page with a script element will hit the same issue. Does HTMX support ammending the CSP rules? Or do CSP rules need to be set on page load only?

**Comment by leonyork** [comment]
'ey up @joerdav! Good question. I've added [the htmx branch](https://github.com/leonyork/templ-csp-example/tree/htmx) to my example repo and from [the diff](https://github.com/leonyork/templ-csp-example/compare/htmx) you can see I've added the htmx library along with the [htmx handler](https://github.com/leonyork/templ-csp-example/compare/htmx?expand=1#diff-2a2b4337e4fe3799a36ef87d8928e22b0c11785acddc2727976eaf0f59601e71R14) that responds **without** a CSP header. All I needed to do was add the [htmx SHAs](https://github.com/leonyork/templ-csp-example/compare/htmx?expand=1#diff-2a2b4337e4fe3799a36ef87d8928e22b0c11785acddc2727976eaf0f59601e71R34) to the CSP, although note two things:

1. Since htmx by default tries to add indicator classes through javascript, we need the `style-src` CSP (see https://github.com/bigskysoftware/htmx/issues/1062).
2. It is the `connect-src 'self'` part of the CSP that allows the page to perform the `hx-get` request. Whilst this is added by default if you include the `default-src 'self'` CSP, I thought in the code I'd make it more explicit by changing that `default-src 'self'` to `connect-src 'self'`.

The [htmx-no-changes branch](https://github.com/leonyork/templ-csp-example/tree/htmx-no-changes) shows that taking the same approach, even with htmx, works. 

To summarise: adding `htmx` doesn't fundamentally change the approach - whatever approach you take, including  `connect-src 'self'` in the CSP will be enough for `htmx` requests to work. As with any library, you'll need to include something (e.g. a SHA) in the CSP to allow the browser to load the library.
  
Tackling the other bit of your question, if the `hx-get` request responds with a `script` tag alongside the html, then this will need to be included in the CSP for the initial request for the whole page - see the failing example on the [htmx-with-script branch](https://github.com/leonyork/templ-csp-example/tree/htmx-with-script). From my understanding there's no way to update the CSP from new requests (or using htmx). So you'd need to know what scripts your `hx-get`s were going to respond with "ahead of time" so that they could be included in the CSP for the main page. An alternate approach here might be to explore using a `nonce` (although we'd need to remember the nonce between the main page request and the `hx-get`).

**Comment by joerdav** [comment]
Templ now supports rendering `scripts` as script elements directly. https://templ.guide/syntax-and-usage/script-templates#script-templates

So this would allow you to avoid having to write a custom `inline` component, when you're rendering scripts.

I had to do some investigation around struct transport recently as part of the day job, and think a possible solution would be for a `nonce` to be allowed to be passed into the render context (which I think you alluded to), and any script/style tag that is created will be decorated with it.

**Comment by leonyork** [comment]
Thanks for this. A little busy at the minute, but will take a look!

**Comment by egtann** [comment]
I was able to solve the CSP problem with HTMX+Templ for my use-case. Hopefully this can help others: https://gist.github.com/egtann/0f686c0fadbd3c52121dc910b849ed3e

**Comment by joerdav** [comment]
Thanks for those participating in the conversation, it seems we now have various approaches for those that encounter this.
