### ISSUE TITLE
custom elements: element property names must be < 16 characters long

### ISSUE THREAD

**Issue by brattonross** [a-h/templ#221]
I've got some JavaScript that registers a [custom element](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements) which has a name that is >15 characters in length. When I attempt to use this custom element in a `.templ` file, the code fails to compile with the error:

> failed to process path: /some/path/to/template.templ parsing error: element property names must be < 16 characters long

Are custom elements something that templ aims to support?

**Comment by joerdav** [comment]
This should be fixed in main now:
#212

**Comment by a-h** [comment]
Released in https://github.com/a-h/templ/releases/tag/v0.2.408
