### ISSUE TITLE
CSS module invoked via templ.KV in loop does not render style tag

### ISSUE THREAD

**Issue by mkraft** [a-h/templ#222]
I have a CSS component

```
css topEdge() {
    border-top: 1px solid black;
}
```

and an element that invokes the CSS component within a call to `templ.KV`

```
templ Item() {
    <div class={ templ.KV(topEdge(), true) }></div>
}
```

and the element is invoked from a loop.

```
...
for i := 0; i < 10; i++ {
    {! Item() }
}
...
```

The problem is, while the class name appears as the value of the `class` attribute in the `<div>`, and the compiler doesn't have any errors,

```html
<div class="topEdge_b8f6"></div>
```

the associated `<style>` definition for `.topEdge_b8f6` doesn't render to the template.

However, if I add a call to the `topEdge()` directly within the loop

```
...
for i := 0; i < 10; i++ {
    <input type="hidden" class={ topEdge() } />
    {! Item() }
}
...
```

then the `<style>` tag is rendered in the markup

```html
<style type="text/css">.topEdge_a978{border-top:1px solid black;}</style>
```

**Comment by a-h** [comment]
Thanks for trying out templ, and for reporting this issue.

I'm sorry, but there was a bug in this particular feature. It was fixed in https://github.com/a-h/templ/commit/8543facd16e4f932bb59ec2900d02b26a9702f9d but I haven't shipped a new release yet.

**Comment by a-h** [comment]
Released as https://github.com/a-h/templ/releases/tag/v0.2.408
