### ISSUE TITLE
VSCode extension not working

### ISSUE THREAD

**Issue by jaysson** [a-h/templ#223]
I get the following error when I open the project. `templ` is in the path.

```
[Error - 2:06:20 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:06:20 PM] Connection to server got closed. Server will not be restarted.
[Error - 2:06:20 PM] templ client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by jaysson** [comment]
This was because I had changed GOPATH.

**Comment by a-h** [comment]
Glad you got it sorted! 😁

**Comment by oitan** [comment]
@jaysson @a-h does GOPATH have to have some value in it? My `echo $GOPATH` is empty, I thought there is a default value for such cases, no? I'm having the same error code in vscode, unfortunately
