### ISSUE TITLE
templ generate not working for multi line arguments

### ISSUE THREAD

**Issue by julianooi** [a-h/templ#232]
Hi there, i'm encountering an issue when having multi line in the function arguments.

this doesn't work, but if i remove the new lines, it works.

also, moving the type declaration to another file works for both, it's only an issue when it's in the same .templ file.

doesn't work
```go
package components

type expense struct {
	A string
}

templ Expense1(
	params expense,
) {
	<div></div>
}

```

works
```go
package components

type expense struct {
	A string
}

templ Expense2(params expense) {
	<div></div>
}
```

error when running `templ generate`
```
failed to process path: <.templ file path>  source formatting error: 16:1: expected declaration, found templ
```

**Comment by a-h** [comment]
Thanks. That's currently a limitation of the templ parser. The current implementation is at https://github.com/a-h/templ/blob/main/parser/v2/templateparser.go - it looks for the `templ ` prefix and then assumes that everything until the next linebreak is Go code.

To support multi-line arguments for templ functions, would need to parse the code after "templ" with the Go parser up until the opening brace of the template body.

**Comment by a-h** [comment]
@julianooi - got a draft PR change to the templ parser that will fix this issue, I added a test that demonstrates the fix.

**Comment by joerdav** [comment]
This is now fixed.
