### ISSUE TITLE
syntax highlighting - add support for Go comments in Neovim plugin

### ISSUE THREAD

**Issue by a-h** [a-h/templ#234]
Go comments in templates was added as a feature in https://github.com/a-h/templ/commit/c1998f6ad53c473a3bbc6ab299e0410099640143

However, the Neovim plugin doesn't reflect this in the syntax highlighting.

<img width="424" alt="Screenshot 2023-10-14 at 09 51 22" src="https://github.com/a-h/templ/assets/1029947/ad244c45-8838-40cd-98f5-56572413bf75">

Supporting this requires an update to the syntax highlighting setup.

**Comment by valxntine** [comment]
Might have a couple of clarifying questions but I get back from holiday tomorrow and would be keen to pick this up if it's still available!

**Comment by a-h** [comment]
Great!

It's not actually in templ, but over in https://github.com/vrischmann/tree-sitter-templ for the Treesitter version, and https://github.com/joerdav/templ.vim for the standard version.

The grammar for Treesitter is here https://github.com/vrischmann/tree-sitter-templ/blob/master/grammar.js

I just updated the VS Code plugin to add the feature, so you may be able to steal some ideas from there. (I took the bits I needed from the Go grammar, so I expect that if you find the Go treesitter grammar, you can take what you need).

**Comment by BKR-dev** [comment]
@valxntine I got bored so I just made a PR not actually knowing what's going on https://github.com/vrischmann/tree-sitter-templ/pull/6

**Comment by BKR-dev** [comment]
the linked PR got merged so this is done and can be closed @valxntine made it happen!
