### ISSUE TITLE
feature request - update the generator to warn or upgrade if the templ runtime version is not the same version as the generator executable

### ISSUE THREAD

**Issue by a-h** [a-h/templ#249]
In https://github.com/a-h/templ/issues/235 there was an issue that was fixed by updating the runtime.

However, updating the generator and running `templ generator` didn't let anyone know.

It could be that the generator is updated and comes to rely on a non-API-breaking change in the templ runtime that isn't present. Either way, updating the `generate` command to:

* If the `templ generate` command version < templ runtime version - warn about mismatched versions
* If the `templ generate` command version > templ runtime version - run a `go get` automatically

One point to note is that the current Nix flake, and the local snapshot install, shows `(devel)` because it's built from source and the version number isn't applied. I'd want to fix that before doing this.

**Comment by joerdav** [comment]
Sounds like a useful warn to have, I wonder if there could be a way to define version mismatches that should trigger an error rather than a simple warning. "The templ version defined in your go module contains bugs x/y/z it is strongly recommended you upgrade, to surpress this warning use --someflag".


> If the templ generate command version > templ runtime version - run a go get automatically

My other thought is that this could cause some unwanted and confusing side effects in a CI pipeline. I think just breaking or warning is safer. (maybe with some color to emphasize warnings)

**Comment by PentesterPriyanshu** [comment]
can you assign this issue to me i am ready to work on it

**Comment by PentesterPriyanshu** [comment]
sir i have to write the script ,which starts by extracting and comparing the version numbers of the Templ runtime and the generator executable. If the versions match, it  continues with the template generation process. However, if a version mismatch is detected, the script issues a warning to the user, indicating the disparity and advising them to upgrade the Templ runtime to the latest version, using the flag for convenience.

after the version check, warning, and potential upgrade prompt, the script proceeds to generate the required template. To maintain a clean and efficient workflow, the script utilizes temporary file management, creating a temporary file for internal processing and removing it once the template generation is complete. This process helps maintain a streamlined and organized working environment for the user.

**Comment by a-h** [comment]
Yesterday, I updated the CLI to auto-increment the commit number, but since the generated files now all contain an up-to-date version number, it's causing git churn.

I think that the next step is to make including the version number (and generated date/time) in the build output optional as per https://github.com/a-h/templ/issues/123#issuecomment-1777724991

The generator.go file includes some code to write out a comment which includes a version.

```go
func (g *generator) writeCodeGeneratedComment() error {
	_, err := g.w.Write(fmt.Sprintf("// Code generated by templ@%s DO NOT EDIT.\n\n", version))
	return err
}
```

We need to update the generator so that:

* The generated statement doesn't include the version number.
* Optionally, beneath that statement, the version number is included as a line of `// templ: version: %s`
   * I'd like the option to be passed in as one of those variadic options `generator.Generate(template, w, generator.WithVersion())`
   * I'd also like the option to include the date/time of the commit, is RFC339 format: `// templ: generated: 2023-06-01T00:00:00Z` etc., and the option `generator.WithTimeStamp()` - this will satisfy https://github.com/a-h/templ/issues/123
* By default, the version number and timestamp is not outputted.
* The `templ generate` command has two new flags for `-include-version` and `-include-timestamp` which are false by default.

@PentesterPriyanshu - if you're up for that, I'll take a PR. Just let me know!

**Comment by a-h** [comment]
@PentesterPriyanshu - you're too late for this one now, I've done the changes above.

**Comment by a-h** [comment]
The final change is to make the generator warn about potential templ version mismatch.
