### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [a-h/templ#259]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/a-h/templ/assets/147402107/a6caf25d-32a8-4912-b6cb-eecc3ad9843c)

**Comment by Kalyanimhala** [comment]
@a-h  Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by a-h** [comment]
Contributors are already listed.

<img width="402" alt="Screenshot 2023-10-28 at 22 03 24" src="https://github.com/a-h/templ/assets/1029947/20615848-09b1-4ad3-8c0b-6af600318940">

**Comment by Kalyanimhala** [comment]
Okay, Thanks!!
