### ISSUE TITLE
misc: Write a lexer for Pygments

### ISSUE THREAD

**Issue by joerdav** [a-h/templ#266]
This isn't really a code change to this repo, but thought it would be worth tracking here.

# What

Write a lexer for the [Pygmens](https://pygments.org/) syntax highlighting tool. 

There's a guide here on how: https://pygments.org/docs/lexerdevelopment/

And it may be useful to reference both the Go and HTML lexers:

https://github.com/pygments/pygments/blob/master/pygments/lexers/go.py

https://github.com/pygments/pygments/blob/master/pygments/lexers/html.py

# Why

Pygmens is the syntax highligher that Github uses, so completing this would make for some colourful code in the github web app.

**Comment by cugu** [comment]
This would also enable templ support in https://github.com/alecthomas/chroma, which would be nice for server side syntax highlighting in Go.

**Comment by joerdav** [comment]
Agreed... it's becoming a bit of a risk for changing the language design, having to go and update all the parsers!

Textmate rings a bell, I believe that may also work with jetbrains for https://github.com/templ-go/templ-jetbrains

**Comment by cugu** [comment]
There is also the [prism.js](https://github.com/a-h/templ/blob/main/docs/src/theme/prism-include-languages.js) syntax highlighter for the docs.

**Comment by a-h** [comment]
Ah yes, thanks! I think it could be possible to swap out the docs to use https://shiki.matsu.io which also uses TextMate.

There's a Docusaurus plugin, but I took a look at your templ documentation site, and it's started to look amazing, so maybe we won't need it. ;)

**Comment by joerdav** [comment]
Github uses Linguist, so I will close this as we have a PR in for linguist.
