### ISSUE TITLE
Syntax Highlighting Issue in VS Code for Multiline Import Expressions

### ISSUE THREAD

**Issue by ccitro** [a-h/templ#268]
**Description:** Syntax highlighting fails in VS Code when import expressions span multiple lines. This issue occurs even though the template compiles and functions correctly. The problem seems isolated to syntax highlighting.

**Steps to Reproduce:**
1. Use a multiline import expression in a template.
2. Observe that syntax highlighting breaks for subsequent code.

**Minimal Test Case:**
```go
package components

type ExampleButtonParams struct {
    Text string
}

templ ExampleButton(params ExampleButtonParams) {
    <button>{params.Text}</button>
}

templ ExampleCaller() {
    @ExampleButton(ExampleButtonParams{
        Text: "Hello World",
    })
}

templ ExampleProblem() {
    <div>Not highlighted correctly</div>
}
```

**Expected Result:** Consistent syntax highlighting throughout the file.

**Actual Result:** Syntax highlighting breaks after the `ExampleCaller` template.

**Screenshot:**
![Incorrect Syntax Highlighting](https://i.imgur.com/UgymD3i.png)

**Additional Information:**
- Combining the `@ExampleButton(ExampleButtonParams{...})` import into a single line resolves the issue.
- Suspected cause might be related to the import-expression regex in `templ.tmLanguage.json`, but unconfirmed.

**Environment:**
- Test Repository: [templ-vscode-issue](https://github.com/ccitro/templ-vscode-issue/)
- Extension Version: v0.0.15

**Comment by ccitro** [comment]
I dug into the extension and confirmed that the begin/end regex for import-expression were causing the issue. I made some adjustments to them, and it seems to have resolved the issue in the test cases I came up with.

I created a [pull request](https://github.com/a-h/templ-vscode/pull/16); I hope it helps.

**Comment by a-h** [comment]
Just noticed that I didn't close this when I merged the PR. Thanks again for the contribution!
