### ISSUE TITLE
Templ CLI doesn't return a non-zero exit code on error

### ISSUE THREAD

**Issue by temos** [a-h/templ#278]
Hello,

I've noticed that when chaining commands with the Templ CLI, it didn't matter whether the command succeeded or not.

In this example, given that the generation fails, I would expect `templ generate` to return a non-zero exit code, thus preventing the commands after it from executing.
```shell
templ generate && go run .
```

This, however, does not happen. I've taken a quick look at the code and it appears the non-zero status code is actually returned by the `generateCmd` function in cmd/templ/main.go, but it is ignored. The following is a snippet of the code:
```go
func run(w io.Writer, args []string) (code int) {
	if len(args) < 2 {
		fmt.Fprint(w, usageText)
		return 0
	}
	switch args[1] {
	case "generate":
                //generateCmd returns the exit code, but it's ignored
		generateCmd(w, args[2:])
		return
...
```

Based on this, the solution might be just returning the exit code, but I'm unsure whether there is a reason for it being this way I'm not seeing:
```go
func run(w io.Writer, args []string) (code int) {
	if len(args) < 2 {
		fmt.Fprint(w, usageText)
		return 0
	}
	switch args[1] {
	case "generate":
		return generateCmd(w, args[2:])
...
```

It would also be required to handle it in `main` which might look something like this:
```go
// now
func main() {
	run(os.Stdout, os.Args)
}

// changed
func main() {
	exitCode := run(os.Stdout, os.Args)
	os.Exit(exitCode)
}
```

The `generate` subcommand is not the only one affected, it's just the one I tested. Based on the code in the `run` function, returned exit codes are ignored for all subcommands.

**Comment by a-h** [comment]
Thanks for that! Nicely written up, much appreciated.
