### ISSUE TITLE
Add generation warning for legacy template call expression.

### ISSUE THREAD

**Issue by joerdav** [a-h/templ#279]
Currently template supports two forms of template call expressions.

The original legacy format:

```
{! myComponent }
```

And the newer format which was designed to be more ergonomic with template block expressions:

```
@myComponent
@myLayout {

}
```

I don't believe that templ should support both of these, but to avoid breaking existing users I think it would make sense to do one or a combination of the following:

- An LSP warning when using the legacy format.
- An LSP code action to fix the legacy format.
- A warning on `templ generate` when using the legacu format.
- A command to fix all occurences in a project (could leverage `templ migrate`)

Along with a plan of when/if to remove it in a future major release.

**Comment by a-h** [comment]
Closed in #280
