### ISSUE TITLE
Straight up not working

### ISSUE THREAD

**Issue by gutrapp** [a-h/templ#317]
Folder structure:

| cmd
\ server
 | main.go
| internal
 \ view
  | index.templ

When I run templ generate it create the file but it is essentially empty, this is what is inside of it:

```go
// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
``` 

Please help me!

**Comment by a-h** [comment]
I can't really help if I can't see your code. Do you have an example repo?

**Comment by gutrapp** [comment]
Gonna publish the repo give me one second

**Comment by gutrapp** [comment]
@a-h Here https://github.com/gutrapp/go-templ

**Comment by zsoltkacsandi** [comment]
@gutrapp You missed the “package view” in the first line of your templ file.

**Comment by gutrapp** [comment]
@zsoltkacsandi Yes that was the problem thank you
