### ISSUE TITLE
`go get` step not mentioned in quick start guide

### ISSUE THREAD

**Issue by heyajulia** [a-h/templ#329]
Hi!

When attempting to follow the quick start guide, I got the error message: `no required module provides package github.com/a-h/templ`.

To fix this, I had to run `go get github.com/a-h/templ` (which the error message suggests doing).

Is this an “implied” step? No one else has raised an issue about this, but I think it could be helpful to call it out explicitly. I’d be happy to submit a PR to update the guide with this information.

Thanks for your work on Templ!

**Comment by a-h** [comment]
Thanks for your kind words!

It is an implied step, and it would be better if it wasn't.

I would love a PR to improve the docs there if you have time, thanks!
