### ISSUE TITLE
Syntax highlight issue on neovim

### ISSUE THREAD

**Issue by Jos620** [a-h/templ#341]
<img width="288" alt="image" src="https://github.com/a-h/templ/assets/55610982/78719026-5b15-46b7-a60f-d617bb25feb3">

Everything goes white between the `/` and the `;`. The issue disappears when I remove either of them.

Environment:
NVIM: 9.4
Colorscheme: [vitesse](https://github.com/2nthony/vitesse.nvim)
Treesitter: commit - 30b5bdca1b534da71cdbc57fbbfe5693b4299e56

**Comment by joerdav** [comment]
This would be better raised on the treesitter plugin its self, as we don't maintain it currently.

**Comment by joerdav** [comment]
I can see this is now fixed with the latest tree sitter version.
