### ISSUE TITLE
Go Fiber Support / Example?

### ISSUE THREAD

**Issue by jacobranson** [a-h/templ#349]
Corresponding ticket on Go Fiber's side: https://github.com/gofiber/template/issues/302

Based on some of the conversation going on over there, it looks like there are a few different approaches to integrating both Templ and Fiber. Since there are already examples of Gin and Chi, maybe one could be added for Fiber?

**Comment by a-h** [comment]
I think that since the Fiber context type implements io.Writer, it should be a case of:

```go
app.Get("/", func(c *fiber.Ctx) error {
  return templConponent("hello").Render(c.Context(), c)
})
```

But I'm just typing this on a mobile, haven't had chance to try it!

**Comment by bastianwegge** [comment]
I created a helper that does this:

```go
func Render(c *fiber.Ctx, component templ.Component, options ...func(*templ.ComponentHandler)) error {
	componentHandler := templ.Handler(layout.Main(component))
	for _, o := range options {
		o(componentHandler)
	}
	return adaptor.HTTPHandler(componentHandler)(c)
}
```

This way you can use your render-function like this, which I found easiest:

```go
app.Get("/", func(c *fiber.Ctx) error {
  return view.Render(c, MyTemplView())
})
```

**Comment by a-h** [comment]
I think we can consider this closed. We've got a good example now, thanks to @bastianwegge.
