### ISSUE TITLE
cmd: templ version check failed: failed to parse go.mod

### ISSUE THREAD

**Issue by a-h** [a-h/templ#355]
In the case of a `go.mod` file that has a Go version of `x.x.x` instead of `x.x`, Go parsing fails with:

```
(!) templ version check failed: failed to parse go.mod file: /Users/adrian/github.com/a-h/fiber-example/go.mod:3: invalid go version '1.21.3': must match format 1.23
```

This error is printed due to https://github.com/golang/go/issues/61888

Might consider doing a find/replace on the go.mod (in memory) before parsing it to workaround temporarily.

**Comment by a-h** [comment]
Workaround applied in https://github.com/a-h/templ/commit/e98db353f87ebedea804cb3dc3200a826afb8904 - will wait for Go issue to be resolved, then remove the workaround, then I'll close this.

**Comment by egonelbre** [comment]
I'm currently getting the same error, however with `go1.22rc1:

```
(!) templ version check failed: failed to parse go.mod file: go.mod:3: invalid go version '1.22rc1': must match format 1.23
```

**Comment by a-h** [comment]
Ah, I see that bug is a gift that keeps on giving. 😁 

I've done a small update to it... https://github.com/a-h/templ/commit/19ad7c914bdc10383081c542775085cebb289492

**Comment by a-h** [comment]
Change released in https://github.com/a-h/templ/releases/tag/v0.2.543 - upgrade with `go install github.com/a-h/templ/cmd/templ@v0.2.543`

**Comment by dezren39** [comment]
hey i'm not sure if this is related, but i'm getting the following when running generate
```
(!) templ version check failed: failed to parse go.mod file: <local-path>\go.mod:5: unknown directive: toolchain
```

**Comment by a-h** [comment]
Can you post the `go.mod` that's causing the message to be displayed?

**Comment by a-h** [comment]
Fixed in https://github.com/a-h/templ/commit/e7d6ef30a35d97a2bc308cb8c5b640a0ae5f6256 - golang.org/x/mod was bumped to v0.17.0 last week.
