### ISSUE TITLE
Hot reload with templ proxy option panic

### ISSUE THREAD

**Issue by eussam** [a-h/templ#358]
Hello all,

I'm starting with `templ` and also kind of new to Go. I'm using `templ` with VSCode on a Mac M1.
I'm trying to setup the hot reload functionality using the `--proxy`option of the templ command , following the doc:

`templ generate --watch --proxy="http://localhost:8080" --cmd="go run cmd/server/main.go"`

The cmd `go run cmd/server/main.go` launches my web server listening to the `8080` port.
I hope this is the right way to do it (it was not totally obvious to me from reading the documentation). I understand that the previous cmd will be killed each time a `.templ` is updated and that the new cmd (my web server in this case) will be executed allowing to automatically see the changes in the browser, without manually refreshing the page thanks to the proxy (sse + location.reload).

Unfortunately, I could not manage to run it, I had the following crash:

```
michel@MBP-de-michel go-templ-vp-web % templ generate --watch --proxy="http://localhost:8080" --cmd="go run cmd/server/main.go"
Processing path: /Users/michel/Documents/dev/eussam/go/go-templ-vp-web
(✓) Generated code for "/Users/michel/Documents/dev/eussam/go/go-templ-vp-web/internal/components/layout.templ" in 3.283333ms
(✓) Generated code for 1 templates with 0 errors in 3.834708ms
Executing command: go run cmd/server/main.go
Proxying from http://127.0.0.1:7331 to target: http://localhost:8080
(!) templ version check failed: generator v0.2.503 is newer than templ version v0.2.477-0.20231218071748-d61470219c74 found in go.mod file, consider running `go get -u github.com/a-h/templ` to upgrade
Opening URL: http://localhost:8080
(!) templ version check failed: generator v0.2.503 is newer than templ version v0.2.477-0.20231218071748-d61470219c74 found in go.mod file, consider running `go get -u github.com/a-h/templ` to upgrade
2023/12/23 17:18:00 http: panic serving 127.0.0.1:58381: runtime error: invalid memory address or nil pointer dereference
goroutine 35 [running]:
net/http.(*conn).serve.func1()
        /Users/michel/.goenv/versions/1.20.12/src/net/http/server.go:1854 +0xb0
panic({0x1014af4e0, 0x1017c9e70})
        /Users/michel/.goenv/versions/1.20.12/src/runtime/panic.go:890 +0x258
github.com/a-h/templ/cmd/templ/generatecmd/proxy.(*roundTripper).RoundTrip(0x14000196000, 0x14000338100)
        /Users/michel/go/1.20.12/pkg/mod/github.com/a-h/templ@v0.2.502-0.20231223111456-00fd30eef1e6/cmd/templ/generatecmd/proxy/proxy.go:97 +0xb4
net/http/httputil.(*ReverseProxy).ServeHTTP(0x14000194000, {0x10153bd80?, 0x14000324000}, 0x1400022c500)
        /Users/michel/.goenv/versions/1.20.12/src/net/http/httputil/reverseproxy.go:473 +0xc6c
github.com/a-h/templ/cmd/templ/generatecmd/proxy.(*Handler).ServeHTTP(0x14000198030, {0x10153bd80?, 0x14000324000}, 0x1400022c500)
        /Users/michel/go/1.20.12/pkg/mod/github.com/a-h/templ@v0.2.502-0.20231223111456-00fd30eef1e6/cmd/templ/generatecmd/proxy/proxy.go:78 +0xac
net/http.serverHandler.ServeHTTP({0x14000235260?}, {0x10153bd80, 0x14000324000}, 0x1400022c500)
        /Users/michel/.goenv/versions/1.20.12/src/net/http/server.go:2936 +0x2d8
net/http.(*conn).serve(0x1400021c120, {0x10153c128, 0x14000198270})
        /Users/michel/.goenv/versions/1.20.12/src/net/http/server.go:1995 +0x560
created by net/http.(*Server).Serve
        /Users/michel/.goenv/versions/1.20.12/src/net/http/server.go:3089 +0x520
Server not ready. Retrying in 513.917235ms...
```

I guess I'm doing something wrong as it would already have been reported here.

I tried to dig a bit, it seems like the problem occurs in the `RoundTrip` method of the proxy, with the `GetBody()` method not being available:

```go
req.Body, err = r.GetBody()
```

Being my limited Go knowledge, I asked ChatGPT for some help, I understand it would be something to do with the body of the request not being able of being re-read when retrying a request.

I tried a suggested modified version of RoundTrip storing the body in a buffer to be able to manage the request retrying:

```go
func (rt *roundTripper) RoundTrip(r *http.Request) (*http.Response, error) {
	// Read and buffer the body
	var bodyBytes []byte
	if r.Body != nil && r.Body != http.NoBody {
		var err error
		bodyBytes, err = io.ReadAll(r.Body)
		if err != nil {
			return nil, err
		}
		r.Body.Close()
	}

	// Function to create a new request with a buffered body
	createRequestWithBuffer := func() *http.Request {
		req := r.Clone(r.Context())
		if bodyBytes != nil {
			req.Body = io.NopCloser(bytes.NewReader(bodyBytes))
		}
		return req
	}

	// Retry logic
	var resp *http.Response
	var err error
	for retries := 0; retries < rt.maxRetries; retries++ {
		req := createRequestWithBuffer()

		resp, err = http.DefaultTransport.RoundTrip(req)
		if err != nil {
			time.Sleep(rt.initialDelay * time.Duration(math.Pow(rt.backoffExponent, float64(retries))))
			continue
		}

		return resp, nil
	}

	return nil, fmt.Errorf("max retries reached")
}
```
 
By doing so I could make it work, the hot reload using the proxy behaves as expected and my web app is automatically refreshed/reloaded in the browser.

Can anybody tell me what I'm doing wrong ?

I'm looking forward to having everything ready on my computer to start playing with the lib, thank you @a-h for this project :)

**Comment by a-h** [comment]
Thanks! I've not seen the issue myself, maybe because my manual testing wasn't based on making POST requests, so I didn't see the issue with making multiple reads of the body.

The code in your example looks good to me. I'd take a PR, or I can your code from the comment above and merge it from there.

**Comment by eussam** [comment]
If you're not in a rush, I can make a PR as a training practice to contribute, I'm not used to participate to open source projects, whatever suits you best :)

**Comment by a-h** [comment]
You did the work, so I think you should be in the contributor list. I'll wait for the PR. 😀
