### ISSUE TITLE
Do some math in template possible?

### ISSUE THREAD

**Issue by ingothierack** [a-h/templ#364]
Hi, new to templ and play currently with it.
What I try is to generate an report from an database query.

```
templ Show(report []model.Sel_div_rep){
    for _, line := range report {
      { line.AccoundId } {line.PayDate.String()} {line.GrossAmount.String()} <br/>
    }
  }

```

Works so far.
Now the question. Is it possible, to sum a value while loop over the records so I can print after the loop the sum of the line.GrossAmount value. 

Something like
```
templ Show(report []model.Sel_div_rep){
    var sum float
    for _, line := range report {
       sum = sum+line.GrossAmount
      { line.AccoundId } {line.PayDate.String()} {line.GrossAmount.String()} <br/>
    }
    Summary Gross Amount:  { sum }
  }
```

What I have tested, is to call a function inside the Show template. But then I have to loop over the records again to sum the values up. That is something what I try to avoid.

**Comment by urmet** [comment]
you could use a separate function to format the output and keep track of the sum at the same time like this:
```go
var sum float32

func printAccount(account Sel_div_rep) string {
    result := fmt.Sprintf("%s %s %.2f", account.AccoundId, account.PayDate.String(), account.GrossAmount)
    sum += account.GrossAmount
    return result
}

templ Show(report []Sel_div_rep){
    for _, line := range report {
      { printAccount(line) } <br/>
    }
    Summary Gross Amount:  { fmt.Sprintf("%.2f", sum) }
}
```

**Comment by a-h** [comment]
I'd normally recommend a view model approach as per https://templ.guide/core-concepts/view-models to keep the template logic as small as possible.

There is a plan to add arbitrary code blocks into templ, but I haven't made any progress on it yet.

**Comment by a-h** [comment]
@urmet, nice idea, but I'm not sure it's a good idea to recommend summing into a global variable, since it will be shared by all concurrent HTTP requests.

**Comment by ingothierack** [comment]
If the approach is to use templ only for output and do any work on the data before provide it to the template I'm fine with this. 
So I have only the formatting stuff inside the template and hand down the data all precalculated.

Have somewhere a function to create/fill something like
```
type Report struct {
   Lines []Sel_div_rep
   Sum float32
} 
```

and put this to the template.
```
temp Show(report Report){
       for _, line := range report.Lines {
         { line.AccoundId } <br/>
    }
    Summary Gross Amount:  { fmt.Sprintf("%.2f", report.Sum) }

}

**Comment by a-h** [comment]
Yes, that's what I think works best!

It's nothing to with templ or Go specific, but I noticed you were using floats for money. You might want to switch to something like `int64` (that's what payments provider Stripe uses), or https://github.com/Rhymond/go-money to ensure that floating point math doesn't affect accuracy of the totals or individual amounts.

**Comment by ingothierack** [comment]
@a-h Changed the workflow, so only formatting for output is done, and works like a charm.

some fragments from the template
```
<td class="right">{ fmt.Sprintf("%.5f",line.GrossRate.Round(5, decimal128.ToNearestEven)) } </td>
<td class="right">{ fmt.Sprintf("%.3f", line.FxRateToBase.MulWithMode(line.GrossRate, decimal128.ToNearestEven).Round(3, decimal128.ToNearestEven)) } </td>
...
<td class="right">{ fmt.Sprintf("%.5f", report.SummaryGrossAmount.Round(5, decimal128.ToNearestEven)) } </td>
```
maybe I put even more formatting to the database query function, but then I have to handle two models, one for the response from the db query, the other for display. 

I used float only here as example. For the real work I use currently https://github.com/woodsbury/decimal128 this should do the trick.  I use here only an generic decimal type, as I have to deal with different data feed, which have up to 9 digits after the decimal point. 

This all is for a personal fun project, where I try to learn something and replace excel to get easy for my tax report :)

**Comment by a-h** [comment]
Great stuff! Looks like this issue can be closed then, unless you think something is missing from the docs?
