### ISSUE TITLE
Version check failed to parse go.mod file

### ISSUE THREAD

**Issue by penmanglewood** [a-h/templ#378]
Current environment:

OS: macOS Sonoma 14.2.1
Go:  go version go1.21.5 darwin/arm64

Steps to reproduce:

1. [Install templ](https://templ.guide/quick-start/installation#go-install): `go install github.com/a-h/templ/cmd/templ@latest`.
2. Assuming there's a templ file in the current directory or below, run `templ generate`.

Expected behavior:

Complete code generation without error.

Actual behavior:

```
$ templ generate
Processing path: /path/to/project
(✓) Generated code for "/path/to/project/internal/component/page.templ" in 2.358042ms
(✓) Generated code for 1 templates with 0 errors in 3.058541ms
(!) templ version check failed: failed to parse go.mod file: /path/to/project/go.mod:3: invalid go version '1.21.5': must match format 1.23
```

For reference, contents of go.mod

```
module github.com/user/project

go 1.21.5

require (
	github.com/julienschmidt/httprouter v1.3.0
	github.com/justinas/alice v1.2.0
	github.com/rs/zerolog v1.31.0
)

require (
	github.com/mattn/go-colorable v0.1.13 // indirect
	github.com/mattn/go-isatty v0.0.19 // indirect
	github.com/rs/xid v1.5.0 // indirect
	golang.org/x/sys v0.12.0 // indirect
)
```

**Comment by Cyna298** [comment]
I have same the environment and I am also getting the same behaviour. 
However, as given by the log, even though the version check failed, the code seems to have been generated perfectly. 
A `/path/to/project/internal/component/page_templ.go` file should have been generated.

Upon inspecting the file, the LSP was unable to resolve `import "github.com/a-h/templ"` but 
```
go get github.com/a-h/templ
```
fixed it. So far it is working fine. I will update if I run into any issues

**Comment by a-h** [comment]
Sorry about this, it's a spurious error that's due to a problem in the Go module parsing library. You can ignore it, it doesn't affect the output. See https://github.com/a-h/templ/issues/355 which links through to https://github.com/golang/go/issues/61888
