### ISSUE TITLE
Templ-vscode missing executable path

### ISSUE THREAD

**Issue by vunhatchuong** [a-h/templ#393]
templ-vscode currently miss an executable path and there is no way to add a custom path

This is the default path when I install `Go` with `pacman -S go`
```bash
Operating System: EndeavourOS
          Kernel: Linux 6.1.70-1-lts
    Architecture: x86-64
```
```bash
error initializing templ LSP: Could not find templ executable in path or in templ, templ.exe, bin/templ, bin/templ.exe, bin/templ, 
bin/templ.exe, /home/ronny/bin/templ, /home/ronny/bin/templ.exe, /usr/local/bin/templ, /usr/bin/templ, /usr/local/go/bin
/templ, /usr/local/share/go/bin/templ, /usr/share/go/bin/templ
```

```bash
❯ which templ
/home/ronny/go/bin/templ
```

**Comment by joerdav** [comment]
https://github.com/templ-go/templ-vscode/blob/main/src/main.ts#L47-L60

It seems that your vscode doesn't have GOBIN set when running, the plugin will either need you to have templ available in your path, or for the GOBIN environment variable set.

**Comment by a-h** [comment]
I think it makes sense to add `~/go/bin` to that list of places to check though, since if you don't have a GOBIN env set, the default is ~/go, as per (I think) https://github.com/golang/go/issues/17262

**Comment by a-h** [comment]
I've added this in https://github.com/templ-go/templ-vscode/commit/34543ff8688cac6bcb9905a5645ee61fa9414e95 and released version 0.0.18 of the templ VS code extension that includes it.

https://github.com/templ-go/templ-vscode/actions/runs/7412517884

**Comment by a-h** [comment]
I'm going to close this, please reopen it if this hasn't solved the issue for you!

**Comment by orblazer** [comment]
Hello,
The possibility to add custom path should be great, especially when we use version manager like [asdf](https://asdf-vm.com/) due path is something like `~/.asdf/shims/templ`.

Thanks.
