### ISSUE TITLE
generator: allow arbitrary go code in templates

### ISSUE THREAD

**Issue by danawoodman** [a-h/templ#399]
It would be awesome if you could define a temporary variable somehow (this is just one possible suggestion) in cases where you might be duplicating lots of code to reuse something, like this:

```go
package views

templ ItemDetail(item Item) {
	t := item.CreatedAt.Local()
	<section>
		<h1>{ item.Name }</h1>
		<time datetime={ t.Format(time.RFC3339) }>{ t.Format("Jan 2, 2006") }</time>
	</section>
}
```

Unless I'm mistaken, this doesn't appear to be supported - so if I'm correct - I'd love to see this implemented some day!

**Comment by dougbarrett** [comment]
As a possible alternative, you may want to consider doing:

```go
package views

func ltf(i Item, f string) time.Time {
    return i.CreatedAt.Local().Format(f)
}

templ ItemDetail(i Item) {
	<section>
		<h1>{ i.Name }</h1>
		<time datetime={ ltf(i, time.RFC3339)) }>{ ltf(i, "Jan 2, 2006") }</time>
	</section>
}
```

i'm finding that I'm often making a `tools.templ` file that I can easily throw small helpers into like this - it helps to keep the actual templates as lean as possible

**Comment by danawoodman** [comment]
def works for some scenarios!

still think some intermediary variable creation would be a valuable addition 😇

**Comment by a-h** [comment]
There's a plan to add the ability to introduce arbitrary code. The discussion around it is in https://github.com/a-h/templ/issues/109#issuecomment-1772316439 

The design will looks like this:

```templ
{{ x := "variable" }}
```

It's not much work to add it. There's already an expression parser that looks to match start and end braces, and is aware of start and ends of strings, comments etc.

Adding lots of code into templates isn't something I'd recommend. I prefer more of a View Model type approach, where you can keep the logic for creating the view separate from the rendering part (as per https://templ.guide/core-concepts/view-models), but there are places where defining a variable or adding some extra code can be useful.

Having a set of helpers like @dougbarrett suggests is a good idea. Might need to mention some of the common string format operations that there are in Go in the documentation, e.g. `fmt.Sprintf()`, `time.Now().Format()`etc.

**Comment by joerdav** [comment]
Just spotted an older ticket which this will be tracked in. https://github.com/a-h/templ/issues/109
