### ISSUE TITLE
[templ-vscode] gets confused with switch statement

### ISSUE THREAD

**Issue by DavidS-ovm** [a-h/templ#406]
While others that look similar work, this statement confuses the vscode plugin/language server:
```
templ riverStateTd(status models.RiverJobState) {
	switch status {
		case models.RiverJobStateAvailable:
			<td class="flex justify-center bg-yellow-50">
				<div>⏸️</div>
			</td>
		case models.RiverJobStateCancelled, models.RiverJobStateDiscarded:
			<td class="flex justify-center bg-red-50">
				<div>✖️</div>
			</td>
		case models.RiverJobStateCompleted:
			<td class="flex justify-center bg-green-50">
				<div>✔️</div>
			</td>
		case models.RiverJobStateRetryable:
			<td class="flex justify-center bg-blue-50">
				<div>⏸️</div>
			</td>
		case models.RiverJobStateRunning:
			<td class="flex justify-center bg-blue-50">
				<div>⏩</div>
			</td>
		case models.RiverJobStateScheduled:
			<td class="flex justify-center bg-blue-50">
				<div>⏱️</div>
			</td>
		default:
			<td class="flex justify-center bg-red-50">
				<div>unknown</div>
			</td>
	}
}
```

broken:
![2024-01-08_16MS+0100_875x800](https://github.com/a-h/templ/assets/118179693/3da91a87-9ecf-47a8-bcc9-0a9b15ed8ec3)

"working":
![2024-01-08_16MS+0100_1012x806](https://github.com/a-h/templ/assets/118179693/49d272be-9816-4a14-8fc3-fa733dd80f91)

**Comment by joerdav** [comment]
From a quick investigation I think this could be a _case_ (pardon the pun) of just updating the switch end regex to be the same as what is defined in the for expression. I don't see why these should be different.

For ender: https://github.com/templ-go/templ-vscode/blob/main/syntaxes/templ.tmLanguage.json#L307
Switch ender: https://github.com/templ-go/templ-vscode/blob/main/syntaxes/templ.tmLanguage.json#L327

**Comment by joerdav** [comment]
This is now fixed in https://github.com/templ-go/templ-vscode/releases/tag/v0.0.19
