### ISSUE TITLE
{! foo }` syntax is deprecated. Use `@foo` syntax instead

### ISSUE THREAD

**Issue by benjiro29** [a-h/templ#411]
Please undo this change or this warning ... 

The basic {} and {! } syntax flow and are visually easy.  While the @ syntax makes it harder to differentiate words. Maybe its a dyslexia issue but this syntax is just harder to read and is a step back.

Example:

@Option()
{! Option() }

@Component 
{! Component )

Or remove the warning about it being deprecated and leave it for the folks that want to use the old syntax.

**Comment by benjiro29** [comment]
This check is also bugged...

templ something(action string) {
	{! Component }
}

Will give a warning on {! Component }

templ something(action string) {
	if 1 == 1 {
            {! Component }
        }
}

Zero warning because there is no check done ...

**Comment by joerdav** [comment]
I have raised a new issue for the diagnostic not working in if statements:
https://github.com/a-h/templ/issues/478

Closing this as the new syntax is a foundation for features that have already been developed.
