### ISSUE TITLE
cmd: templ version check failed

### ISSUE THREAD

**Issue by benjiro29** [a-h/templ#412]
Run templ generate -watch

....
(✓) Generated code for 18 templates with 0 errors in 33.453991ms
(!) templ version check failed: could not find go.mod file
(!) templ version check failed: could not find go.mod file
(!) templ version check failed: could not find go.mod file
(!) templ version check failed: could not find go.mod file
..... 

See this constant spam of "templ version check failed"... repeat hundred of times (~one per second)

Updated all go.mod files to v0.2.513, no difference ... Older v0.2.476 version worked perfectly

File structure as following:

Server
+go.mod
-- Module
-- +x.templ
---- Submodule
---- +x.templ

No need to have go.mod into every directory but for some reason templ is expecting it?

**Comment by benjiro29** [comment]
Update on the issue:

The issue is that templ only looks at the absolute root of project for a go.mod, but if you use workspace layouts or simply use segregated module:

go.work
/Something
/Something/go.mod
/Something/main.go
/Something/main_templ
/Another
/Another/go.mod
/ ...

This breaks templ as its only checks the root for a go.mod file.

Solution: Add a fake go.mod file, just to please templ but it makes the whole version check routine useless, as the actual go.mods with templ versions are in the sub directories (that never get checked).

**Comment by a-h** [comment]
I think the output spam is fixed in https://github.com/a-h/templ/commit/bb756d7fb3018846d3265f01ec49f6799dab8e48

**Comment by a-h** [comment]
The `generate --watch` and process has also just been refactored and new tests added in https://github.com/a-h/templ/pull/441

I think this solves the issue @benjiro29, if you're able to try out the main branch that would be great.

**Comment by joerdav** [comment]
Should we close this with the above fixes and re-open if it pops back up again?

**Comment by a-h** [comment]
Fix released in https://github.com/a-h/templ/releases/tag/v0.2.543 - upgrade with `go install github.com/a-h/templ/cmd/templ@v0.2.543`
