### ISSUE TITLE
lsp: Auto import and import formatting on save

### ISSUE THREAD

**Issue by norbusonam** [a-h/templ#413]
I have been using templ for a new project and one of the biggest pain points for me is the lack of auto imports and import formatting (like the ones existing in go's built-in formatter). I keep having to manually look up package names/paths in order to fix `undefined` errors. Would be great for DX if this could be integrated!

I'm open to helping implement but I have v little experience in developer tools like this.

**Comment by alehechka** [comment]
Not quite auto-imports on save, but the LSP includes intellisense for imports that can be used to add import statements for new packages to the file. If you're using VSCode, the default would be `Ctrl + Space` after a package name to pull up the intellisense tooltip which should include a list of matching packages that you can arrow through to select the desired one.

**Comment by joerdav** [comment]
Apologies I duplicated this issue and tracked my progress there https://github.com/a-h/templ/issues/757
