### ISSUE TITLE
generator: Implement the go line compiler directive in generated files

### ISSUE THREAD

**Issue by joerdav** [a-h/templ#415]
There is a Go compiler directive [`//line`](https://pkg.go.dev/cmd/compile#hdr-Compiler_Directives), which can be used to reference other files. Historically `gopls` would support this directive, but subsequently dropped support https://github.com/golang/go/issues/55043 

There is an issue in `gopls` to propose reintroducing this https://github.com/golang/go/issues/65001 

It could be valuable for templ to implement this directive for the future, so that if this directive is implemented in `gopls` it'll work with generated templ files.

# Solution

In `*_templ.go` files, all symbols that could be referenced by `.go` files should be defined with the `//line` directive, for example:

Generated file
```go
//line index.templ:20
func Index() templ.Component {
...
```

This should apply to code generated by all keywords `templ`, `css` and `script`.

**Comment by joerdav** [comment]
For now I think we should close this, the implementation did work but the go line directive also affected other parts of the application in unexpected ways.

**Comment by noor-tg** [comment]
so what is the alternative to handle this with go lsp or can I start templ lsp inside go files and it work too ?
