### ISSUE TITLE
Unicode, UTF-8 and Html Charset Not Working in String Variable 

### ISSUE THREAD

**Issue by rizal111** [a-h/templ#416]
String Variable : 
![image](https://github.com/a-h/templ/assets/61342066/2cc41824-b0dd-4766-9536-42b90e7b5af4)

Browser View : 
![image](https://github.com/a-h/templ/assets/61342066/92a655b0-f50a-460f-bb83-ffc561a651c0)

Response Html :
![image](https://github.com/a-h/templ/assets/61342066/70db72d5-3b85-410a-83d3-9a048f705ded)

using @templ.Raw for mean time

**Comment by a-h** [comment]
Thanks for bringing this up, it will be default in the next release.
