### ISSUE TITLE
can i use charts in templ (e.g. go-echarts)

### ISSUE THREAD

**Issue by johanwinter1** [a-h/templ#424]
can i use charts in templ (e.g. go-echarts)?

if yes can you show me how?

thx

**Comment by a-h** [comment]
Yes, yes you can.

![image](https://github.com/a-h/templ/assets/1029947/ef5b3759-8a74-4850-a3a5-6064d4f14316)

And here's an example of how to do it.

https://github.com/a-h/templ/tree/main/examples/integration-go-echarts

**Comment by johanwinter1** [comment]
thank you very much i have working
