### ISSUE TITLE
parser: `for: expected nodes, but none were found`

### ISSUE THREAD

**Issue by sirkostya009** [a-h/templ#425]
I keep getting an error when running `templ generate` for this specific snippet. It points to line 80, col 16, which is 4 spaces before beginning of the `<span>` element. Am I tripping or is this a bug?

```
<div hx-boost="true" hx-swap="transition:true" hx-target="main">
    <h2>Colors</h2>
    for _, c := range shoe.Colors {
        <a href={templ.URL("/product/"+shoe.Id+"?color="+c.Color+"&size="+strconv.FormatFloat(so.Size, 'f', -1, 64))}>
            <span class="color" style={"background-color:" + c.Color}>{s.Color}</span>
        </a>
    }
</div>
```

**Comment by sirkostya009** [comment]
Removing `style={"background-color:" + c.Color}` made the file compile. But it still leaves me curious as to why was it not possible to make `templ` compute the style attribute.

**Comment by javirst** [comment]
my workaround would look like this in your code
```@templ.Raw(fmt.Sprintf(`<span class="color" style="background-color:%s">%s</span>`,s.Color,s.Color))```

**Comment by joerdav** [comment]
Duplicates #88
