### ISSUE TITLE
Spread attributes

### ISSUE THREAD

**Issue by LyubenGeorgiev** [a-h/templ#430]
In the docs there is https://templ.guide/syntax-and-usage/attributes#spread-attributes
But if I try to use even the example snipet it can't be compiled. Is the feature depracated or is the docs not updated?

**Comment by alehechka** [comment]
This is a newer feature added by https://github.com/a-h/templ/pull/237 which is included in release [v0.2.501](https://github.com/a-h/templ/releases/tag/v0.2.501). Make sure your locally installed templ version and Go modules version of templ are at least v0.2.501.

**Comment by joerdav** [comment]
@LyubenGeorgiev what's the result of running `templ version`?

**Comment by LyubenGeorgiev** [comment]
It was a version issue. I upgraded to the latest templ but for some reason my VSCode extension did not recognize the newer syntax after restarting. Now it seems to work fine.
