### ISSUE TITLE
Switch Statement Highlighting Broken in VSCode Extension

### ISSUE THREAD

**Issue by alehechka** [a-h/templ#437]
# Overview
I noticed that the switch statement highlighting is broken in the VSCode extension. The closing curly brace appears as invalid and all code below the switch no longer receives highlighting. I opened a pull request for this at: https://github.com/templ-go/templ-vscode/pull/25. 

Mainly just opening this issue to get visibility on the PR since that repo doesn't get a lot of traffic.

![Screenshot 2024-01-18 at 2 14 42 PM](https://github.com/a-h/templ/assets/42357034/d141a4d4-bc57-4215-82d3-ab0bd286f96a)

**Comment by joerdav** [comment]
There's actually an issue on this raised already https://github.com/a-h/templ/issues/406

I'll take a look at the PR thanks!

**Comment by joerdav** [comment]
Fixed in https://github.com/templ-go/templ-vscode/pull/25
