### ISSUE TITLE
--proxy is not injecting javascript and there is no reload if no body tag is present

### ISSUE THREAD

**Issue by phenpessoa** [a-h/templ#448]
I have found that the proxy feature does not work if there is no body tag in the html.

main.go

```go
package main

import (
	"fmt"
	"net/http"

	"github.com/a-h/templ"
)

func main() {
	component := hello("World")

	http.Handle("/", templ.Handler(component))

	fmt.Println("Listening on :8080")
	http.ListenAndServe(":8080", nil)
}
```

hello.templ
```templ
package main

templ hello(name string) {
	<div>Hello, { name }</div>
}
```

command
```shell
templ generate --watch --proxy="http://localhost:8080" --cmd="go run ."
```

When I run this, the code builds, and making changes to the templ file make the code recompile (changing the main.go file doesn't though).
It opens the browser (pointing to localhost:7331), but this is what the html looks like:

```html
<div>Hello, World</div>
```

As you can see, no javascript was injected in order to have live reloading. So when I make a change to the templ file, even though the code recompiles, the browser doesn´t automatically update.

If I add a body tag to the component, then it works as expected. It took me a while to realize that.
Maybe adding it to the docs could be helpful. 
This is what the doc says

```
The proxy inserts client-side JavaScript before the </body> tag that will cause the browser to reload the window when the app is restarted instead of you having to reload the page manually.
```

My suggestion would be to add a note after that saying, something like

```
If there is no body tag, the proxy flag will not work.
```

Perhaps we could also have a code example there.

**Comment by a-h** [comment]
Thanks, good spot!

If you feel like doing a PR, for it, go ahead. The docs are just markdown files in ./docs/docs 

If you've not got time, drop a comment, and I'll tag the issue with help wanted.

**Comment by phenpessoa** [comment]
@a-h I’ll open a PR. Thank you.
