### ISSUE TITLE
scripts: Reference script templates from other script templates

### ISSUE THREAD

**Issue by RaniAgus** [a-h/templ#449]
It would be great if we were able to write this:

```templ
script mul(a int, b int) {
  return a * b;
}

script double(num int) {
  return @mul(num, 2);
}
```

And map the function call to the correct script template like this:
```html
<script type="text/javascript">function __templ_mul_5a85(a, b){return a * b;}</script>
<script type="text/javascript">function __templ_double_5a85(num){return __templ_mul_5a85(num, 2);}</script>
```

So we could reuse logic from both client and server sides.

**Comment by joerdav** [comment]
As script templates are no longer recommended I think we can close this: https://templ.guide/syntax-and-usage/script-templates#script-templates
