### ISSUE TITLE
lsp: no root directory despite go.mod being present

### ISSUE THREAD

**Issue by JulianH99** [a-h/templ#452]
On neovim, the lsp is starded but does not seem to work, and upon executing :LspInfo, this is the result I get
![image](https://github.com/a-h/templ/assets/16496346/08fc18ff-86bb-4edd-ae1a-682914a13459)

And this is my file structure
![image](https://github.com/a-h/templ/assets/16496346/a7b7297c-55a9-4872-8668-d660f0b3bc50)

I already tried the code on the [logging ](https://templ.guide/commands-and-tools/ide-support/#enable-lsp-logging)section as well to see if using `root_patern` would help, but it didn't

**Comment by a-h** [comment]
From the information provided, I can't tell what file type is being detected.

This is what I see on screen.

![Screenshot from 2024-01-23 12-23-41](https://github.com/a-h/templ/assets/1029947/7d397d8f-a650-4ef0-be44-6e5dbf538ab6)

**Comment by a-h** [comment]
Is the filetype being correctly detected as templ? If not, that's the problem.

You need to show the whole screenshot.

**Comment by JulianH99** [comment]
Hi @a-h sorry for the missing part of the sc, here it is 
![image](https://github.com/a-h/templ/assets/16496346/f40bb1af-dbd0-4e91-8187-29122cbc892d)
And as you can see, it is being detected as templ

**Comment by a-h** [comment]
My understanding is that Neovim will only start the LSP is the root directory configuration matches. In the case of templ, having a `go.mod` file (which I can see from your project that you do).

Here's the exact part of my Neovim configuration that configures the root directory.

https://github.com/a-h/dotfiles/blob/7f9d98a2ee263bacd6728ae4d519ada5f71e4119/.config/nvim/lua/lsp.lua#L59-L67

I'm not sure where your config is going wrong. Maybe you could share a repo with the complete config in it?

**Comment by JulianH99** [comment]
Only thing is I removed the root config after it didn't work, but sure, here's my config https://github.com/JulianH99/nvim/tree/lsp (already on the lsp branch which is the one I'm using)

**Comment by a-h** [comment]
@JulianH99 - a recent PR just landed which contains a known working Neovim configuration with Lazyvim: https://github.com/a-h/templ/pull/463

I can see that there's a number of extra settings related to cmp_nvim_lsp in the example config that you don't have in yours. Maybe you could try using that config as a base and building out from there?

**Comment by JulianH99** [comment]
@a-h I tried that config and yours too, but nothing seems to be working. I use mason, I added a custom handler for the templ lsp, I put the default config before mason setup, inside the handler, after the setup, and nothing worked

**Comment by joerdav** [comment]
@JulianH99 templ is now bundled in lspconfig, so you don't need to add a custom handler in your config, the following can be removed:

```
        ["templ"] = function()
          lsp.templ.setup({
            on_attach = on_attach,
            capabilities = capabilities,
            filetypes = { "templ" },
          })
        end,
```

Please let me know it that helps.

**Comment by JulianH99** [comment]
Hi @joerdav thanks, it eventually worked, but I don't really remember what did I moved. but thanks, this will make it easier of course
