### ISSUE TITLE
Dynamic Attribute Values

### ISSUE THREAD

**Issue by mattbrandman** [a-h/templ#453]
I am trying to make a part of my attribute dynamic based on an input variable.

Something along the lines of the following

```
templ FormField(title, name, value, err string) {
     <p class="mt-2 text-sm text-red-600" id={title}"-myid">{ err }</p>
}
```

Where the ideal outcome if the title is Bob is 

```
     <p class="mt-2 text-sm text-red-600" id="Bob-myid">{ err }</p>
```

I have not been able to get the generator to accept any type of dynamic mix of strings and variables here. I have found a way around by defining a function that takes in the title and returns the fully formed string but I wanted to see if that is the recommended best practice.

**Comment by a-h** [comment]
Hi Matt, what you're describing is best practice. Templ ensures that all attribute content is properly escaped. If it was possible to interpolate strings within attribute values, it would hard to know what type of escaping to apply.

It's the same behaviour in JSX - https://playcode.io/1734926

In templ, I might do something like this if defining a function is hard work.

```
templ FormField(title, name, value, err string) {
     <p class="mt-2 text-sm text-red-600" id={ fmt.Sprintf("%s-myid", title) }>{ err }</p>
}
```

**Comment by alehechka** [comment]
Also valid would be normal string concatenation:

```
templ FormField(title, name, value, err string) {
     <p class="mt-2 text-sm text-red-600" id={ title + "-myid" }>{ err }</p>
}
```

**Comment by mattbrandman** [comment]
Thanks @a-h thats really helpful to know and for the other examples! This library was exactly what I was missing from my stack. Type safety and composability have been awesome just needed a way to easily abstract some thicker tailwindUI form input components. Will close!
