### ISSUE TITLE
docs: Gin example cannot use context.

### ISSUE THREAD

**Issue by SebastianStehle** [a-h/templ#456]
If I understand it properly the gin example does not use the context, because there is no solution to pass the context from gin to the renderer.

I think there would be an alternative solution by using the `Render()` method of the gin context.

**Comment by a-h** [comment]
Thanks, you're right!

I'd happily take a PR for an example update if you feel like it.

**Comment by iamajoe** [comment]
https://github.com/a-h/templ/pull/466
You mean like this? Or are you thinking on something different?

**Comment by a-h** [comment]
Closed in https://github.com/a-h/templ/commit/b6e7a779dacbddc4a185023be181fe7349e6b923

Thanks for your contributions!
