### ISSUE TITLE
parser: comments in script break execution

### ISSUE THREAD

**Issue by romanzy313** [a-h/templ#457]
Im using the latest version of templ `v0.2.513`

While trying out this library I found an issue with JavaScript functionality.

The following works:

```go
script hello() {
    console.log("hello")
}
```
This also works
```go
script hello() {
    // comment
    console.log("hello")
}
```

Yet when I add a comment in the end, it breaks.

```go
script hello() {
    console.log("hello 2")
    // comment
}
```

Here is the error browser gives me:

```
Uncaught SyntaxError: missing } after function body[:2:16](http://localhost:3000/)note: { opened at line 1, column 1282
```

This is html emitted by templ:
```html
<script type="text/javascript">function __templ_hello_3db9(){console.log("hello 2")
    // comment}</script>
```

**Comment by a-h** [comment]
I think this was fixed in #384.

This unit test looks like it would trigger the same issue if it wasn't: https://github.com/a-h/templ/pull/384/files#diff-a2c7d658d99422e95b3f52d1935a65ac3049077aebb3d61fdee3aee214324981

**Comment by joerdav** [comment]
I reckon cut a release, I think there's people waiting on the formatting fix that was made too.

**Comment by a-h** [comment]
Fix released in https://github.com/a-h/templ/releases/tag/v0.2.543
