### ISSUE TITLE
Concurrent Map Write on templ watch command

### ISSUE THREAD

**Issue by grindlemire** [a-h/templ#474]
I am running into a panic due to concurrent map writes when running `templ generate --watch`. I haven't been able to consistently reproduce this because it is a race condition. Looking through the code I believe it stems from the fact we are adding entries to the `hashes` map ([link](https://github.com/a-h/templ/blob/main/cmd/templ/generatecmd/main.go#L414)) when it is unprotected and being used by multiple go routines that are launched from the file directory walk function ([link](https://github.com/a-h/templ/blob/main/cmd/templ/generatecmd/main.go#L311)).

Here is a stack trace showing this:
```
fatal error: concurrent map writes

goroutine 9 [running]:
github.com/a-h/templ/cmd/templ/generatecmd.generate({0x9d6f00, 0xc000024460}, {0xc00002a380, 0x3e}, {0xc000038930, 0x63}, 0xc00017b890, 0x0, {0xc00003f070, 0x2, ...})
        /home/grindlemire/go/pkg/mod/github.com/a-h/templ@v0.2.543/cmd/templ/generatecmd/main.go:414 +0x665
github.com/a-h/templ/cmd/templ/generatecmd.processSingleFile({0x9d6f00, 0xc000024460}, {0x9d1200, 0xc000066030}, {0xc00002a380, 0x3e}, {0xc000038930, 0x63}, 0x0?, 0x0, ...)
        /home/grindlemire/go/pkg/mod/github.com/a-h/templ@v0.2.543/cmd/templ/generatecmd/main.go:349 +0x106
github.com/a-h/templ/cmd/templ/generatecmd.processChanges.func1.1()
        /home/grindlemire/go/pkg/mod/github.com/a-h/templ@v0.2.543/cmd/templ/generatecmd/main.go:311 +0xf4
created by github.com/a-h/templ/cmd/templ/generatecmd.processChanges.func1 in goroutine 1
        /home/grindlemire/go/pkg/mod/github.com/a-h/templ@v0.2.543/cmd/templ/generatecmd/main.go:309 +0x77e
```

I have put up a PR converting the hashes map to a `sync.Map` to address this (#473).

I have not been able to consistently reproduce this behavior in a unit test since I suspect it requires many templ files. Perhaps you know of a way to do it?

**Comment by a-h** [comment]
Thanks for looking into this issue, and agree with the solution.

However... I have just completely rewritten that part of the code which is under review at https://github.com/a-h/templ/pull/470/files and also noticed the concurrent map issue, which I resolved in https://github.com/a-h/templ/pull/470/commits/c4f40435299efb7f84fab564a53227d26a8fd284

Since you now understand how that part of the system works, if you'd like to review PR #470, that would be great. I think it should be a little easier to understand given the rewrite.

**Comment by grindlemire** [comment]
Ok sounds good. I'll close this issue. Do you have a timeline for when #470 will be merged?

**Comment by a-h** [comment]
Next couple of days. All the tests are passing, but thought it was worth asking people to review it, and giving them a couple of days to spot any structural problems.

It's good to try out if you want to pull the branch and build it locally.
