### ISSUE TITLE
scripts: we cant use go expression in function

### ISSUE THREAD

**Issue by rgunindi** [a-h/templ#483]
```
//Simple example
templ Show(msg types.Message) {
<script>
 function showAcceptedUsers() {
console.log(msg.Success)
//or
console.log({msg.Success})
}
}

-- 1.Output: **ReferenceError: msg is not defined**
-- 2.Output: **SyntaxError: Unexpected token '.'**
```

Why is go code not allowed in javascript functions or is there a way to work around this problem? It seems to me that because the js function starts with {, it is not allowed to use any go code in it.

I haven't seen any usage in js functions in the documentation either.

The problem here is clearly obvious.

**Comment by JonnyLoughlin** [comment]
The way to do this would be to make a `script` tag and pass the go value to it
```
templ Show(msg types.Message) {
  @logMsg(msg)
}

script logMsg(msg types.Message){
  console.log({msg.Success})
}
```

[Here](https://templ.guide/syntax-and-usage/script-templates#script-templates) are the relevant docs

**Comment by rgunindi** [comment]
> The way to do this would be to make a `script` tag and pass the go value to it
> 
> ```
> templ Show(msg types.Message) {
>   @logMsg(msg)
> }
> 
> script logMsg(msg types.Message){
>   console.log({msg.Success})
> }
> ```
> 
> [Here](https://templ.guide/syntax-and-usage/script-templates#script-templates) are the relevant docs

```
/* SyntaxError: Unexpected identifier
for _,v:=range msg{
	console.log(v)
}
*/
msg.forEach(x=>console.log(x))
```

What can we do to provide standard go support here instead of using javascript? 

Using script tag and writing js function in <script> produces the same result.

**Comment by joerdav** [comment]
I think I might have missed the issue here, would you be okay to create a minimal reproduction repo of what you are trying to do?

**Comment by joerdav** [comment]
Ah! I see your issue here, you can't mix Go and JavaScript, you should use a JavaScript loop here.

**Comment by rgunindi** [comment]
But this is a script tag. Why we cannot use Go?

For example, i want to use Go in normal html symnatic script or pass to js script function go variable.

 - pass to js function in html
`<button onclick=jsFunction({c.AcceptedUsers}) name={ c.ID }>Accepted Users</button>`

- directly using go inside of script fucntions.
```
templ Show(flash types.Message) {
<script>
    function fireMessage() {
        var flashMsg = flash.Msg;
    }
</script>
}
```
@joerdav 

Can't we support this behavior?

**Comment by joerdav** [comment]
This is because script tags are for browser scripts, so must be in javascript.

You can do what you suggested though, and pass the go value to a javascript function, as @JonnyLoughlin suggests:

```
templ Show(msg types.Message) {
  @logMsg(msg)
}

script logMsg(msg types.Message){
  console.log({msg.Success})
}
```

**Comment by joerdav** [comment]
It can even be used with an `onClick`

```
script logMsg(msg types.Message){
  console.log({msg.Success})
}
templ Show(msg types.Message) {
    <button onClick={logMsg(msg)}>Log Message</button>
}
```

**Comment by joerdav** [comment]
Documented here: https://templ.guide/syntax-and-usage/attributes/#javascript-attributes
