### ISSUE TITLE
vscode: Inconsistent syntax highlighting inside <script> and <style> tags

### ISSUE THREAD

**Issue by irsyadpage** [a-h/templ#489]
I found that syntax highlighting for JavaScript and CSS inside the `<script>` and `<style>`  tags are highlighted inconsistently. Code inside a function is highlighted properly, whereas the others are not.

![bb](https://github.com/a-h/templ/assets/14093866/30bee435-985e-413b-b1f6-d4cb2ba9ccd3)

Is templ currently does not support syntax highlighting for content inside `<script>` and `<style>`  tags or I misconfigured something?

**Comment by alehechka** [comment]
I can look into this.

**Comment by alehechka** [comment]
Opened a PR: https://github.com/templ-go/templ-vscode/pull/32.
