### ISSUE TITLE
parser: error when a template with arguments on new lines comes after go code

### ISSUE THREAD

**Issue by joerdav** [a-h/templ#505]
I believe I've narrowed the issue down to a minimal reproduction.

Version: a5c60767ef03cfb52db78cb666df5a8df9f7a7a5

Create an index.templ with the contents:

```
package main

var a = "a"

templ template(
	a string,
) {
}
```

Run `templ generate`:

```
(✗) Error generating code [ file=index.templ source formatting error: 12:1: expected declaration, found templ ]
(✗) Event handler failed [ error=failed to generate code for "index.templ": index.templ source formatting error: 12:1: expected declaration, found templ ]
panic: send on closed channel

goroutine 18 [running]:
github.com/a-h/templ/cmd/templ/generatecmd.Generate.Run.func3.1({{0xc0001160c0?, 0xc000069f80?}, 0x69f70?})
        /Users/joe.davidson/src/joerdav/templ/cmd/templ/generatecmd/cmd.go:173 +0x35f
created by github.com/a-h/templ/cmd/templ/generatecmd.Generate.Run.func3 in goroutine 10
        /Users/joe.davidson/src/joerdav/templ/cmd/templ/generatecmd/cmd.go:166 +0x15f

```

**Comment by joerdav** [comment]
I've narrowed the issue down to this line: https://github.com/a-h/templ/blob/main/parser/v2/templatefile.go#L163

It keeps assuming Go code until it finds a line of code that starts with `templ ` and ends with `{`. Of course this logic breaks down if you have a template whose arguments are split across lines.

I'm proposing we remove the check for `{` entirely, do you see any issue with this @a-h ?

**Comment by joerdav** [comment]
Something to weed out the edge cases might be to check if the line contains an open bracket `(`.

**Comment by joerdav** [comment]
I've also found an issue with having go code with multiple sets of curly braces  after a for loop:

The following produces the error: `■ for: expected nodes, but none were found: line 5, col 7`
```
package views

templ Nav() {
<div>
	for _, l := range links {
	<a>{ l.Title }</a>
	}
</div>
}

var links = []struct { }{ }
```

**Comment by kamukwamba** [comment]
templ NavBar(links []Links){
    <header>
        <nav>
            <ul>
                for _, link := range links{ 
                    <li><a href = {temp.URL(link.Href)}></a></li>
                    }
            </ul>
        </nav>
    </header>
    <br />
}

keeps giving the error "home.templ parsing error: for: expected nodes, but none were found"
please help
