### ISSUE TITLE
Error Installing on windows 10

### ISSUE THREAD

**Issue by AlejandroSoftwareDeveloper** [a-h/templ#515]
go install github.com/a-h/templ/cmd/templ@latest
go: downloading github.com/segmentio/encoding v0.3.6
C:\Users\MyUser\go\pkg\mod\github.com\a-h\protocol@v0.0.0-20230224160810-b4eec67c1c22\base.go:9:2: github.com/segmentio/encoding@v0.3.6: reading https://proxy.golang.org/github.com/segmentio/encoding/@v/v0.3.6.zip: 403 Forbidden

**Comment by a-h** [comment]
Hi, this issue is not really a templ problem, the error is coming from the Go CLI, saying that your machine got a 403 error when downloading a file.

I would suggest download a binary, as per https://templ.guide/quick-start/installation#github-binaries

**Comment by AlejandroSoftwareDeveloper** [comment]
Thanks
