### ISSUE TITLE
Is there any way to generate raw attributes without any escaping?

### ISSUE THREAD

**Issue by PyrekP** [a-h/templ#526]
I would like to do something like:
```templ
templ AttrTest(csrf, boo string) {
  <button
    hx-headers={ fmt.Sprintf("'%q:%s'", "csrf-token", csrf) }
    hx-vals={ fmt.Sprintf("'%s'", boo) }
  ></button>
}
```
where boo in this case is valid json like `{"foo":"bar"}`. Currently both hx-headers and hx-vals come out mangled, I mean escaped. Is there any way to disable it?

**Comment by PyrekP** [comment]
Using `@templ.Raw()` for the whole button instead of using an expression just for value works, but it would be nice if we could exlude some specific attributes from being mangled/escaped...

**Comment by joerdav** [comment]
Hi @PyrekP , please see the discussion here: https://github.com/a-h/templ/discussions/519#discussioncomment-8443104

Although it may not be readable for a human, escaping attributes in this case is correct.

**Comment by PyrekP** [comment]
@joerdav Thanks, works great.
