### ISSUE TITLE
LSP Server dont attach to Nvim

### ISSUE THREAD

**Issue by rfbatista** [a-h/templ#529]
Hello, this is my first issue :), if I need to follow some template or bring more information please let me know

For some reason the LSP server don`t attach anymore to the buffer in neovim. Looking in the logs I found this panic message

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7ee30f]

goroutine 2265 [running]:
github.com/a-h/templ/cmd/templ/lspcmd/proxy.(*Document).String(...)
	github.com/a-h/templ/cmd/templ/lspcmd/proxy/documentcontents.go:146
github.com/a-h/templ/cmd/templ/lspcmd/proxy.(*Server).Formatting(0xc0001a6050, {0x9d01b0, 0xc0001a6460}, 0xc0003a2c90)
	github.com/a-h/templ/cmd/templ/lspcmd/proxy/server.go:725 +0xef
github.com/a-h/protocol.serverDispatch({0x9d01b0, 0xc0001a6460}, {0x9d4900, 0xc0001a6050}, 0xc0003a2c30, {0x9d03e0, 0xc000542780})
	github.com/a-h/protocol@v0.0.0-20230224160810-b4eec67c1c22/server.go:422 +0x4936
github.com/a-h/protocol.NewServer.ServerHandler.func1({0x9d01b0, 0xc0001a6460}, 0xc0003a2c30, {0x9d03e0, 0xc000542780})
	github.com/a-h/protocol@v0.0.0-20230224160810-b4eec67c1c22/server.go:36 +0x7e
github.com/a-h/protocol.Handlers.ReplyHandler.func1({0x9d01b0, 0xc0001a6460}, 0xc000156318, {0x9d03e0?, 0xc000542780?})
	go.lsp.dev/jsonrpc2@v0.10.0/handler.go:35 +0xe5
github.com/a-h/protocol.Handlers.AsyncHandler.func2.2()
	go.lsp.dev/jsonrpc2@v0.10.0/handler.go:114 +0x76
created by github.com/a-h/protocol.Handlers.AsyncHandler
```
For some reason we lose the reference to `Document`. It appears to be panicing here: https://github.com/a-h/templ/blob/753ba3966d4ae6c8eb963f210123c1add87bbd70/cmd/templ/lspcmd/proxy/documentcontents.go#L146

**Comment by ChocolateOverflow** [comment]
@rfbatista 
I'm using `nvim-lspconfig` and the templ LSP is getting attached just fine.
If you're using a neovim plugin, you should probably create an issue on that plugin's repo.
If you're doing it manually or believe this is a native issue in templ, please provide more details with steps to reproduce.

**Comment by joerdav** [comment]
Hi @rfbatista , would you mind please providing the version of templ you are using?

**Comment by haydenrou** [comment]
I'm using `lsp-zero` and it's working fine for me too, with `v0.2.598`.

**Comment by rfbatista** [comment]
I am using `v0.2.598` ... But i think @ChocolateOverflow is right, some plugin was messing with templ. I fixed by  manually adding the LSP
