### ISSUE TITLE
Feature request: Reduce verbose output to terminal

### ISSUE THREAD

**Issue by Perusae** [a-h/templ#538]
Is it possible to add a feature, so that the file generation reporting can be truncated. Running a terminal in the left or right side of VSC results in a rather word wrapped experience, what makes it much less clean.

1. First run: Running templ generate creates on first runs:

```
Processing path: /home/perusae/Project

(✓) Generated code for "/home/perusae/Project/Base/Scr/Component/general.templ" in 18.700572ms
(✓) Generated code for "/home/perusae/Project/Base/Scr/Component/Button/Button.templ" in 18.700572ms
(✓) Generated code for "/home/perusae/Project/Base/Scr/Component/....templ" in 18.700572ms
(✓) Generated code for "/home/perusae/Project/Base/Scr/.../....templ" in 18.700572ms
(✓) Generated code for "/home/perusae/Project/Base/Scr/.../....templ" in 18.700572ms
(✓) Generated code for "/home/perusae/Project/Base/Scr/.../....templ" in 18.700572ms
x 55 files ...
```

And clutters the entire terminal output. There is no way to suppress successful generated code. Showing errors = perfect but there is no need to show generated files that are successful beyond a short summary on first run.

2. Output: There really is no need to display the "Generated code for" on each line. A single statement at the top is plenty:

```
Generated code for path ` /home/perusae/Project` :

(✓) "/home/perusae/Project/Base/Scr/Component/general.templ" in 18.700572ms
(✓) "/home/perusae/Project/Base/Scr/Component/Button/Button.templ" in 18.700572ms
(✓)  "/home/perusae/Project/Base/Scr/Component/....templ" in 18.700572ms
(✓)  "/home/perusae/Project/Base/Scr/.../....templ" in 18.700572ms
(✓)  "/home/perusae/Project/Base/Scr/.../....templ" in 18.700572ms
(✓)  "/home/perusae/Project/Base/Scr/.../....templ" in 18.700572ms
```

3. There is no need to show 7 digits behind the milisecond. 

```
Generated code for path ` /home/perusae/Project` :

(✓) "/home/perusae/Project/Base/Scr/Component/general.templ" in 18.7ms
(✓) "/home/perusae/Project/Base/Scr/Component/Button/Button.templ" in 18.7ms
(✓) "/home/perusae/Project/Base/Scr/Component/....templ" in 18.7ms
(✓) "/home/perusae/Project/Base/Scr/.../....templ" in 18.7ms
(✓) "/home/perusae/Project/Base/Scr/.../....templ" in 18.7ms
(✓) "/home/perusae/Project/Base/Scr/.../....templ" in 18.7ms
```

4. Maybe interesting to use path truncating:

```
Generated code for path ` /home/perusae/Project` :

(✓) "/.../Scr/Component/general.templ" in 18.7ms
(✓) "/.../Scr/Component/Button/Button.templ" in 18.7ms
(✓) "/.../Scr/Component/....templ" in 18.7ms
(✓) "/.../Scr/.../....templ" in 18.7ms
(✓) "/.../Scr/.../....templ" in 18.7ms
(✓) "/.../Scr/.../....templ" in 18.7ms
```

Showing the full path is not useful as this is already reported on the first line by templ right now. So the focus needs to be the subdirectories relative to the path.

Notice how much more clean the reporting has become ... Less is more.

**Comment by a-h** [comment]
Maybe it's your lucky day @Perusae - I tidied up the `generate` command CLI output a few weeks ago in https://github.com/a-h/templ/issues/439

It now uses the `slog` package, and you can set whether you want verbose output or not.

It will be included in the next templ release, but you can try it out early by building the main branch. 😁
