### ISSUE TITLE
Generate output differs between windows and linux

### ISSUE THREAD

**Issue by tekulvw** [a-h/templ#539]
Seems mostly related to line endings and path separators in errors. I understand that this behavior could technically be considered correct but personally I think deterministic generation from a given input file would be preferred.

![image](https://github.com/a-h/templ/assets/3731082/ee8dc8a1-7f9f-4856-915e-cfc0f11acae4)
![image](https://github.com/a-h/templ/assets/3731082/7bfdeae2-753f-435e-a66e-6d7ab28a625b)

Both of these screenshots came from autogen diff with no source diff.

**Comment by a-h** [comment]
Thanks, I agree, it would be preferable to standardise on `\n` (fewer bytes) and Unix style relative paths (matches HTTP paths).

**Comment by a-h** [comment]
The code that gets the relative filename for use in error messages is at: https://github.com/a-h/templ/blob/edb6b5501622804e734f367d3e0480b96e03eebf/cmd/templ/generatecmd/eventhandler.go#L180-L189

It uses the Go stdlib to get the relative path, which uses the OS specific separator. I'm not sure if there's a package that converts Windows style paths to Unix style. I expect that a string replace of `\` to `/` would break escaping of some sort.
