### ISSUE TITLE
docs: In gin the status passed to the HTML func is always overwritten with 200

### ISSUE THREAD

**Issue by Foggyman** [a-h/templ#545]
https://github.com/a-h/templ/blob/5d11e601536d97c8d0604ac817255ddc41a550d1/examples/integration-gin/gintemplrenderer/renderer.go#L29

Hi, here we should not call `WriteHeader` since in this way we are overriding the status gin is writing in its HTML func.
For example this code
```
router.GET("/test", func(c *gin.Context) {
    c.HTML(http.StatusTeapot, "", Something())
})
```
would still return a 200 status

**Comment by a-h** [comment]
Yes, you're right. Do you have a suggestion of how to refactor it?

**Comment by Foggyman** [comment]
Sure, I will try to put up something this evening

**Comment by a-h** [comment]
Thanks, that would be great!

**Comment by joerdav** [comment]
Thankyou for the contribution @Foggyman !
