### ISSUE TITLE
Nix flake modules has outdated, add a test?

### ISSUE THREAD

**Issue by headblockhead** [a-h/templ#557]
The current flake.nix uses an [outdated hash for templ's go modules](https://github.com/a-h/templ/blob/ee2ba0e937dae19cf3bd1ee532ff3dcda5a8aae4/flake.nix#L37). Perhaps add a GH actions test of building the flake? I'd be willing to try a PR.

<pre><font color="#AA0000"><b>error:</b></font> hash mismatch in fixed-output derivation &apos;<font color="#AA00AA"><b>/nix/store/frr5inapx2y44y5m6qmdxagdr2vvfii2-templ-go-modules.drv</b></font>&apos;:
         specified: <font color="#AA00AA"><b>sha256-U/KFUGi47dSE1YxKWOUlxvUR1BKI1snRjZlXZ8hY24c=</b></font>
            got:    <font color="#AA00AA"><b>sha256-O3ibTq4oTqIvaLscEuA/0Q9vNVQMHtcO7lOSj9DSKiI=</b></font>
<font color="#AA0000"><b>error:</b></font> <font color="#AA00AA"><b>1</b></font> dependencies of derivation &apos;<font color="#AA00AA"><b>/nix/store/q2yiys1fb05dz861w18114rry1if3151-templ.drv</b></font>&apos; failed to build
</pre>

**Comment by headblockhead** [comment]
I had a closer look at the actions, and it does build using Nix, but a stale entry fetched from the magic-nix-cache is used if the hash is not changed for the vendors.

**Comment by headblockhead** [comment]
Comparing cached and un-cached actions runs on my own fork of this repo:

- First run, a normal commit: builds correctly and caches result.

- Second run, a PR changes version numbers, without updating the hash: builds using *stale* versions of modules fetched from the cache, passes!?

- The cache is deleted

- Third run: mysterious hash mismatch appears from nowhere as the cache can no longer be used to fetch the outdated hash!

Logs and run times:

Run 1 (no cache, first run): passed in 2m 38s
![image](https://github.com/a-h/templ/assets/26520767/012125ba-c9f4-4e2e-a8ab-e27ddb30ce50)

Run 2 (commit is made, action uses cache from run 1): passed in 1m 20s
![image](https://github.com/a-h/templ/assets/26520767/857d1958-fa8d-41e3-96a0-f16ae0050f18)

Run 3 (same commit, without cache): failed in 2m 28s
![image](https://github.com/a-h/templ/assets/26520767/676b22a0-ede2-4651-9695-cbabbe0067e9)

**Comment by headblockhead** [comment]
So I believe that it could be worth the extra run time (around 1 minute) for a guaranteed fresh build?

**Comment by chrisseto** [comment]
Just hit this as well on darwin-arm64.

**Comment by a-h** [comment]
Nice investigation and summary @headblockhead 

I was thinking about swapping to gomod2nix so that go modules are more than just a blob of "stuff". Got an example here: https://github.com/a-h/nix-gomod2nix-example

I think that might allow caching to be used, but also means that Nix derived SBOMs are useful.

**Comment by a-h** [comment]
I've updated the `flake.nix` to use `gomod2nix` instead. I think that should resolve the issue. If you were able to re-test it, that would be great.
