### ISSUE TITLE
vscode: Syntax highlighting for inline method components

### ISSUE THREAD

**Issue by alehechka** [a-h/templ#566]
# Overview 
@Ra0k had opened https://github.com/a-h/templ/issues/561 asking about support for inline method components which has been added in the `main` branch but not released. I wanted to try this out myself and noticed that the VSCode extension does not support syntax highlighting for this type of expression. I can take a look at this and get a PR opened for it.

### Example from https://github.com/a-h/templ/issues/56
```go
package main

type Data struct {
	message string
}

templ (d Data) Method() {
	<div>{ d.message }</div>
}

templ Hello() {
	@Data{
		message: "You can implement methods on a type.",
	}.Method()
}
```

**Comment by alehechka** [comment]
PR opened: https://github.com/templ-go/templ-vscode/pull/38

**Comment by joerdav** [comment]
@alehechka thanks for the PR. I'm not sure if this is a regression but it looks like now non-function components are not rendered properly:

```
templ higherOrderTemplate(a, b templ.Component) {
	<div class="left">
		@a
	</div>
	<div class="right">
		@b
	</div>
}
```

![image](https://github.com/a-h/templ/assets/19927761/8f0259e3-d918-46bc-a6a7-507239d63146)

**Comment by alehechka** [comment]
@joerdav checking this on v0.0.21, it appears to have the same lack of syntax highlighting. So I don't believe this to be a regression. The syntax regex for import-expressions currently relies on `@functionName(` to begin capture. This PR basically just makes `@structName{` also a valid begin capture. 

If you want, I can add syntax highlighting support for non-function components to this PR or open a new one for just that addition?

**Comment by joerdav** [comment]
> If you want, I can add syntax highlighting support for non-function components to this PR or open a new one for just that addition?

Let's do a separate PR, don't want to block your good work any longer!

**Comment by alehechka** [comment]
> Let's do a separate PR, don't want to block your good work any longer!

Sounds good to me. I'll have time after work to take a look at it.

**Comment by alehechka** [comment]
@joerdav, I opened a PR for this: https://github.com/templ-go/templ-vscode/pull/39. It has one open question about the syntax highlighting.
