### ISSUE TITLE
Overriding NopComponent

### ISSUE THREAD

**Issue by caleb-sideras** [a-h/templ#569]
## Overview

At present NopComponent is essentially a no-operation component rendering nothing if no children are passed in. I was wondering if it's possible to override this to allow us to inject other default HTML here? Can be useful if you want to perform operations on statically rendered HTML (i.e. go templating parsing, htmx attributes etc)

**Comment by a-h** [comment]
I can't really picture the use case. Could you write out the templ code you'd like to write, along with the expected HTML?

**Comment by caleb-sideras** [comment]
This specifically targets the injection of dynamically rendered content into a statically rendered template, almost like partial hydration

Consider the following Templ components:

```go
// Contains UI shared across mutiple pages
templ IndexTempl(){
  <html>
    <body>
      {children...}
    </body>
  </html>
}

// Page level UI
templ PageTempl(data Type){
  // render data
}

// Page level function
func Page(w http.ResponseWriter, r *http.Request) templ.Component {
  data := fetchData()
  return PageTempl(data)
}
```
While passing `Page()` into `IndexTempl()` can be achieved per request like follows:  

```go
IndexTempl().Render(templ.WithChildren(r.Context(), Page(w, r)), &buffer)
```

`IndexTempl()` has no dynamic data, so theoretically it can be rendered to html on build and have the `Page()` passed in per request

If `NopComponent` can be overriden to return `{{ template 'page' . }}`, I could then use the go `html/template` library to parse/pass in the `Page()`


(I understand there are better solutions to this, but I want to keep all my html within the Templ library)

**Comment by caleb-sideras** [comment]
I figured out a solution to this, sorry for the unnecessary issue. I will close this now.

Regardless, I do think it's an interesting idea to have the ability to explicitly define default UI if no children are passed in.

**Comment by a-h** [comment]
I'm not sure if you've seen the docs on templ's integration with go templates or the section on template composition.

https://templ.guide/syntax-and-usage/using-with-go-templates

https://templ.guide/syntax-and-usage/template-composition

I'm not sure if those help you get the composition you're looking for, or if the idea you've got is around performance optimisation.

**Comment by a-h** [comment]
Ah, our messages crossed over there.

It would be possible to check if the passed in component is nil, and show default layout that way.

**Comment by caleb-sideras** [comment]
Appreciate the help Adrian! The docs provided on go template integration is very helpful. And yes, my idea was mainly centered about performance optimization.
