### ISSUE TITLE
Why SafeURL is encoded as HTML and not as URL?

### ISSUE THREAD

**Issue by kanstantsin-chernik** [a-h/templ#575]
I was playing with Templ to see if it can replace `html/template` for us and noticed that URL encodings do not match. I put together a quick example. `Html/template` uses url escaping while temple the same escape as html content. 
https://go.dev/play/p/GEDcbcq539t

Should the URL be escaped as a URL instead of HTML?

Here is the template code for URL escaping: https://cs.opensource.google/go/go/+/master:src/html/template/url.go

**Comment by kanstantsin-chernik** [comment]
Here is an example of the URL I have to support
```
somedeeplink://some/url?type=asap&id=test&trackingCode={"name":"test","codeType":"STORE","metaInfo":{"pluginName":"TestName","analyticsLabel":"front"}}"
```

**Comment by a-h** [comment]
Interesting. I took a look at what React does in this case.

If you copy this into `https://playcode.io/react` you'll see the result.

```jsx
import React from 'react';

export function App(props) {
  const urlString = `somedeeplink://some/url?type=asap&id=test&data={"name":"test","codeType":"STORE","metaInfo":{"pluginName":"TestName","analyticsLabel":"front"}}`
  return (
    <div className='App'>
      <a href={ urlString }>URL</a>
    </div>
  );
}
```

In the console, if you edit as HTML, you get the same result as templ.

```
<a href="somedeeplink://some/url?type=asap&amp;id=test&amp;data={&quot;name&quot;:&quot;test&quot;,&quot;codeType&quot;:&quot;STORE&quot;,&quot;metaInfo&quot;:{&quot;pluginName&quot;:&quot;TestName&quot;,&quot;analyticsLabel&quot;:&quot;front&quot;}}">URL</a>
```

<img width="1585" alt="Screenshot 2024-03-03 at 11 42 03" src="https://github.com/a-h/templ/assets/1029947/755febf5-f7ac-4ab8-a5bc-19bffddff525">

I'm not sure why `html/template` would produce that output, but from what I can see, templ is consistent with React's behaviour.

**Comment by kanstantsin-chernik** [comment]
Thanks for looking at it. I dug a bit deeper and it turned out that the url is constructed incorrectly: the query must be escaped. Interestingly enough, there is no good way to escape a query. You would think that "net/url" would do it, but it replaces ' ' with '+'. I think it would be amazing to have a standard html url escaping util. But for now I can just use "net/url" and replqce

**Comment by a-h** [comment]
in Go, there is a way, it's slightly ugly, but it works: https://go.dev/play/p/DqfbeO_CD_0

```go
package main

import (
	"fmt"
	"net/url"
)

func main() {
	fmt.Println(createURL(`{ "key": "value" }`))
}

func createURL(data string) string {
	u := &url.URL{
		Scheme: "https",
		Path:   "/",
	}
	qs := u.Query()
	qs.Set("data", data)
	u.RawQuery = qs.Encode()
	return u.String()
}
```

**Comment by kanstantsin-chernik** [comment]
Yeah, this is what I mean, take a look at the example with spaces: https://go.dev/play/p/dxvWsWDR0_p
For HTML it should used `%20` instead of `+`

**Comment by a-h** [comment]
My understanding is that both are valid, and since both are valid, I'd expect programs to use `+` over `%20` simply because it's 2 characters fewer to transmit, but maybe you have a reason to prefer `%20`. 😁

**Comment by kanstantsin-chernik** [comment]
So, the point is js encodeURIComponent encodes it differently
<img width="313" alt="Screenshot 2024-03-03 at 12 30 35 PM" src="https://github.com/a-h/templ/assets/3438115/01d27d5b-cd31-4530-8f0c-7abc96cf629d">
