### ISSUE TITLE
bug(CSS component args): impossibility of nested properties and strange value `zTemplUnsafeCSSPropertyValue`

### ISSUE THREAD

**Issue by koddr** [a-h/templ#578]
Thanks for the update, @a-h! 

Here is some feedback about [CSS component arguments](https://templ.guide/syntax-and-usage/css-style-management#css-component-arguments) that I identified during testing (`templ v0.2.598`):

1. The impossibility of nested properties, such as `url()` in the `background-image`

```go
css bgImage(image string) {
	background-image: url({ image });
}
```

<img width="1059" alt="Снимок экрана 2024-03-02 в 15 29 31" src="https://github.com/a-h/templ/assets/11155743/6e5fc2e6-1793-494d-89ff-aeb6d024a19f">

And generated result is:

```html
<style type="text/css">.bgImage_9fc6{background-image:url({ image });}</style>
```

2. Strange value `zTemplUnsafeCSSPropertyValue`

```go
css bgImage(image string) {
	background-image: { fmt.Sprintf("url(%s)", image) };
}
```

And generated result is:

```html
<style type="text/css">.bgImage_a54a{background-image:zTemplUnsafeCSSPropertyValue;}</style>
```

How to correctly specify similar CSS properties using **Templ**?

**Comment by a-h** [comment]
Reading through the code, it was expecting quoted URLs for CSS `url` props. I've put forward a PR which adds support for single quoted, double quoted, and unquoted strings.

**Comment by koddr** [comment]
@a-h thanks for the release, but bug is still here :(

<img width="557" alt="screen" src="https://github.com/a-h/templ/assets/11155743/a49fa93c-1370-4d36-88b4-fa973fbecff4">

Input code:

```go
css bgImage(u string) {
	background-image: url({ u });
}
```

Output (generated) code:

```html
<style type="text/css">
.bgImage_0918{
  background-image:url({ u });
}
</style>
```

Config:

- templ: `v0.2.639`
- templ-vscode: `v0.0.22`

**Comment by a-h** [comment]
@koddr - please refer to this example. I think the docs need to be updated.

```
package main

import "os"

templ page() {
	<!DOCTYPE html>
	<html>
		<head>
			<title>Background image</title>
		</head>
		<body>
			<div>
				@profile("image1.png")
			</div>
			<div>
				@profile("image2.png")
			</div>
		</body>
	</html>
}

templ profile(image string) {
	<div class={ profileCSS(image) }>
		Profile
	</div>
}

func bgImage(trustedURL string) templ.SafeCSSProperty {
	return templ.SafeCSSProperty("url(" + trustedURL + ")")
}

css profileCSS(image string) {
	background-image: { bgImage(image) };
}

func main() {
	page().Render(context.Background(), os.Stdout)
}
```

Also, thinking about the next version of templ, supporting this:

```
css profileCSSNext(image string) {
	background-image: { templ.URL(image) };
}
```
