### ISSUE TITLE
"Starting LSP: templ lsp" on VSCode

### ISSUE THREAD

**Issue by soyangel** [a-h/templ#585]
I have a very nitpicky/OCDish problem with the message "Starting LSP: templ lsp" that shows when the VSCode plugin starts. 

I always have to close it manually or wait what it seems a too long time for it to hide . 

Maybe it should be a little less intrusive, like a status bar message? From a 5 min investigation it seems like it this is the recommended behaviour on VSCode:

https://github.com/Microsoft/vscode/issues/2732

EDIT: Link with more info about notifications on VSCode

https://code.visualstudio.com/api/ux-guidelines/notifications

**Comment by a-h** [comment]
I'd take a PR for that. Offending line of code is here.

https://github.com/templ-go/templ-vscode/blob/ba185d4f792eb7f58e35085e830e3b0db84e38ad/src/main.ts#L152

Seems like there's a `setStatusBarMessage(text: string, hideAfterTimeout: number): [Disposable](https://code.visualstudio.com/api/references/vscode-api#Disposable)` function that would do the trick as a replacement.

Imagine your intense satisfaction after fixing it... 😁

**Comment by soyangel** [comment]
Perfect! 

Does something like 3 secs sounds right?

**Comment by a-h** [comment]
Thanks for that @soyangel 

![starting_lsp](https://github.com/a-h/templ/assets/1029947/6ddab085-5053-4d6b-89df-4daf322b185b)
