### ISSUE TITLE
zTemplUnsafeCSSPropertyValue - Unable to use dynamic background-image css component

### ISSUE THREAD

**Issue by RafaelZasas** [a-h/templ#604]
I am unable to use a css component to dynamically add a css background image:

```html
css bgImage(img string) {
	background-image: { img };
	background-size: cover; background-position: center;
}

templ showcase(developments []models.Development) {
	<div class="space-y-36">
		for _, d := range developments {
			<div
				class={
					"flex items-center justify-between",
					"even:flex-row-reverse odd:flex-row",
				}
			>
				<div
					class={ "parallax w-[50%] h-[80vh] bg-fixed",
						bgImage(
                        fmt.Sprintf("url(%s)", d.Images[0].URL),
                        ) }
				></div>
				<div class="bg-white p-8 rounded-lg shadow-lg relative z-10 w-[40%]">
					<h2 class="text-2xl font-bold">{ d.Name }</h2>
					<p>{ d.Description }</p>
				</div>
			</div>
		}
	</div>
}
```

I'm not even able to directly add the styles inline as the compiler does not allow angle brackets on the style attribute, only class attribute.

In the dom I get the background image style with a value of zTemplUnsafeCSSPropertyValue.

```html
<div class="flex items-center justify-between even:flex-row-reverse odd:flex-row">
    <style type="text/css">
        .bgImage_ceb3{
              background-image:zTemplUnsafeCSSPropertyValue;
              background-size:cover;
              background-position: center;
         }
</style>
    <div class="parallax w-[50%] h-[80vh] bg-fixed bgImage_ceb3"></div>
    <div class="bg-white p-8 rounded-lg shadow-lg relative z-10 w-[40%]">
          <h2 class="text-2xl font-bold">Sandhurst</h2>
          <p>A stunning complex</p>
    </div>
</div>
```
I understand that templ is trying to make sure there isnt bad css being injected, but how can I override this?

I don't like the framework making these decisions for me.

Also, the style tag with the background image is only present on the first element in the for loop. I need a different image for each item in the loop

**Comment by a-h** [comment]
Last week https://github.com/a-h/templ/commit/8d4898441887f4155389b48ed93d09ab94b255e9 added a way to bypass CSS property sanitization. It's not been released yet, but is available to try out in the main branch.

Does that solve the issue for you?

**Comment by RafaelZasas** [comment]
It looks good to me.
Thank you, I'll pull main and test it out
