### ISSUE TITLE
templ generate custom name pattern

### ISSUE THREAD

**Issue by i1kaaasra** [a-h/templ#608]
when I use templ I want to have option for custom name pattern name 

hello.templ
templ generete --name-opt {}.go
hello.go

another example
hello.templ
templ generete --name-opt {}_custom.go
hello_custom.go

**Comment by a-h** [comment]
Why?

**Comment by i1kaaasra** [comment]
I want to combine my route and handlers and templ in just one file and after generate it the name of the file is example_templ.go ... I do not like this name ... because my file is not just templ it has handlers and routes and many extra .. or is there any approach use templ in go file without .templ ????

**Comment by a-h** [comment]
No. It would complicate the implementation of every command for no tangible benefit.
