### ISSUE TITLE
Spread JS event map

### ISSUE THREAD

**Issue by iamajoe** [a-h/templ#612]
Sorry in advance in case I have missed an issue related to this.

There are cases where a `map[string]templ.ComponentScript` might make sense but spreading or iterating is not possible on the attributes side. Tried to do a spread with `templ.Attributes` but those are not templ scripts so it makes sense that they do not work.

```go
jsMap := map[string]templ.ComponentScript{
  "onclick": alert(),
}
```

Example A (spread):
```
<button { jsMap... }>Foo</button>
```

Example B (for):
```
<button
for evt, fn := range jsMap {
  {evt}={fn}
}
>Foo</button>
```

Personally I think it would be better to support a `for` under attributes. Also, a `for` even for `templ.Attributes` would be interesting.

**Comment by alehechka** [comment]
I have a PR open that adds support for ComponentScripts within the templ.Attributes. There hasn't been much action for review, but with more interest in the feature maybe it can move over the line.

https://github.com/a-h/templ/pull/595

**Comment by iamajoe** [comment]
Nice. I would say it is still not the best interface since my go to would be to use go syntax but a solution at least and also the "basis" since attributes is like the barebones option.

**Comment by joerdav** [comment]
I'm going to close this issue for now as script templates are [deprecated](https://templ.guide/syntax-and-usage/script-templates#script-templates), we are looking into creating examples of better ways to interact with js in templ, which will hopefully make your use cases easier to implement.

**Comment by iamajoe** [comment]
> I'm going to close this issue for now as script templates are [deprecated](https://templ.guide/syntax-and-usage/script-templates#script-templates), we are looking into creating examples of better ways to interact with js in templ, which will hopefully make your use cases easier to implement.

Why is it deprecated? I am actually using it quite a lot. The idea now is to substitute by the script tags, sure works about the same but think about a button onclick for example, it is easier to set through a ComponentScript. Do you have an issue related to this deprecation I could read?

**Comment by joerdav** [comment]
@iamajoe not yet. Currently there is one for css components, the reasoning is very similar. https://github.com/a-h/templ/issues/740

**Comment by joerdav** [comment]
The deprecation itself happened under https://github.com/a-h/templ/issues/739
