### ISSUE TITLE
dynamic rendering based on server html files

### ISSUE THREAD

**Issue by i1kaaasra** [a-h/templ#629]
I want to rendering dynamic at request time ... 

I get this html form database 
```
<div>Hello, { name }</div>
```

how to render a templ like top at request time

**Comment by a-h** [comment]
I think that what you're asking for is runtime template processing.

templ compiles to Go code, so if you really wanted to use a template that is only available at runtime, you'd need to compile the template into a Go program and run it.

Obviously, there's lots of security and performance considerations around why you wouldn't want to do that.

This is more of a discussion than an issue, so I'm closing this.
