### ISSUE TITLE
bug: passing arrays to templates

### ISSUE THREAD

**Issue by nexovec** [a-h/templ#632]
Hi,
today my templ started failing on code like this example:

```go
package main

type Param struct {
    Member uint
}
templ Thinger(things []Param){

}

templ Caller(){
    @Thinger([]Param{
        {Member:69},
    })
}
```

When I do
```go
package main

type Param struct {
    Member uint
}
templ Thinger(things []Param){

}

templ Caller(){
    @Thinger([]Param{
        Param{Member:69},
    })
}
```
It works but I get a warning `redundant type from array, slice, or map composite literal`.

templ version v0.2.639
go version go1.22.0 linux/amd64

**Comment by a-h** [comment]
Sorry about that, I think this is a duplicate of #626

I have a PR ready to go on that one, so I'll close this.
