### ISSUE TITLE
Is this a bug a.k.a what inputs do components support?

### ISSUE THREAD

**Issue by RoxKilly** [a-h/templ#638]
Parsing fails for this template:
```
package views

templ Outer() {
	<div> @Inner([]string{}) </div>
}

templ Inner(values []string) {
}
```

Error:
> parsing error: \<div\>: expected end tag not present or invalid tag contents: line 6, col 0

However passing no arg to Inner doesn't crash (I expected it to since the function call doesn't match its signature)
```
...
        <div> @Inner() </div>
...
```

Are we not allowed to pass slices into components?  More broadly, what inputs are supported? I couldn't find a clear answer in the docs.

```
~ templ --version
v0.2.646
```

**Comment by ChocolateOverflow** [comment]
I believe this is a bug. I only got this error after upgrading from `v0.2.543` to `v0.2.646`.

**Comment by koddr** [comment]
Absolutely the same behavior.

All my code just broke after upgrading from `v0.2.639` to `v0.2.646` (latest). 

Please pay attention and do not update, until @a-h gives some explanation.

**Comment by a-h** [comment]
The goexpression parser was updated to support multi line go expressions, so it's probably a problem with that.

There's a set of tests in parser/v2/goexpression/parse_test.go for calling templ expressions. There are tests for passing slices and arrays to components, but no tests for passing an empty slice, as per the code snippet above.

I'm out from home at the moment, but that seems like the most likely problem area.

**Comment by a-h** [comment]
Sorry about that, as you can see from the commit, something was happening in the wrong order, and an oversight in the parser tests meant that it wasn't covered.

I've fixed the issue, added some test cases for the behaviour, and will push a small release.

**Comment by RoxKilly** [comment]
Thanks! That update allowed `generate` to work again on the input passing in a slice :-)
