### ISSUE TITLE
Css-modules integration

### ISSUE THREAD

**Issue by timsofteng** [a-h/templ#642]
Hello. How to integration css-modules into go templ project?
Thanks

**Comment by a-h** [comment]
This doesn't sound like an issue, and there's no enough information for me to understand what you're trying to do for it to be a discussion.

This guide is useful regarding issue tracker and general programming etiquette: https://stackoverflow.com/help/how-to-ask

This is linked from that page: https://codeblog.jonskeet.uk/2010/08/29/writing-the-perfect-question/

Feel free to create a discussion if you're able to explain more clearly what it is you're looking for help with.
