### ISSUE TITLE
cmd: report go compile issues on templ generate

### ISSUE THREAD

**Issue by RoxKilly** [a-h/templ#643]
This is only my 2nd day knowing templ and the below seems obvious enough that I'm guessing it's on purpose for reasons I don't understand.  Consider this template:

```
// view.templ
package views

templ Outer() {
	<div> @Inner() </div>
}

templ Inner(values []string) {
}
```

`Inner` is being called without a required argument; in go this code wouldn't compile, but `templ generate` does not complain.  Is this a parser bug?  The generated code in fact cannot compile:
```
// view_templ.go
...
templ_7745c5c3_Err = Inner().Render(ctx, templ_7745c5c3_Buffer)
...
```

> Not enough arguments in call to 'Inner'

Have you considered improving the dev experience by having `generate` look at the generated files for detectable go errors and report them as errors?

**Comment by a-h** [comment]
That's a good point.

The current design is that `templ generate` generates Go code, and `go build` does all the building.

If you use the templ VS Code, goland, or Neovim plug-ins, then the generate command is run in the background, and templ then uses the Go LSP (gopls) to look for diagnostic information like missing params in the generated code. This means that you get updated about problems as you write code in your editor.

Most people probably do that.

However `templ generate` could be updated to run a compile afterwards, or, more simply, to use the existing LSP code to check for errors and warnings.

That would work well for people that aren't using an editor plugin.

For some workflows, it would be wasteful to compile twice, so I guess another flag `--no-compile` or similar would be needed to switch it off.

**Comment by RoxKilly** [comment]
I didn't think about an environment where `go` isn't available.  Funny how quickly things get complex as soon as you scratch the surface.  Maybe in such an environment, the graceful degradation could be the current `generate` plus a warning?

Your replies got me thinking about another tricky case.  If `generate` works and then the `go` check fails, the original -- possibly valid -- `_templ.go` files would have already been overwritten with the "bad" ones.  So I wondered, would a feature like this require that all work be done in a file in memory or in temp storage so the operation can be atomic?  And is this worth your development time (opportunity cost of what the other stuff you could be building instead)?  Like you guys hinted at, compilation will fail with an error that many (most) devs will be able to trace back to the `templ` component call in their template.

Thanks for engaging.

**Comment by joerdav** [comment]
It sounds to me that we're happy with this as is? Compile errors on templ generate has too many complex side-effects.

I'll close for now, and maybe we can discuss again if it becomes more widely asked for?
