### ISSUE TITLE
generator: *string attribute value is ignored

### ISSUE THREAD

**Issue by kanstantsin-chernik** [a-h/templ#647]
Right now `templ.Attributes` silently ignores `*string` during rendering. It would be helpful if it had a case for `*string` and if the value is not nil render it

**Comment by joerdav** [comment]
Thanks for raising this! And thanks @whalenrp for the code contribution.

For now, I've marked this as needs decision, to allow for a discussion on the expected behaviour. I think I agree with your implementation... what to you think @a-h ?

**Comment by a-h** [comment]
That looks sensible to me, I've merged it in. Thanks for that.
