### ISSUE TITLE
feature: add syntax highlighting support to Github - needs Grammar Regex Adjustments

### ISSUE THREAD

**Issue by tris203** [a-h/templ#652]
Hi All,

I am working on a PR for Linguist ( The highlighting used for github). I want to support .templ files, so that they are correctly highlighted on the web interface for GitHub

https://github.com/github-linguist/linguist/issues/6777

I have begun the work on the PR to linguist, when I try to import the grammar file from the VSCode extension, there are 6 errors, all for lookbehind assertions not having a fixed length.

```
Status: Downloaded newer image for linguist/grammar-compiler:latest
docker.io/linguist/grammar-compiler:latest
6 errors found in new grammar 'repository `vendor/grammars/templ-vscode` (from https://github.com/templ-go/templ-vscode.git)':
- Invalid regex in grammar: `source.templ` (in `syntaxes/templ.tmLanguage.json`) contains a malformed regex (regex "`(?<=\s*})`": lookbehind assertion is not fixed length (at offset 8))
- Invalid regex in grammar: `source.templ` (in `syntaxes/templ.tmLanguage.json`) contains a malformed regex (regex "`(?<=<script.*>)(?<!</script>)`": lookbehind assertion is not fixed length (at offset 14))
- Invalid regex in grammar: `source.templ` (in `syntaxes/templ.tmLanguage.json`) contains a malformed regex (regex "`(?<=\s*})`": lookbehind assertion is not fixed length (at offset 8))
- Invalid regex in grammar: `source.templ` (in `syntaxes/templ.tmLanguage.json`) contains a malformed regex (regex "`(?<=\s*})`": lookbehind assertion is not fixed length (at offset 8))
- Invalid regex in grammar: `source.templ` (in `syntaxes/templ.tmLanguage.json`) contains a malformed regex (regex "`(?<=\s*})`": lookbehind assertion is not fixed length (at offset 8))
- Invalid regex in grammar: `source.templ` (in `syntaxes/templ.tmLanguage.json`) contains a malformed regex (regex "`(?<=<style.*>)(?<!</style>)`": lookbehind assertion is not fixed length (at offset 13))
```

I am using the repository here: 
https://github.com/templ-go/templ-vscode

Is there anybody that I can speak to about adjusting these regexs so that the grammar can be imported? Or is this something the project is even interested in

Thanks in advance

**Comment by a-h** [comment]
I'm very interested in having Github highlighting for Linguist.

`templ-go` is an organisation I created to host templ related projects. I haven't moved `templ` itself because it would break the import paths etc.

Do you know what needs to change in those regular expressions for them to continue to work in VS Code, but also work within Linguist?

Possibly a change to use a subexpression or similar? https://stackoverflow.com/a/28227432/1037465

**Comment by tris203** [comment]
I don't know what's needed with the regexs

I can look into it, although ironically I don't actually use VsCode. I was only using that repo as linguist needs a Text mate grammar not Tree-Sitter

I will look into what would be needed. It may just be reversing the logic of the regexs from lookbehinds as they are generally very computationally expensive, which I assume is why they are not recommended

**Comment by joerdav** [comment]
Interesting it was my understanding that GitHub used pigmens, which is why I raised https://github.com/a-h/templ/issues/266

Maybe my info is out of date now!

**Comment by tris203** [comment]
> Interesting it was my understanding that GitHub used pigmens, which is why I raised https://github.com/a-h/templ/issues/266
> 
> Maybe my info is out of date now!

I'm basing off this information

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

(bottom of the Syntax highlighting section)

https://github.com/github-linguist/linguist/blob/master/vendor%2FREADME.md


Additionally, I think the regexs are quite easy to fix. Essentially there are only two formats there

1. Whitespace }
2. (<Tag anything>tag

I think, we can just use capturing groups instead

1. (\s*)}
2. (<script.*>)(?!.*<\/script>)

Although this entirely untested, and I don't have a valid regex licence. https://regexlicensing.org/

**Comment by alehechka** [comment]
I haven't double-checked this against linguist, but at the very least the below PR removes usage of wildcard lookbehinds.

https://github.com/templ-go/templ-vscode/pull/47

**Comment by tris203** [comment]
> I haven't double-checked this against linguist, but at the very least the below PR removes usage of all the wildcard lookbehinds mentioned.
> 
> https://github.com/templ-go/templ-vscode/pull/47

Wow. Good job that was a really fast turn around

**Comment by a-h** [comment]
Thanks @alehechka. I'll run a few tests on code and bring that in.

The ability to test for regressions in the syntax highlighting is a weak spot in the VS Code tooling. I'll take a look to see if there's some sort of "snapshot test" we could apply.

Ideally, the workflow would be that we provide samples of code, the tool produces PNGs or similar, then we eyeball the results and approve them. Then, if there's changes, we run the tests again, and compare snapshots, with visual changes then highlighted between "before" and "after".

That way, any manual eyeballing of sample code etc. will be useful over multiple changes to the highlighting.

**Comment by tris203** [comment]
> Thanks @alehechka. I'll run a few tests on code and bring that in.
> 
> The ability to test for regressions in the syntax highlighting is a weak spot in the VS Code tooling. I'll take a look to see if there's some sort of "snapshot test" we could apply.
> 
> Ideally, the workflow would be that we provide samples of code, the tool produces PNGs or similar, then we eyeball the results and approve them. Then, if there's changes, we run the tests again, and compare snapshots, with visual changes then highlighted between "before" and "after".
> 
> That way, any manual eyeballing of sample code etc. will be useful over multiple changes to the highlighting.

https://github.com/PanAeon/vscode-tmgrammar-test

This seems like an option from a brief look

**Comment by alehechka** [comment]
> https://github.com/PanAeon/vscode-tmgrammar-test
> 
> This seems like an option from a brief look

That seems like a sweet option since it'll allow a direct comparison of the applied tokens. Since this update is also working to fix some issues for linguist, it would probably also be a good idea to run their tests against any proposed changes to make sure we don't break our ability to have GitHub syntax highlighting.

**Comment by joerdav** [comment]
Over on the jetbrains plugin there's a test where we're able to serialise the parsed tree into text, then we do a diff to validate. Looks like this tool will allow us to take a similar approach!

**Comment by a-h** [comment]
Nice find @tris203, I think that would work great.

**Comment by tris203** [comment]
Is there anything I can do to help move this forward? Happy to make a PR if there is anything you need assistance with

**Comment by joerdav** [comment]
@tris203 I've implemented some snapshot tests, so am going to merge the regex changes once I've seen it passes and tested it out.

**Comment by tris203** [comment]
PR opened with linguist

https://github.com/github-linguist/linguist/pull/6798

**Comment by tris203** [comment]
Thankyou for your swift support @joerdav @a-h @alehechka

**Comment by tris203** [comment]
Linguist PR approved. Now just to wait for the next release cycle for the merge

**Comment by a-h** [comment]
Thanks, this is very cool. 😁

**Comment by joerdav** [comment]
Looks like we will be waiting few months unfortunately, but still exciting.

**Comment by tris203** [comment]
This just got merged. So it's getting closer!

**Comment by a-h** [comment]
```templ
package main

func Hello() {
  <div id={ "123" }>Hello</div>
}
```

<img width="411" alt="Screenshot 2024-06-10 at 18 10 51" src="https://github.com/a-h/templ/assets/1029947/f16657ee-2386-421b-8dd8-0f832bbf8ee2">

Yeah, great. Thanks everyone!

**Comment by lorypelli** [comment]
the only question is, why is the first letter lowercase?

**Comment by tris203** [comment]
> the only question is, why is the first letter lowercase?

https://github.com/github-linguist/linguist/issues/6777#issuecomment-2161199896
