### ISSUE TITLE
can't start sentence with `for`

### ISSUE THREAD

**Issue by leandergangso** [a-h/templ#653]
```go
package view

templ Demo() {
    <p>for, this is an invalid sentence</p>
    <p>For, with uppercase works fine</p>
}
```

If a sentence starts with `for` the both vs-code templ and `templ generate` throw error because of the reserved keyword `for` in range/loops.

**Comment by joerdav** [comment]
Thanks for raising an issue, but this is expected behaviour. Please refer to this section of the documentation: https://templ.guide/syntax-and-usage/statements#ifswitchfor-within-text

**Comment by a-h** [comment]
I do wonder whether it would be helpful to start if/switch etc started with `@for` like in Razor pages, in order to avoid this.

It's nice to have minimal syntax noise, but if it happens that people get confused, maybe it's worth changing.

**Comment by leandergangso** [comment]
Sounds interesting. I don't think people will have a hard time switching, since we are already familiar with the @ for components. (I can't imagine that people have custom components named if/for...)

Will be a breaking change but should be simple enough to update.

I do like the way it is now, but wouldn't be opposed to the change.

**Comment by joerdav** [comment]
It's definitely a common pitfall, I wonder how hard the migration for your proposed change would be @a-h ? It would be hard to be backwards compatible so we'd likely need to update the migrate command to help with this? 

There's another alternative, which is to log out the documentation page where this functionality is explained, then hopefully people will easily be able to resolve their issue.

**Comment by gondo** [comment]
Maybe this could be started by introducing compilation flag `templ generate -escaped-reserverd-keywords`
