### ISSUE TITLE
docs: document SafeCSSProperty function

### ISSUE THREAD

**Issue by andybarilla** [a-h/templ#658]
I'm developing a site which has a lot of dynamically generated CSS.

I've found assorted CSS syntaxes which are being improperly marked as unsafe:

```
css exampleClass(config Config) {
	grid-template: { fmt.Sprintf("repeat(%d, 1fr) / repeat(%d, 1fr)", config.Rows, config.Cols)) };
	font-size: { fmt.Sprintf("calc(4vmin * %d)", config.FontScale) };
}
```

I worked around the font size attribute by creating a helper function that does the calculation but can't figure out a way around the `grid-template` attribute. Is there a way (other than using Go's html templates for the CSS) to generate this CSS in Templ?

**Comment by andybarilla** [comment]
I did think of a work around to skip the `repeat` function, but it would be nice to be able to dynamically construct CSS values with functions.

```
css exampleClass(config Config) {
	grid-template-rows: { strings.Repeat("1fr ", config.Rows) };
	grid-template-cols: { strings.Repeat("1fr ", config.Cols ) };
	font-size: { fmt.Sprintf("calc(4vmin * %d)", config.FontScale) };
}
```

**Comment by a-h** [comment]
Hi, sorry, it's not in the docs yet, but you can do it with `templ.SafeCSSProperty` which bypasses CSS sanitisation for known safe values - i.e. by using it, you're marking that, as a develop, you know the string is safe.

```
css windVaneRotation(degrees float64) {
	transform: { templ.SafeCSSProperty(fmt.Sprintf("rotate(%ddeg)", int(math.Round(degrees)))) };
}
```

**Comment by joerdav** [comment]
It sounds like the best course of action is to use this ticket as a documentation change?

**Comment by a-h** [comment]
I've documented it in 6365f9449e3a5a965c52060b3343676979fa2df2
