### ISSUE TITLE
doc: add more hot reload example

### ISSUE THREAD

**Issue by jackielii** [a-h/templ#667]
I think the browser hot reloading can improve productivity. The current documentation mentions the browser reloading on Templ file changes, but doesn't cover other types of files, which leaves community coming up with different solutions that's not efficient as it can be.

I propose adding a example makefile in the documentation to demonstrate a typical workflow that covers most use cases:

```makefile
# run templ generation in watch mode to detect all .templ files and 
# re-create _templ.txt files on change, then send reload event to browser. 
# Open http://localhost:7331
live/templ:
	templ generate --watch --proxy="http://localhost:8080" --open-browser=false -v

# run air to detect any go file changes to re-build and re-run the server
live/server:
	go run github.com/cosmtrek/air@v1.51.0 \
	--build.cmd "go build -o tmp/bin/main" --build.bin "tmp/bin/main" --build.delay "100" \
	--build.exclude_dir "node_modules" \
	--build.include_ext "go" \
	--build.stop_on_error "false" \
	--misc.clean_on_exit true

# run tailwindcss to generate the styles.css bundle
live/tailwind:
	npx tailwindcss -i ./input.css -o ./assets/styles.css --minify --watch

# run esbuild to generate the index.js bundle
live/esbuild:
	npx esbuild js/index.ts --bundle --outdir=assets/ --watch

# watch for any js or css change in the assets/ folder, then reload the browser via templ watch
live/sync_assets:
	go run github.com/cosmtrek/air@v1.51.0 \
	--build.cmd "templ generate --notify-proxy" \
	--build.bin "true" \
	--build.delay "100" \
	--build.exclude_dir "" \
	--build.include_dir "assets" \
	--build.include_ext "js,css"

# start all 5 watch processes
live: 
	make -j5 live/templ live/server live/tailwind live/esbuild live/sync_assets
```

In this setup, Go binary rarely has to be rebuild for reloading to work.

We should also mention:

Caveat: Make sure to serve your static asset with `http.Dir` instead of using `//go:embed` and `http.FS`. E.g.

Instead of:
```go
	//go:embed assets/*
	var assets embed.FS
...
	mux.Handle("/assets/", http.FileServer(http.FS(assets)))
```
Do:
```go
	mux.Handle("/assets/", http.StripPrefix("/assets", http.FileServer(http.Dir("assets"))))
```

If you need to use `go:embed`, just include assets folder to the `live/server` watch list

**Comment by joerdav** [comment]
This sounds like a great documentation addition. However, I think it would fit better as a page of docs rather than an example makefile, this way you could explain how it fits together so people can decide which bits they need.

**Comment by jackielii** [comment]
I can submit a PR to add a separate page, explaining the flow with a diagram, the possible components, and then with the final makefile. Does this sound good?

**Comment by joerdav** [comment]
That sounds like it would be a very useful page.

**Comment by muradbu** [comment]
This is a very welcome addition imo. It's something I frequently run against

**Comment by iloveicedgreentea** [comment]
Thanks this worked for me with no modifications 💯
