### ISSUE TITLE
How to add add pseudo like :hover to CSS component?

### ISSUE THREAD

**Issue by viirak** [a-h/templ#673]
In the document, there's CSS component. But it does not mention how we can add css pseudo like :hover to the className??

`css className() {
	background-color: white;
}`

How to add hover style to above className?

**Comment by a-h** [comment]
It's not currently possible with CSS components.

I'm working on a CSS parser that can support working directly in `<style>` elements instead, see https://github.com/a-h/templ-css/blob/main/parse_test.go for a (very) early look at the idea.

For the time being, just use normal CSS. CSS components are targeted at making reusable component libraries.

**Comment by joerdav** [comment]
Going to close this, we can track progress in #262
