### ISSUE TITLE
lsp: report errors for component call without parentheses

### ISSUE THREAD

**Issue by qdm12** [a-h/templ#676]
Hi there, just learning this wonderful library! 👍 

I encountered a little problem (using VSCode, templ v0.2.648 and vscode extension v0.0.22), where I (silly me) used `@subcomponent` instead of `@subcomponent()` and the extension wouldn't complain about it, but the generated code would be invalid (since it generates `subcomponent.Render` instead of `subcomponent().Render`. Example:

```
templ Bad() {
	<html>
		@subcomponent
	</html>
}

templ subcomponent() {
	<div>Hello</div>
}
```

Although the extension should watch out for components given as arguments which can be called without parentheses. By the way, why is this? 🤔 Shouldn't we make it consistent and force the developer to use `@subcomponent()` in all cases? 🤔

**Comment by joerdav** [comment]
Oddly, I do get an error, but its at the end of the file. Is it the same for you @qdm12 ? 
![image](https://github.com/a-h/templ/assets/19927761/cdc23cbb-87fb-442b-8f4d-c2f49719df93)
