### ISSUE TITLE
I cannot use dynamic css properties

### ISSUE THREAD

**Issue by hpivanov** [a-h/templ#684]
I have the following code:
![image](https://github.com/a-h/templ/assets/16254978/a4073030-fb73-4eca-af23-d72d3a16ea01)
![image](https://github.com/a-h/templ/assets/16254978/62959c9f-59a3-40e3-be2c-39cc7696cb9b)
and for some reason I cannot render the color:
![image](https://github.com/a-h/templ/assets/16254978/285b53cd-3758-474d-9bf6-1185fd842161)

**Comment by joerdav** [comment]
Hi, what you are looking for is CSS components, they are essentially functions that return a CSS class: https://templ.guide/syntax-and-usage/css-style-management#css-components

**Comment by joerdav** [comment]
```
css BgColor(color string) {
    background-color: { color };
}

templ groups() {
// Other code
    <div class={ "color", BgColor(group.Color) }></div>
// Other code

}
```

**Comment by joerdav** [comment]
It allows for better type safety, and xss protection :)

**Comment by hpivanov** [comment]
Thanks! It works 👍
