### ISSUE TITLE
cmd: templ command hangs and I'm unable to kill the templ process

### ISSUE THREAD

**Issue by mileusna** [a-h/templ#685]
I have started using templ recently but bump into the strange problem.

Configuration
- M1 Mac ARM64
- macOS Sonoma 14.4.1 (23E224)
- templ v0.2.663 (go.mod)

Sometimes, or should I say most of the times, `templ generate` doesn't execute properly, it starts the process, but nothing is going on. You can't even stop it with `Ctrl+C` or similar command. Here it is in screen recording:

https://github.com/a-h/templ/assets/4697935/7348a22d-aed9-459f-aeae-df1010f05e8b

And even worse, you can't even kill the process with `kill` command or from Activity Monitor on macOS. Here you can see couple of `templ` processes in Activity Monitor which just hangs there and I can't kill them (force quite, kill -9, nothing...)

<img width="903" alt="Screenshot 2024-04-15 at 12 09 22" src="https://github.com/a-h/templ/assets/4697935/ce0e1998-3410-4c70-b40d-0b9fcc9657f9">

Am I doing something wrong or this is some nasty bug?

**Comment by a-h** [comment]
Interesting. I have an ARM64 Mac, and I don't see the same problem.

If you can run it with the `-v` option, that would be helpful, because you'll get verbose logs, e.g.:

```
$ templ generate -v
(!) templ version check: templ not found in go.mod file, run `go get github.com/a-h/templ` to install it
(✓) Starting post-generation handler
(✓) Walking directory [ path=/Users/adrian/github.com/a-h/example devMode=false ]
(✓) Starting event handler
(✓) Dev mode not enabled, process can finish early
(✓) Post-generation event channel closed, exiting
(✓) Waiting for push handler to complete
(✓) Waiting for event handler to complete
(✓) Waiting for post-generation handler to complete
(✓) Complete [ updates=0 duration=994.917µs ]
```

**Comment by mileusna** [comment]
It could be some macOS security issue since I have updated macOS recently. It looks like that OS is blocking the execution. After deleting and reinstalling templ everything works normally so far.

I will close the ticket for now, I will reopen it if problem continues and when I get more info.
