### ISSUE TITLE
Proxy: injection of `script.js` with Brotli compression is silently failing

### ISSUE THREAD

**Issue by AlyxPink** [a-h/templ#692]
I encountered an issue where `script.js` was inconsistently injected into pages across different browsers. Specifically, both Safari and cURL successfully had the JavaScript script injected, whereas Firefox did not.

Upon further investigation by exporting requests from Safari and Firefox as cURL commands, I pinpointed the cause to the differences in the `Accept-Encoding` header. The request from Firefox uses `Accept-Encoding: br`, unlike Safari or a basic cURL command.

Here are the results demonstrating this discrepancy:
```
$ curl -s 'http://localhost:7331/' -H 'Accept-Encoding: gzip' | gunzip - | grep -Eo '</main>.*'
</main><script src="/_templ/reload/script.js"></script></body></html>
```

```
$ curl -s 'http://localhost:7331/' -H 'Accept-Encoding: br' | brotli -d | grep -Eo '</main>.*'
</main></body></html>
```

I don't think I would be capable of submitting a PR, but I'll give a try if I got time. Maybe warning the user that only `gzip` compression is supported today could be easily doable, while a proper fix could come later?

**Comment by a-h** [comment]
Great find, thanks for raising the issue. I agree that it shouldn't fail silently.

I don't think it would be hard to add the brotli support alongside gzip.

Are there any others we should add proactively?

**Comment by AlyxPink** [comment]
Oh, cool if it's not too hard to add support for brotli!

[MDN lists others format](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding#directives), but I'm not sure if any browser is using something other than gzip or brotli.

**Comment by a-h** [comment]
OK, PR https://github.com/a-h/templ/pull/695 added.

I've added brotli support, and logged a warning if an unsupported encoding was used, along with tests.

Could you please test it out to make sure it works for you before I merge it?

**Comment by AlyxPink** [comment]
Yes, it almost works! There is just a tiny detail, otherwise it's perfect 🙌

## Issue with HTTPS? An header?

I first tried with the same test as before, and bingo! The script was now here (and it worked in Firefox too, no problem):

```
$ curl -s 'http://localhost:7331/' -H 'Accept-Encoding: br' | brotli -d | grep -Eo '</main>.*'
</main><script src="/_templ/reload/script.js"></script></body></html>
```

So then, I tried with my usual workflow, where I'm using a local HTTPS dev hostname. But the page wasn't reloading. The script wasn't here anymore 😨 .

I started to create a mini project to reproduce it, isolated from the stack I'm using, with a basic `net/http` server.
Then I thought "wait, check the fix before, maybe it will give you an idea". And I saw this line https://github.com/a-h/templ/commit/ef58c7a1b2bdaee62bf200a82d404d355e94cafb#diff-860a2d05f2fc056a3b00dc4f0ccad808424e95dbea19feef713aab918748cb9dR56

At first, I thought it was related to the `Content-Type` header **value**, perhaps something in my stack was messing up with it? So I went back to cURL and look at what the HTTPS proxy do 😩

```
$ curl -sI 'https://web.my-app.orb.local/' -H 'Accept-Encoding: br' | grep -i 'content-type'
content-type: text/html; charset=utf-8

$ curl -sI 'http://localhost:7331' -H 'Accept-Encoding: br' | grep -i 'content-type'
Content-Type: text/html; charset=utf-8
```

But `r.Header.Get()` is case-insensitive 🤔 So I'm not sure what the fix would look like.

## How to reproduce

### My local HTTPS setup
I'm running https://orbstack.dev/ on my local machine, which expose any docker containers through a local HTTPS proxy. If you can do the same, then you can go to https://templ-issue-692.orb.local/ and it should work.

If you can't have Orbstack, I don't know an easy way to get an HTTPS running on localhost locally, sorry 😬 

### Files

`Dockerfile`:

```Dockerfile
# syntax=docker/dockerfile:1

ARG GO_VERSION=1.22
FROM golang:${GO_VERSION}-alpine
WORKDIR /src

COPY . .
RUN go install github.com/a-h/templ/cmd/templ@ef58c7a1b2bdaee62bf200a82d404d355e94cafb && \
    go mod download -x

EXPOSE 7331
CMD templ generate --watch --proxy="http://localhost:4000" --proxybind="0.0.0.0" --open-browser=false --cmd="go run main.go hello_templ.go"
```

`main.go`:

```golang
package main

import (
	"net/http"

	"github.com/a-h/templ"
	"github.com/labstack/echo/v4"
)

func main() {
	app := echo.New()
	app.GET("/", HomeHandler)
	app.Logger.Fatal(app.Start(":4000"))
}

// This custom Render replaces Echo's echo.Context.Render() with templ's templ.Component.Render().
func Render(ctx echo.Context, statusCode int, t templ.Component) error {
	ctx.Response().Writer.WriteHeader(statusCode)
	ctx.Response().Header().Set(echo.HeaderContentType, echo.MIMETextHTML)
	return t.Render(ctx.Request().Context(), ctx.Response().Writer)
}

func HomeHandler(c echo.Context) error {
	return Render(c, http.StatusOK, Home())
}
```

`hello.templ`

```golang
package main

templ Home() {
	<html>
		<body>
			<h1>Hello, World!</h1>
		</body>
	</html>
}
```

```sh
go get github.com/a-h/templ/cmd/templ@ef58c7a1b2bdaee62bf200a82d404d355e94cafb
go get github.com/labstack/echo/v4@v4.12.0
```

### Launch command
Launch the container:

```sh
$ docker run --rm -p 7331:7331 --name=templ-issue-692 $(docker build -q .)
```

### cURL results

```
$ curl -v https://templ-issue-692.orb.local
*   Trying 192.168.215.2:443...
* Connected to templ-issue-692.orb.local (192.168.215.2) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: O=OrbStack Development; OU=Containers & Services; CN=templ-issue-692.orb.local
*  start date: Apr 26 01:26:10 2024 GMT
*  expire date: Jul 26 01:26:10 2026 GMT
*  subjectAltName: host "templ-issue-692.orb.local" matched cert's "templ-issue-692.orb.local"
*  issuer: O=OrbStack Development; OU=Containers & Services; CN=OrbStack Development Root CA
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://templ-issue-692.orb.local/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: templ-issue-692.orb.local]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.4.0]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: templ-issue-692.orb.local
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/2 200
< content-type: text/html; charset=utf-8
< date: Fri, 26 Apr 2024 01:26:46 GMT
< content-length: 48
<
* Connection #0 to host templ-issue-692.orb.local left intact
<html><body><h1>Hello, World!</h1></body></html>
```

```
$ curl -v http://localhost:7331/
*   Trying [::1]:7331...
* Connected to localhost (::1) port 7331
> GET / HTTP/1.1
> Host: localhost:7331
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 96
< Content-Type: text/html; charset=utf-8
< Date: Fri, 26 Apr 2024 01:26:47 GMT
<
* Connection #0 to host localhost left intact
<html><body><h1>Hello, World!</h1><script src="/_templ/reload/script.js"></script></body></html>
```

---

Let me know if I can help you with anything 🙇 And thanks again for the quick fix, it's really awesome 🙌

**Comment by AlyxPink** [comment]
Hey @joerdav @a-h, sorry for the direct ping, I wanted to ask if you had seen the report above? I can open a new issue if you prefer, of course. Thank you so much.

**Comment by a-h** [comment]
Hi @AlyxPink - sorry, didn't spot this one. I don't think it's an issue with HTTPS, I can't see a reason for that.

I did get a PR this week that updated the Echo example - see https://github.com/a-h/templ/commit/6a9dbff61ab1a130a866aa529384bc92e2448e54 and the associated issue https://github.com/a-h/templ/pull/734

If adjusting the Echo integration doesn't work, then I think the best thing to do would be to add some extra logging at the templ side so that we can check what it's getting from Orbstack.

`cmd/templ/generatecmd/proxy/proxy.go` is the bit that would need additional logging adding. I think some `debug` level logging would be OK to add.

**Comment by AlyxPink** [comment]
Would you like me to test this and send you the new logs you've created?

Sorry for the very late replied, I burnt myself out of code for a little while 😿
