### ISSUE TITLE
templ-vscode fast html insert

### ISSUE THREAD

**Issue by mcgtrt** [a-h/templ#703]
It would be great if the templ-vscode would recognise when we write HTML code and will auto-complete elements with classes, just like it does in a .html file. 

For example, writing `p.pl-10.text-blue` will return `<p class="pl-10 text-blue"></p>`

**Comment by indaco** [comment]
Did you check the Emmet HTML completion section at https://templ.guide/commands-and-tools/ide-support ?

**Comment by joerdav** [comment]
This is correct, it should allow you to do exactly what you are proposing @mcgtrt if you update your settings, no extension required.

**Comment by mcgtrt** [comment]
@indaco this solution allows formatting HTML which I already have and it does work by updating the settings.json. What I'm looking for is automated completion of HTML elements
![ScreenRecording2024-04-29at11 39 02-ezgif com-speed](https://github.com/a-h/templ/assets/22679057/188cf216-e7b4-45df-9dcf-42301bf468db)

**Comment by joerdav** [comment]
![Screenshot 2024-04-29 at 11 12 14](https://github.com/a-h/templ/assets/19927761/029a6f5f-cc8f-4f06-be39-0a63e54003bc)

I seem to get the desired effect.

**Comment by mcgtrt** [comment]
Yes works now, misstypo in my configuration. Thanks a lot for the help lads
