### ISSUE TITLE
I need a break statement

### ISSUE THREAD

**Issue by nicolasfranck** [a-h/templ#707]
Is there support for the control statement `break`? I often find myself in the situation where a regular for-loop doesn't just do what I need. For example a `range` does take `nil` into account, so is safe to execute:

```
var m map[string]string
for key, val := range m {

}
```

But what for example if I need the first key of that map?

**Comment by joerdav** [comment]
The way I would approach this is with a separate Go function to extract a key from the map.

This separates the logic from the presentation a bit more.

You may already know this, but keep in mind that maps don't have a reliable order, so the `first` record is potentially not going to give you reliable results.

```
func oneKey(m map[string]string) string {
    for key, _ := range m {
        return key
    }
}

templ view(m map[string]string) {
    <p>{ oneKey(m) }</p>
}
```

**Comment by nicolasfranck** [comment]
Well yes, I was afraid of that. I'm asking, because I saw myself writing a new method for every use case like that (I cannot put this in a one liner). Of course a `break` would need `{}` to be parsed correctly as a statement

**Comment by joerdav** [comment]
An option would be to use go generics if you are repeating functions a lot.
