### ISSUE TITLE
Enable generating Go code, not just HTML

### ISSUE THREAD

**Issue by clayne11** [a-h/templ#715]
I've worked on a number of Golang code generation tools. Doing things like taking gRPC / GraphQL AST and generating builders, GraphQL servers, and the like. The tooling and dev model of `templ` is awesome and I would love to use it as a code generator rather than an HTML generator. I can imagine some relatively small tweaks to make this work, something like:

```
templ MyFile(input string) {
  <go>
    package main
    
    func main() {
      <$fmt := import "fmt">
      <$fmt>.Println(input)
    }
  </go>
}
```

`templ` could then collect all the imports in a file, arrange them at the top, and format the Go code. Of course you can't do the same type of validation that you can do with HTML, but this would be an incredibly powerful paradigm for creating code generator tools.

What do people think of this idea?

**Comment by joerdav** [comment]
The mission of templ is to:

>    Enable Go developers to build strongly typed, component-based HTML user interfaces with first-class developer tooling, and a short learning curve.

At the moment this is not a part of the plan, we've had similar suggestions before around templating text https://github.com/a-h/templ/issues/631, but for now we are putting focus on creating a really effective HTML templating tool.

**Comment by a-h** [comment]
Agree with @joerdav - it's a nice idea to support other languages - text, etc., but even if we wanted to, I think it would open up lots of new edge cases and demand for new features that I think would ultimately result in it being really hard to maintain the project over the long term, so I think we need to keep the scope small.

Once we've really nailed HTML, JS, and CSS, and are basically bored... maybe it would be time to think about it! 😁
