### ISSUE TITLE
Golang code generated always import github.com/a-h/templ even if not used

### ISSUE THREAD

**Issue by fmarmol** [a-h/templ#727]
the go code generated always import templ package, which can cause issues if templ package is not used in go code.

example:
file a.templ
```
package foo
type A struct{}
```
produces the following code:
```
// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package foo

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

type A struct{}
```

The reason behind to not use any rendering component in file a.templ is just to organise the code  (structures) in multiple files

**Comment by joerdav** [comment]
@fmarmol I would recommend storing these files in go files `a.go` as there is no benefit to running templ generate on them. You will still be able to call this go code from your templ file.

**Comment by joerdav** [comment]
I'll close this now as there is a quick solution.
