### ISSUE TITLE
vscode: show _templ.go files greyed out?

### ISSUE THREAD

**Issue by jwarlander** [a-h/templ#730]
It would be nice if the generated `*_templ.go` files could be greyed out in the tree view in VS Code, either by default or as an option, just to indicate that one probably doesn't want to edit those, and that it's the `.templ` files that are important.

Perhaps one could even indicate that `_templ.go` files are stale by some kind of marker, if they have an older timestamp than the corresponding `.templ` file..

I'm not super familiar with TypeScript, or how VS Code plugins work in general, but I'm guessing something like how files in `.gitignore` are handled would be applicable:

https://github.com/microsoft/vscode/blob/4a6ebe0ee5b2d13435e42416640b69d1a1004289/extensions/git/src/decorationProvider.ts#L14-L85

**Comment by indaco** [comment]
Why not allow both the options via plugin settings?

Anyhow, my personal preference would be for option 1

**Comment by a-h** [comment]
Reasonable. It's also possible to enable commands like "showGeneratedFiles". We do this already for "templ.restartServer"`.

## 3: Grey out the filename in explorer

Updating the `activate` function in `main.ts`:

```typescript
export async function activate(ctx: vscode.ExtensionContext) {
  try {
    ctx.subscriptions.push(
      vscode.commands.registerCommand(
        "templ.restartServer",
        startLanguageClient
      )
    );

    vscode.window.registerFileDecorationProvider(formatGeneratedFilesInExplorer);

    await startLanguageClient();
  } catch (err) {
    const msg = err && (err as Error) ? (err as Error).message : "unknown";
    vscode.window.showErrorMessage(`error initializing templ LSP: ${msg}`);
  }
}

const formatGeneratedFilesInExplorer: vscode.FileDecorationProvider = {
  provideFileDecoration: async (uri) => {
    if (uri.path.endsWith('_templ.go')) {
      return {
        color: new vscode.ThemeColor('gitDecoration.ignoredResourceForeground')
      };
    }
    return undefined;
  }
};
```

Produces this effect:

<img width="378" alt="Screenshot 2024-05-06 at 18 15 04" src="https://github.com/a-h/templ/assets/1029947/85c0d4af-a9fd-4dc1-b2ba-6ac8758dfb0c">

Note how the filename is greyed out.

**Comment by joerdav** [comment]
Nesting seems the most sensible to me, its the default behavior of the goland plugin too.

**Comment by jwarlander** [comment]
Either nesting or greyed out files would work quite well, I think, and make it clearer what parts to focus on in the explorer! :tada: 

Hiding them completely might be confusing.

**Comment by ddelpero** [comment]
Options 1 and 2 can be set in the vscode Settings without changing anything in the extension.

**Comment by a-h** [comment]
We have consensus on enabling file nesting (option 1)?

I don't think we can realistically do option 2 in that list until #726 and #415 are dealt with.

And option 3 is basically just abusing git decorations. 😁 

So, time to implement option 1 for now.

**Comment by a-h** [comment]
Fixed in https://github.com/templ-go/templ-vscode/commit/913c9b89ca152413024f28d0b7419ef147e44410
