### ISSUE TITLE
lsp: support the organizeImports code action

### ISSUE THREAD

**Issue by joerdav** [a-h/templ#757]
Currently, as you are typing a package if you autocomplete it the lsp will import it for you. However, one feature of gopls that templ does not support is `organizeImports`, this can be set to run on-save and will import, reorder and remove imports depending on what is being used.

In nvim to apply this codeAction you can run `lua vim.lsp.buf.code_action({ context = { only = { "source.organizeImports" } }, apply = true })`

This currently works in go files via gopls, but not templ files.

**Comment by joerdav** [comment]
From my basic understanding I think this will involve supporting "codeActionLiteralSupport", this allows actual page edits to be returned from the `textDocument/codeAction` request.

**Comment by joerdav** [comment]
After some more investigation, this is nothing to do with the above! The problem is that gopls does not do organizeImports on generated files, the string at the top of our go files `DO NOT EDIT` means that it is ignoring the request.

I tried removing it in our cached version of the go file, however it seems that gopls is still reading the disk version of the file, therefore it still contains the comment.

One solution would be to remove this comment entirely, @a-h do you think that is sensible, as organize imports is a fairly requested feature?

**Comment by joerdav** [comment]
I have now managed to get gopls to respond to the request. However, now when mapping to the templ file the code becomes mangled, it tries to convert it to a multiline import as the generated file contains multiple imports even if the templ file only has one.

The way I can think to do this, is apply the change to the generated imports list, remove the "implicit" imports and then create our own change list for the templ file.

**Comment by a-h** [comment]
Released in https://github.com/a-h/templ/releases/tag/v0.2.731
