### ISSUE TITLE
Wasm support for interacting with the DOM

### ISSUE THREAD

**Issue by arejula27** [a-h/templ#758]
Is it planned to add support for wasm so scripts can be done in go instead of JS?

I am trying to implement a modal, which requires a simple JS code, if a wasm API for modifying the DON is used then JavaScript would not be required

**Comment by AlexanderArvidsson** [comment]
WASM cannot access DOM, you need to write javascript. Also in my opinion, this is out of scope of Templ, which is a server-only template engine.

Have you taken a look at the `<dialog>` html element, which has been baseline since March 2022?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

**Comment by arejula27** [comment]
Yes, I had to add a few JS to open and close it. Issue can be close, mb

**Comment by a-h** [comment]
I've updated https://templ.guide/syntax-and-usage/script-templates/ to add additional detail on how to work effectively with JS / TypeScript using `esbuild` as a bundler. You don't even need to create an NPM project if you're not using any external NPM packages.

I don't see templ / HTMX or anything else completely replacing JS in the short term, but minimising how much of it we have to write to get things done? Definitely!

I would like to see Go be a great WASM target, but I suspect that the current large binary size of Go will mean that JS / TS is almost always a better choice for small interactive scripts.

However, there's a templ playground in the works that lets you try out templ code in the browser, with the build happening in the browser using WASM... I haven't work on it, so I won't steal the team's thunder. When they're ready to release, I'll be talking about it.
