### ISSUE TITLE
css expression: found unexpected parameters

### ISSUE THREAD

**Issue by leomorpho** [a-h/templ#789]
Not sure what I'm missing, but when using a parameterized css function, it fails using templ v0.2.707.

```templ
css loading(percent int) {
	width: { fmt.Sprintf("%d%%", percent) };
}
```
The above gives me `css expression: found unexpected parameters`.
I must be doing something wrong because this is an example from the docs, but I can't figure out what that is...any ideas?

**Comment by chilljalapeno** [comment]
You can try without the two percentage signs after d, I think it is a mistype.
`
css loading(percent int) {
  width: {fmt.Sprintf("%d", percent) };
}
`
It works for me, I have some similar code.  Hope it helps

**Comment by joerdav** [comment]
@leomorpho I tried to recreate the error but could not. I pasted it into https://play.templ.guide/ and had no issue.

**Comment by JoshuaSchlichting** [comment]
@leomorpho I had this issue with `v0.2.408`. I installed the latest version via `go install github.com/a-h/templ/cmd/templ@latest`, bringing me up to `v0.2.731`, and the error appears to have cleared up!

**Comment by a-h** [comment]
Seems dealt with...
