### ISSUE TITLE
Abandoned change to not modify files where fmt makes no changes

### ISSUE THREAD

**Issue by hellified** [a-h/templ#794]
There was an issue: https://github.com/a-h/templ/issues/128
And a code change: https://github.com/a-h/templ/commit/3d478b3bf49345f0a365843b6507f0cb253b4c55

But it looks as though the change was abandoned?
I was hoping either to have the change merged in, since I'm having the same issue as the original issue filer, or learn what the alternative/workaround was.

**Comment by a-h** [comment]
Yeah, I don't know why. Just looks like a mistake not to include it, tbh.

**Comment by a-h** [comment]
See https://github.com/a-h/templ/pull/797

**Comment by hellified** [comment]
Ah, that's wonderful. Just fell through the cracks I guess. Back on track now, so no worries. I'll just watch the PR and anticipate the release.
Thanks!
