### ISSUE TITLE
lsp error when ı reload or open templ file

### ISSUE THREAD

**Issue by BeratHundurel** [a-h/templ#800]
I am getting an error in VS Code that says 'connection to server got closed' when I reload the page or open new templ file. I logged the error and found this error message: 'unable to complete because the sourcemap for the URI doesn't exist in the cache.'

I will attach the log file. Also, in the command line, I am able to execute commands like "templ lsp --help", and "which go gopls templ" command give me correct results.
[templ.log](https://github.com/user-attachments/files/15930381/templ.log)

**Comment by FernandoAcTr** [comment]
I'm facing the same issue. Any idea how to fix it?

**Comment by DarioDT75** [comment]
I'm affected too.
`go version go1.22.1 darwin/amd64`
VS Code reports:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb79c620]

goroutine 42 [running]:
github.com/a-h/templ/cmd/templ/lspcmd/proxy.(*Server).CodeAction(0xc000146050, {0xb980730, 0xc0000b2000}, 0xc0003af620)
	/Users/dark/go/pkg/mod/github.com/a-h/templ@v0.2.707/cmd/templ/lspcmd/proxy/server.go:294 +0x480
github.com/a-h/protocol.serverDispatch({0xb980730, 0xc0000b2000}, {0xb985a20, 0xc000146050}, 0xc0005008d0, {0xb980a08, 0xc0000b0000})
	/Users/dark/go/pkg/mod/github.com/a-h/protocol@v0.0.0-20230224160810-b4eec67c1c22/server.go:158 +0x4013
github.com/a-h/protocol.NewServer.ServerHandler.func1({0xb980730, 0xc0000b2000}, 0xc0005008d0, {0xb980a08, 0xc0000b0000})
	/Users/dark/go/pkg/mod/github.com/a-h/protocol@v0.0.0-20230224160810-b4eec67c1c22/server.go:36 +0x7e
github.com/a-h/protocol.Handlers.ReplyHandler.func1({0xb980730, 0xc0000b2000}, 0xc0003c8078, {0xb980a08, 0xc0000b0000})
	/Users/dark/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:35 +0xc6
github.com/a-h/protocol.Handlers.AsyncHandler.func2.2()
	/Users/dark/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:114 +0x76
created by github.com/a-h/protocol.Handlers.AsyncHandler.func2 in goroutine 25
	/Users/dark/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:112 +0x165
[Error - 2:06:41 PM] Server process exited with code 2.
[Error - 2:06:41 PM] Connection to server got closed. Server will not be restarted.
```
[gopls.log](https://github.com/user-attachments/files/15933004/gopls.log)
[templ.log](https://github.com/user-attachments/files/15933008/templ.log)

**Comment by DarioDT75** [comment]
Update: in a machine that was working fine, it started to happen once gopls was updated to 0.16.0

**Comment by tim-rus** [comment]
> Update: in a machine that was working fine, it started to happen once gopls was updated to 0.16.0

Yeap. Rolled back to gopls@v0.15.3 and that fixed the problem.
Thnx.

**Comment by joerdav** [comment]
This has been fixed in mainline, so should be resolved in the next release. Alternatively you can install mainline now `go install github.com/a-h/templ/cmd/templ@main`

**Comment by advdv** [comment]
@a-h @joerdav sorry for pinging but I think it might be worth it to roll a new release just to fix this because changing to the mainline release "@main" triggers this issue: https://github.com/a-h/templ/issues/801.  Or maybe create a pinned issue to advise users to prevent new issues from being created for the same problem, e.g:
- https://github.com/a-h/templ/issues/806
- https://github.com/a-h/templ/issues/803

**Comment by EmmanuelOga** [comment]
Thank you @advdv, just chiming in to say I'm getting the exact same issue and I was wondering how to fix it :-)

**Comment by a-h** [comment]
Fixed in https://github.com/a-h/templ/releases/tag/v0.2.731
