### ISSUE TITLE
Error Starting VCS Extension

### ISSUE THREAD

**Issue by biggi93** [a-h/templ#807]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xcdaa00]

goroutine 31 [running]:
github.com/a-h/templ/cmd/templ/lspcmd/proxy.(*Server).CodeAction(0xc00016e460, {0xebaed0, 0xc00016e190}, 0xc000180840)
	C:/Users/Surfer/go/pkg/mod/github.com/a-h/templ@v0.2.707/cmd/templ/lspcmd/proxy/server.go:294 +0x480
github.com/a-h/protocol.serverDispatch({0xebaed0, 0xc00016e190}, {0xec11d0, 0xc00016e460}, 0xc000226f00, {0xebb1a8, 0xc00011e400})
	C:/Users/Surfer/go/pkg/mod/github.com/a-h/protocol@v0.0.0-20230224160810-b4eec67c1c22/server.go:158 +0x4013
github.com/a-h/protocol.NewServer.ServerHandler.func1({0xebaed0, 0xc00016e190}, 0xc000226f00, {0xebb1a8, 0xc00011e400})
	C:/Users/Surfer/go/pkg/mod/github.com/a-h/protocol@v0.0.0-20230224160810-b4eec67c1c22/server.go:36 +0x7e
github.com/a-h/protocol.Handlers.ReplyHandler.func1({0xebaed0, 0xc00016e190}, 0xc00010edb0, {0xebb1a8, 0xc00011e400})
	C:/Users/Surfer/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:35 +0xc6
github.com/a-h/protocol.Handlers.AsyncHandler.func2.2()
	C:/Users/Surfer/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:114 +0x76
created by github.com/a-h/protocol.Handlers.AsyncHandler.func2 in goroutine 23
	C:/Users/Surfer/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:112 +0x165
[Error - 8:31:01 PM] Connection to server got closed. Server will not be restarted.
[Error - 8:31:01 PM] Server process exited with code 2.

**Comment by biggi93** [comment]
Thank you, worked!

**Comment by a-h** [comment]
Fixed in https://github.com/a-h/templ/releases/tag/v0.2.731
