### ISSUE TITLE
[question] go 1.22 iterators / rangefunc

### ISSUE THREAD

**Issue by netbrain** [a-h/templ#822]
Will the templ framework implement the new rangefuncs / iterators from go 1.22?

Not quite sure if it will add any value to the framework as I just recently picked up on using templ, but I guess it could make looping over stuff easier?

Like for instance creating your own multiple custom iterators on structs or custom slice types for different ways of listing out the data?

**Comment by netbrain** [comment]
Seems templ already supports the iter.Seq and iter.Seq2 as looping functions. But could not get it working with the type `func(yield func(V) bool)` :shrug:

**Comment by joerdav** [comment]
Yes, I wouldn't expect there to be any work for templ to do to support iterators. What you are referring to will be a bug if it is not working, can you provide a reproducible example please?

**Comment by a-h** [comment]
Closed: no further info provided.
