### ISSUE TITLE
Release `v0.2.731` breaks Mason.nvim integration

### ISSUE THREAD

**Issue by zyriab** [a-h/templ#823]
Hello!
First off, amazing job with Templ, this is amazing!

I am using Mason with Neovim to manage my LSPs, Linters, DAPs, etc but I can't get the Templ LSP to work properly with it.
I spent a few hours debugging my config and I found out that the problem is that the [Mason registry](https://github.com/mason-org/mason-registry/blob/main/packages/templ/package.yaml#L16) uses the latest release, not the latest version of the code on the main branch.

If I ditch Mason and use `go install` pointing to the `latest` version, I get the `v0.2.734` which works just fine: auto-imports, auto-completion, etc.

Since my entire LSP config turns around Mason, I can't (and won't) ditch it easily, so I wanted to ask: can you make a release with the current version of the main branch?

Thanks and take care :)

**Comment by joerdav** [comment]
I would expect the latest release `v0.2.731` to work fine as-well. Can you please outline exactly what has broken in this version?

**Comment by joerdav** [comment]
Are you experiencing the bug fixed in https://github.com/a-h/templ/commit/01d33616aadcc08e450a95f7bce086e7f44662c5 ?

It is worth mentioning that you can tell mason not to install an lsp and use the version installed to your PATH, this is what I do since often I am working on a local version of templ.

**Comment by zyriab** [comment]
Hey, thanks for taking the time to answer!
I'm not sure what breaks what, I just don't have any LSP capabilities with Mason's version.

I've looked at how I could tell Mason to let me use my local version, haven't found it.
I'll see and implement that until a new release is out. :)

Cheers

**Comment by a-h** [comment]
Thanks @zyriab - should now be fixed in https://github.com/a-h/templ/commit/26c1d79761e7800837caffdd3c8c2abab96e0794

**Comment by zyriab** [comment]
> Thanks @zyriab - should now be fixed in https://github.com/a-h/templ/commit/26c1d79761e7800837caffdd3c8c2abab96e0794

You're the best! I appreciate all the hard work you're putting in!
