### ISSUE TITLE
Error with VSCode: Request textDocument/codeAction failed

### ISSUE THREAD

**Issue by datamonsterr** [a-h/templ#825]
Templ have worked fine for me recently until now. It suddenly throws this error message whenever I'm in a .templ file.
![image](https://github.com/a-h/templ/assets/94211882/ff38d946-5994-4af3-b90e-842795aeb4ff)

**Comment by datamonsterr** [comment]
after updating from @latest to the @main, the problem is gone

**Comment by hueuebi** [comment]
Thanks, I had the same issue!
