### ISSUE TITLE
LSP on Vscode Broken

### ISSUE THREAD

**Issue by CRSylar** [a-h/templ#829]
I'm working on a project since a couple of weeks and everything worked fine until yesterday, when the LSP crashed and i cannot find a way to make it work again

this is the trace of the error given by vscode

```
[Info  - 10:32:53 PM] 2024/07/04 22:32:53 Created View (#1)
	directory=/<path-to>/webapp
	view_type="GoMod"
	root_dir="file:///<path-to>/webapp"
	go_version="go version go1.22.3 linux/amd64"
	build_flags=[]
	env={GOOS:linux GOARCH:amd64 GOCACHE:/<home>/.cache/go-build GOMODCACHE:/<home>/go/pkg/mod GOPATH:/<home>/go GOPRIVATE: GOFLAGS: GO111MODULE: GOTOOLCHAIN:auto GoVersion:22 GoVersionOutput:go version go1.22.3 linux/amd64
 ExplicitGOWORK: EffectiveGOPACKAGESDRIVER:}
	env_overlay=[]

[Info  - 10:32:53 PM] 2024/07/04 22:32:53 go/packages.Load #1
	view_id="1"
	snapshot=0
	directory=/<path-to>/webapp
	query=[<path-to>/webapp/... builtin]
	packages=13
	duration=86.552919ms

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x87a6c0]

goroutine 68 [running]:
github.com/a-h/templ/cmd/templ/lspcmd/proxy.(*Server).CodeAction(0xc0000b64b0, {0xa55250, 0xc0002561e0}, 0xc00047a360)
	/home/go/pkg/mod/github.com/a-h/templ@v0.2.707/cmd/templ/lspcmd/proxy/server.go:294 +0x480
github.com/a-h/protocol.serverDispatch({0xa55250, 0xc0002561e0}, {0xa5b300, 0xc0000b64b0}, 0xc000474570, {0xa55528, 0xc0002187c0})
	/home/go/pkg/mod/github.com/a-h/protocol@v0.0.0-20230224160810-b4eec67c1c22/server.go:158 +0x4013
github.com/a-h/protocol.NewServer.ServerHandler.func1({0xa55250, 0xc0002561e0}, 0xc000474570, {0xa55528, 0xc0002187c0})
	/home/go/pkg/mod/github.com/a-h/protocol@v0.0.0-20230224160810-b4eec67c1c22/server.go:36 +0x7e
github.com/a-h/protocol.Handlers.ReplyHandler.func1({0xa55250, 0xc0002561e0}, 0xc000212708, {0xa55528, 0xc0002187c0})
	/home/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:35 +0xc6
github.com/a-h/protocol.Handlers.AsyncHandler.func2.2()
	/home/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:114 +0x76
created by github.com/a-h/protocol.Handlers.AsyncHandler.func2 in goroutine 9
	/home/go/pkg/mod/go.lsp.dev/jsonrpc2@v0.10.0/handler.go:112 +0x165
[Error - 10:33:09 PM] Server process exited with code 2.
[Error - 10:33:09 PM] Connection to server got closed. Server will not be restarted.
```

even opening a new project do not fix the lsp ( i've tried as a last resort )

the system im working on is Win11 - Wsl2  ( vscode running in wsl as well )

**Comment by a-h** [comment]
There was a couple of issues that surfaced when templ is used with gopls v0.16.x. It's likely that VS Code prompted you to upgrade gopls when you upgraded Go to v1.22.3 or something, resulting in it suddenly stopping working.

From the logs you provided, it looks like you're using templ v0.2.707, but the issue you're seeing was fixed in https://github.com/a-h/templ/commit/73474f65da4509c02aa0666f3277629c8c75e176 which was released in v0.2.731, which also supports auto-import of packages.

There's also another update today to support some changes made in gopls v0.16.x that change how gopls returns values to the editor.

See https://github.com/a-h/templ/releases/tag/v0.2.742

I'll mark this as closed, but please feel free to re-open if the release doesn't fix it.

**Comment by CRSylar** [comment]
i've updated the templ package but the lsp keeps crashing, reading the crash log i can see that the it still uses the templ@v.0.2.707

here's the full line 
```
/go/pkg/mod/github.com/a-h/templ@v0.2.707/cmd/templ/lspcmd/proxy/server.go:294 +0x480
```

how can i force the usage of the latest version ?

**Comment by a-h** [comment]
To install the latest version of templ run `go install github.com/a-h/templ/cmd/templ@latest`

**Comment by a-h** [comment]
You might also want to make sure you don't have any other versions of templ on your path somewhere, e.g. by running this a few times before you run the install:

```
rm `which templ`
```
