### ISSUE TITLE
bug: cannot parse complex attributes

### ISSUE THREAD

**Issue by stackus** [a-h/templ#83]
The parser cannot parse the complex attributes that are added to enable interactivity with [Alpine.js](https://alpinejs.dev).

Using the starting example from [here](https://alpinejs.dev/start-here) with the counter example added:
```
templ Demo() {
  <html>
  <head>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
  </head>
  <body>
    <h1 x-data="{ message: 'I ❤️ Alpine' }" x-text="message"></h1>
    <div x-data="{ count: 0 }">
      <button x-on:click="count++">Increment</button>
      <span x-text="count"></span>
    </div>
  </body>
  </html>
}
```
Generation results in the following error message:
`demo.templ parsing error: boolConstantAttributeParser: expected attribute name to end with space, newline or '/>', but got ":": line 10, col 18`

Changing `x-on:click` to `@click` will then produce this error message:
`demo.templ parsing error: <button>: malformed open element: line 10, col 14`

**Comment by joerdav** [comment]
Is alpine js using webcomponents to expand upon html?

If so I believe attributes are constrained by XML:
https://www.w3.org/TR/xml/#d0e804

So as you say ":" should be valid, and a potential expansion would be to allow all XML attribute characters.

**Comment by a-h** [comment]
The spec for HTML5 is really broad in what's allowed as an attribute name: https://html.spec.whatwg.org/multipage/syntax.html#attributes-2

**Comment by cayter** [comment]
I'm still getting error for the HTML below:

HTML
```html
<div x-data="{ modalOpen: false }" @keydown.escape.window="modalOpen = false" class="relative z-50 w-auto h-auto">
```

Error
```
parsing error: boolConstantAttributeParser: expected attribute name to end with space, newline or '/>', but got "."
```

**Comment by joerdav** [comment]
Hey, if you install `main` this should be fixed, I added `.` as a valid token in #107

**Comment by cayter** [comment]
> Hey, if you install `main` this should be fixed, I added `.` as a valid token in #107

Oh ok thanks boss!
