### ISSUE TITLE
Templ gopls functionality seems to still be broken with gopls `v0.16.x` and does not work with gopls `v0.15.3` anymore

### ISSUE THREAD

**Issue by zyriab** [a-h/templ#830]
Hello,

I've updated Templ and gopls to their respective latest releases but I still don't have any autocomplete or autoimports.
It used to work if I used gopls `v0.15.3` but it does not work anymore.
Templ logs have no error or warnings (they used to have one about a bad URI before the latest release).

When typing `f`:

gopls `v0.15.3` + Templ `v0.2.731` (it also autoimports)
![image](https://github.com/a-h/templ/assets/2111910/96c1f232-4e3d-4fcb-ad21-b14668971c35)

gopls `v0.16.1` (or `v0.15.3` as well) + Templ `v0.2.742`
![image](https://github.com/a-h/templ/assets/2111910/8b91cbfe-82f8-4839-884e-f1b07ac36a64)

I'd be happy to help if I can give more info.
I did try with the minimal config given in the docs.
Using Neovim `0.10.0` on MacOS 14.5 (Intel)

**Comment by Ganes556** [comment]
> Hello,
> 
> I've updated Templ and gopls to their respective latest releases but I still don't have any autocomplete or autoimports. It used to work if I used gopls `v0.15.3` but it does not work anymore. Templ logs have no error or warnings (they used to have one about a bad URI before the latest release).
> 
> When typing `f`:
> 
> gopls `v0.15.3` + Templ `v0.2.731` (it also autoimports) ![image](https://private-user-images.githubusercontent.com/2111910/345953252-96c1f232-4e3d-4fcb-ad21-b14668971c35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTU5ODIsIm5iZiI6MTcyMDE1NTY4MiwicGF0aCI6Ii8yMTExOTEwLzM0NTk1MzI1Mi05NmMxZjIzMi00ZTNkLTRmY2ItYWQyMS1iMTQ2Njg5NzFjMzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDVUMDUwMTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQyZmNhOTJiZGRhNDZhNDJjZjNlOTdkOTAzNzE2MDJlZjgwNDZmYjg0ZjI5M2I1N2U4MTlmNmI4NWFlMzQxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fTf_fMeCC3wbXE8Z80qXQUcw1ssHzagjaBbMTbw_r9w)
> 
> gopls `v0.16.1` (or `v0.15.3` as well) + Templ `v0.2.742` ![image](https://private-user-images.githubusercontent.com/2111910/345953421-8b91cbfe-82f8-4839-884e-f1b07ac36a64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTU5ODIsIm5iZiI6MTcyMDE1NTY4MiwicGF0aCI6Ii8yMTExOTEwLzM0NTk1MzQyMS04YjkxY2JmZS04MmY4LTQ4MzktODg0ZS1mMWIwN2FjMzZhNjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDVUMDUwMTIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTY1NzFmMDQ1ZjUzZDk5MmQzNDQzMzg4OGE1OTg3ZGJlNmMyZjAyM2VlMTk2Y2FlZmQwYjQ2MjNmYmJkNmZhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3MSjU8il-bswQZ2KJpZsSF1_UAZlm8FKm--P9SauNvs)
> 
> I'd be happy to help if I can give more info. I did try with the minimal config given in the docs. Using Neovim `0.10.0` on MacOS 14.5 (Intel)

same issue in nvim

**Comment by a-h** [comment]
Sorry about that, I had to release an update (v0.2.747). Can you give that a try out and see if order is restored to the world?

**Comment by zyriab** [comment]
Hey no worries! It's super cool that you are so reactive and work on this project for free!
It's solved on my end, thanks again for all the hard work!
I'll close the issue :)
