### ISSUE TITLE
Improved dev flow

### ISSUE THREAD

**Issue by martinmunillas** [a-h/templ#849]
As of right now I see myself using the following Makefile
```Makefile
include .env
export

templ:
	templ generate --watch --proxy="http://localhost:8020" -v

server:
	wgo run ./cmd

dev:
	make -j2 templ server
```

so I'm able to have auto reload on changes by doing `make dev`, it would be ideal if this could be baked altogether with in a `templ run` command or something. It would also be ideal if there could be a flag to attach a delve debugger to it and debug from the editor.

I would be more than willing to help doing these changes with some directions

**Comment by a-h** [comment]
I think you might be asking for `templ generate --watch` to re-run the cmd if Go files change. We want to do this, see https://github.com/a-h/templ/issues/646

**Comment by a-h** [comment]
I'll close this as a duplicate, since no extra info was received.
