### ISSUE TITLE
`templ generate` takes a long time for unformatted files

### ISSUE THREAD

**Issue by MilkeeyCat** [a-h/templ#857]
Try to generate code for this code 

```
package test

templ TestThingy(){
    <div>
        <h3>Dummy text</h3>
        <p>
            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>

            <span>Dummy text</span>
            <br>
        </p>
    </div>
}
```

For me it takes 6.3s when it's formatted but after I run `templ fmt` on the file, it takes 4.2ms. It doesn't seem like a big difference but I have a while which takes 1min to generate xd but after I formatted it, it takes only 20ms.

**`templ info` output**
usage: templ <command> [<args>...]

templ - build HTML UIs with Go

See docs at https://templ.guide

commands:
  generate   Generates Go code from templ files
  fmt        Formats templ files
  lsp        Starts a language server for templ files
  version    Prints the version

**Desktop (please complete the following information):**
 - OS: Linux
 - templ CLI version v0.2.747
- Go version 1.22.3 linux/amd64

**Comment by a-h** [comment]
I'd guess it's taking a long time to parsenthe <br> tag. The parser currently reads to the end of the content to check if it ever gets closed.

If it gets closed and there's content in it, IIRC, the formatter leaves it alone. But if it's a void tag like br, and it's got no children, templ fmt converts it to a self closing tag which is much faster to parse.

But several seconds to do either seems like a long time!

**Comment by MilkeeyCat** [comment]
Yep, when i change it to `<br/>` it works MUCH faster, thanks a lot!

**Comment by joerdav** [comment]
There's possibly a way to speed this up by avoiding the rewinding and re-parsing of tags after unclosed tags. 

Though it may be one of those that adds more parsing complexity than it's worth.

**Comment by a-h** [comment]
It could be that as soon as we see a void open tag inside a void tag, eg br inside br, we should quit looking for the close for the first br.

**Comment by a-h** [comment]
See #887

**Comment by MilkeeyCat** [comment]
Thanks a lot!
