### ISSUE TITLE
App freeze using air proxy

### ISSUE THREAD

**Issue by webdevcody** [a-h/templ#862]
**Describe the bug**

Video showing the issue.  When using air proxy, after I navigate between a few routes to and from, the browser tab freezes and I keep getting canceled requests in the network tab.  If I use the app normally without air proxy, I don't see this issue.  See attached video:

https://github.com/user-attachments/assets/bbe295e8-2e34-4fac-8502-2f4fa7497d35

Here are all the canceled requests after it gets into a bad state.  
<img width="1512" alt="Screenshot 2024-07-28 at 5 09 42 PM" src="https://github.com/user-attachments/assets/30480fda-cf05-4a98-b3a3-a952e32b6daa">

if I try to open new tabs to port 7331, they also sit there stuck until I close the original tab which caused the issue.

I checkout a new branch which demonstrates this bug here if interested https://github.com/webdevcody/go-mailing-list/tree/air-proxy-bug

run it with `Make dev` and go to http://localhost:7331/dashboard and click between the tabs.

**Comment by a-h** [comment]
Thanks. I tracked it down to the client side reload script not closing connections - fixed in https://github.com/a-h/templ/commit/889c8330cc4438492ed9c858a9aec40a871eb9c2

Didn't notice it because I'd been using it for partial page updates in HTMX, so wasn't triggering the same issue.
