### ISSUE TITLE
templ fmt indents weirdly if @component is put before/after text 

### ISSUE THREAD

**Issue by a-h** [a-h/templ#87]
The following snippet:

```html
templ x() {
	<li>
		<a href="/">
			Home
			@Icon("home", Inline)
		</a>
	</li>
}
```

gets formatted to become:

```html
templ x() {
	<li><a href="/">
	Home
	@Icon("home", Inline)
</a></li>
}
```

I don't think this is expected behavior.

(Extracted from #86)

**Comment by a-h** [comment]
Please see https://github.com/a-h/templ/commit/7efc71cfcfead03bbf773850db350e2279ec700b - I've updated the formatting. I hadn't taken into account correct whitespace handling behaviour at the start and end of inline elements.

The `@Icon` was always being interpreted as a block element.

Since `<a>` elements are inline, the content is now moved to a single line, with the whitespace correctly collapsed into a single space between the "words".

```
package main

templ x() {
        <li><a href="/">Home @hello("home")</a></li>
}
```

**Comment by diamondburned** [comment]
This is unrelated to the issue, but is there a way to disable collapsing of inline elements into a single line? It would be really inconvenient to have a really long paragraph be squished into one line instead of being line wrapped properly.

For example:

```
templ x() {
	<p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
		veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
		commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
		velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
		occaecat cupidatat non proident, sunt in culpa qui officia deserunt
		mollit anim id est laborum.
	</p>
}
```

shouldn't be squished to become

```
templ x() {
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
}
```

**Comment by a-h** [comment]
Yes, that should be no problem. I'll pick it up as my next thing to do.

**Comment by a-h** [comment]
Been thinking about formatting the text. I asked in a Slack channel with 400 engineers in it whether they prefer formatting to 1 or 2.

The first one is the simplest.

```html
<p>This is a long line of text, it will just keep going. Multiple sentences, all until the closing element.</p>
```

This is what Prettier does.

```html
<p>
  This is a long line of text,
  but, it's been broken up at
  80 cols.
</p>
```

I did skew the results by saying that I preferred number 1, because each developer can set their own screen width and word wrap preferences, whereas in 2 it's hard coded into the file, and if you want to remove a word like "but", it's on the 2nd line, you end up with a short line, and need to reformat, but the result was 29 votes for 1 vs 1 vote for 2, which seemed pretty conclusive to me.

I'm going to play around with the idea, but I'm not sure about it at the moment.

**Comment by diamondburned** [comment]
> because each developer can set their own screen width and word wrap preferences

They *can* choose what the editor does, yes. The editor will usually break it into an ugly-looking misindented line. It'll look nothing like the second example would. They *can not* choose how it would actually be line-wrapped, because the formatter will unwrap their lines.

That is, unless the editor takes an unopinionated approach like go fmt does and not touch line wrapping/breaking at all.

**Comment by a-h** [comment]
Can you describe some before/after examples that would demonstrate what you mean by un-opinionated wrapping?

Are you saying that a line like this wouldn't be touched?

```html
<p>This text { value } is a long line hdjkhfjkd fdhsjkhjk
fhdjskhjk.</p>
```

Or would you expect it to become?

```html
<p>
  This text { value } is a long line hdjkhfjkd fdhsjkhjk
  fhdjskhjk.
</p>
```

Or...

```html
<p>This text { value } is a long line hdjkhfjkd fdhsjkhjk
  fhdjskhjk.</p>
```

What about this approach of only wrapping if a block element contains plain text?

https://github.com/a-h/templ/compare/main...wrap

**Comment by diamondburned** [comment]
Ideally, the second condition would be best. However, I'm not sure how practical
that would be. Perhaps these examples could give an idea of what I'm thinking:

```html
<p>Hello, world</p> <!-- becomes -->
<p>
	Hello, world
</p>

<p>Hello,
			world</p>
<!-- becomes -->
<p>
	Hello,
			world
</p>

<p>
Hello,
		world</p>
<!-- becomes -->
<p>
Hello,
		world
</p>

<p>			Hello
world</p>
<!-- becomes -->
<p>
			Hello
	world
</p>
```

If that makes sense. Effectively, this behavior doesn't actually wrap or reflow
texts in any way. It just ensures that indentation is consistent to an extent:

- If the indentation is on the same line, then it is moved to the next line. The
  number of prefixing indentation is preserved.
- If the indentation goes before or after the tag, nothing gets done.

This should allow normal paragraphs such as these ones to stay unformatted:

```html
<body>
	<div>
		<pre>
Hello, world!

	Indented section goes here...

End of indentation?
		</pre>
	</div>
</body>
```

As well as very normal paragraphs wrapped to any column:

```html
<!-- wrapped to 50 columns! -->
<p>
	Lorem ipsum dolor sit amet, consectetur
	adipiscing elit, sed do eiusmod tempor
	incididunt ut labore et dolore magna aliqua.
	Tempus urna et pharetra pharetra. Elit
	pellentesque habitant morbi tristique senectus
	et. Non pulvinar neque laoreet suspendisse.
</p>
```

I'm not sure how consistent of a rule this would be. Please let me know if they
make sense or if any inconsistencies would occur because of them.

(This comment is written in vim so lines are soft-wrapped. You can blame GitHub
for not rendering soft-wrapped paragraphs properly.)

**Comment by joerdav** [comment]
Some of these would be too much indentation for me personally.
```html
<p>Hello, world</p> <!-- becomes -->
<p>
	Hello, world
</p>
```
I would expect a formatter to leave the above as-is.
It should only add new lines if:
A) the contents has new lines:
```html
<p>Hello, 
world</p> <!-- becomes -->
<p>
	Hello, 
	world
</p>
```
B) the contents is past a certain length:
```html
<p>Hello, world11111111111111111111111111111111111111111111111111111111111111111111111111111111111</p> <!-- becomes -->
<p>
	Hello, world11111111111111111111111111111111111111111111111111111111111111111111111111111111111
</p>
```

**Comment by a-h** [comment]
That sounds like a good set of rules @joerdav, thanks for putting the thinking time in!

One of my biggest concerns is messing up spacing around inline elements by adjusting the HTML formatting, especially where you *don't* want a space before or after an inline element within flowing text, and I think this set of rules does the trick.

Only adding new whitespace at the start and end of element content is good, since any whitespace there is ignore by HTML whitespace normalisation rules, and removing extra whitespace doesn't do any harm, since again, it would be removed by the whitespace normalisation rules in the browser.

If templ doesn't do any wrapping, then it's also really easy to implement. templ currently uses a plain `io.Writer` to write the formatted files to, so it doesn't currently know how long each line is, and there's no need to consider the length of inline element and their child content in the wrapping.

**Comment by diamondburned** [comment]
I personally don't think the tool needs to have a judgment of how long a line is. I would be very happy if only A of https://github.com/a-h/templ/issues/87#issuecomment-1556685714 is implemented. `go fmt` doesn't do this either.

**Comment by msonawane** [comment]
`````
package  components

templ Input() {
  <div class="form-control w-full max-w-xs">
    <label class="label">
      <span class="label-text">What is your name?</span>
    </label> 
    <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs"/>
    <label class="label">
      <span class="label-text-alt">Bottom Left label</span>
      <span class="label-text-alt">Bottom Right label</span>
    </label>
  </div>
}
```

is squashed into a single line. That seems odd

```
templ Input() {
	<div class="form-control w-full max-w-xs"><label class="label"><span class="label-text">What is your name?</span></label> <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs"/> <label class="label"><span class="label-text-alt">Bottom Left label</span> <span class="label-text-alt">Bottom Right label</span></label></div>
}

```
`

**Comment by a-h** [comment]
Yes @msonawane, currently, the formatter uses whether the HTML element is "inline" or "block" to determine whether it should have a newline and indent its contents (inline doesn't start a newline, block starts a new line and indents).

There's currently an additional rule which says that if all children are inline, don't bother indenting the contents.

Since `input`, `label` and `span` elements are all inline, and the `div` only contains inline elements, it's all squished onto a line.

I've had a few attempts at implementing a better formatter based on this conversation - i.e. it will be less opinionated about whitespace, but have so far ended up throwing away the changes each time.

**Comment by msonawane** [comment]
may i suggest not trying to format ?

**Comment by stormpat** [comment]
Would it be possible to add an option to format **all** elements as blocks, as this is _probably_ what most users want (also what other html formatters [like prettier] do) Right now i have a list of images (img tags) and the current formatting makes it really hard to make changes as all img tags are formatted on a single line (currently a single line 8000 chars long), basically the same goes for any inline element, currently i wrap inline elements in a div resulting in bloated html.

**Comment by evanlurvey** [comment]
One of the patterns I have noticed myself following is kinda this:
all elements have the exact same behavior
```html
<!-- input -->
<div>hello</div>
<!-- becomes -->
<div>hello</div>
```

```html
<!-- input -->
<div>hello
</div>
<!-- becomes -->
<div>
    hello
</div>
```

```html
<!-- input -->
<div>
hello</div>
<!-- becomes -->
<div>
    hello
</div>
```

```html
<!-- input -->
<div>
hello
</div>
<!-- becomes -->
<div>
    hello
</div>
```

```html
<!-- input -->
<div>
hello
line 2
</div>
<!-- becomes -->
<div>
    hello
    line 2
</div>
```

innerHTML rules are same as above ^^^

```html
<!-- input -->
<div attr="value" attr2="value2">hello</div>
<!-- becomes -->
<div attr="value" attr2="value2">hello</div>
```

```html
<!-- input -->
<div 
attr="value" attr2="value2">hello</div>
<!-- becomes -->
<div 
    attr="value" 
    attr2="value2"
>hello</div>
```

```html
<!-- input -->
<div 
attr="value" attr2="value2">
hello</div>
<!-- becomes -->
<div 
    attr="value" 
    attr2="value2"
>
    hello
</div>
```

```html
<!-- input -->
<div attr="value" 
attr2="value2">
hello</div>
<!-- becomes -->
<div 
    attr="value" 
    attr2="value2"
>
    hello
</div>
```


I think this type of logic could be built pretty easily. 🤞 Compare line # of prev token with line # of current token. If same line do nothing, if diff line then newline that token and tokens of same type for elm. 

Meaning if you define innerHTML all on the same line as the element then prune extra spaces and keep on same line. If you define innerHTML on a different line than either element tag then indent and newline the innerHTML

Same rules with attrs, if they are same line as starting of the tag then keep them there, if one exists on a new line put them all on their own lines.

**Comment by joerdav** [comment]
@evanlurvey I agree with your examples, they follow the rule of only adding whitespace for clarity sake, and never removing whitespace (since the developer may be trying to format in one way and fmt is fighting against them).

One example you haven't outlined is what would happen to the following:

```html
<!-- input -->
<div>
hello
	line 2
</div>
```

Would it be all shifted along:
```html
<!-- output -->
<div>
	hello
		line 2
</div>
```

Or brought inline:
```html
<!-- output -->
<div>
	hello
	line 2
</div>
```

**Comment by evanlurvey** [comment]
@joerdav I think in that example the last solution bringing them inline is best. 

Reasoning is for the copy paste. If I'm copy pasting a tailwind button for example. I might grab it from something with 4 levels of indentation and place it at a 2 level. I expect that to be fixed. 

Same with whitespace I expect it to be adjusted. I think 2+ spaces is the same as one space. Makes parsing easier.

HTML doesn't care or do anything different for extra whitespace which is my main argument for formatting it out.

**Comment by evanlurvey** [comment]
So this is what I was thinking as far as formatting https://github.com/a-h/templ/pull/167. I built it locally and used it to format a few sample projects. 

If we like it I will update all the tests and try to clean up the unused block / inline formatting code.

**Comment by a-h** [comment]
For me, getting the formatting right is number 1 priority. It should fix issues where `{firstName} {lastName}` becomes `{firstName}{lastName}`.

If you'd like to pair/mob on it, I'd be happy to set some time up.

I had this function in a branch. Quite helpful for debugging whitespace in the diff output.

```go
if diff := cmp.Diff(expected, w.String()); diff != "" {
		t.Errorf("Input:\n\n%s", input)
		t.Errorf("Expected:\n\n%s", showHiddenChars(expected))
		t.Errorf("Actual:\n\n%s", showHiddenChars(w.String()))
}

func showHiddenChars(s string) string {
	s = strings.Replace(s, " ", ".", -1)
	s = strings.Replace(s, "\t", " →", -1)
	return s
}
```

**Comment by evanlurvey** [comment]
> If you'd like to pair/mob on it

Sure! 

I just pushed up the cleanup and tests as well for the indention changes. Which can work around the `{first} {last}` issue by adding a newline somewhere in there.

**Comment by evanlurvey** [comment]
@a-h Actually this was an easy fix to add to my PR. So I did that and added tests. Let me know what you think.

**Comment by a-h** [comment]
Thanks to everyone for contributing their brains and time to this issue. It's much appreciated.

I think this has been resolved by @evanlurvey's PR. There's a good set of tests that describe the behaviour.

If there's any specific issues with the formatting as it is in 39e59ab1f96467276dd6feb7cbe71288cf136bcc onwards, let's start a new issue to cover that!

Thanks again.
