### ISSUE TITLE
Anyway to instantiate a templ once per rendering context?

### ISSUE THREAD

**Issue by zaydek** [a-h/templ#883]
Hey there, I was wondering if there's some way I can instantiate a CSS template once per rendering context. Conceptually, you could imagine something like `@once <templ>` or something. In React.js world, this is more like using the `<head>` element so even if you stamp out a template like 5 times, it only inserts the component once per document.

Here's a use case:

```go

templ AnyPage(data AnyPageData) {
  @ComeauCSS()
  @BaseCSS()
  @NavbarCSS()
  @AnyPageCSS()
  @HairlineCSS()
  @PreviewCardListCSS()
  @PreviewCardCSS()

  @Navbar(navbarItems)
  <main class="main">
    <div class="sidebar-1">
      <div>Hello, {data.Name}!</div>
      <div>Hello, {data.Name}!</div>
      <div>Hello, {data.Name}!</div>
      <div>Hello, {data.Name}!</div>
    </div>
    <div class="content">
      <div>Hello, {data.Name}!</div>
      <div>Hello, {data.Name}!</div>
      <div>Hello, {data.Name}!</div>
      <div>Hello, {data.Name}!</div>
    </div>
    <div class="sidebar-2">
      @PreviewCardList() {
        @PreviewCard()
      }
      @Hairline()
      @PreviewCardList() {
        @PreviewCard()
        @PreviewCard()
        @PreviewCard()
        @PreviewCard()
      }
    </div>
  </main>
}
```

I found that because the CSS parser doesn't support things like psuedos, I had more success just creating sibling templates for CSS which exclusively render <style> tags. This works -- though I don't get class name hashing or anything fancy, but I also need to make sure I only stamp out the CSS template once. So in my case, I just have to remember to instantiate the CSS template in the root template, but I wish it were somehow an implicit side effect of the component templates I'm already using, hence the `@once` idea. Is there a way I can do soemthing like what I'm trying to do already? I would use the `css` syntax but I want to be able to use arbitrary CSS expressions which may or may not be supportable with the built in lexer. Thanks!

**Comment by nexovec** [comment]
Is there even a notion of a rendering context in templ?

It sounds more like you're calling for a centralized way to manage CSS dependencies than some actual `@once` feature. I have a build-less tool for managing CSS and JS resources grouped into yaml defined user profiles at hand. Even does some extra stuff like CDN support with server-side failover.

Is there demand for this as a library?

**Comment by zaydek** [comment]
> Is there even a notion of a rendering context in templ(the `.Render()` method, possibly?)?
> 
> It sounds more like you're calling for a centralized way to manage CSS dependencies than some actual `@once` feature. I have a build-less tool for managing CSS and JS resources grouped into yaml defined user profiles at hand. Even does some extra stuff like CDN support with server-side failover.
> 
> Is there demand for this as a library?

Sure, I'd be curious to see your setup. I think I could also try using a data structure in Go and have components register themselves as side effects but I'm not sure because .templ files are not really setup for writing arbitrary Go code. I did try the flag TEMPL_EXPERIMENT=rawgo but I'm not sure it will let me do what I want, like writing to a global cache so I know which stylesheets to include or something like that. Not sure. Anyway yeah, open minded to existing solutions and patterns.

**Comment by pharrisee** [comment]
Would this be what you're thinking?

https://templ.guide/syntax-and-usage/render-once/

**Comment by zaydek** [comment]
> Would this be what you're thinking?
> 
> https://templ.guide/syntax-and-usage/render-once/

Yes that looks amazing for my use case, much appreciated!
