### ISSUE TITLE
Support self-closing tags

### ISSUE THREAD

**Issue by Joe-Davidson1802** [a-h/templ#9]
Currently attempting to use self closing tags throws an error in some cases.

Case 1:

In this case since the input is the last in the parent element generator seems to allow it and writes a `</input>` after.

```
<div>
    <input type="text" name="title" id="title" placeholder="Todo..." />
</div>
```

Case 2:

In this case as self closing tags exist as children that aren't at the end of the parent an error is thrown:
`parsing error: <meta>: mismatched end tag, expected '</meta>', got '</link>'`

```
<head>
    <title>{%= "Hotwire Todo - " + title %}</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.min.css" />
    <script type="module">{%! Raw("import hotwiredTurbo from 'https://cdn.skypack.dev/@hotwired/turbo';") %}</script>
</head>
```

**Comment by a-h** [comment]
Hi, thanks for this. This was fixed in https://github.com/a-h/templ/commit/70aae13ae31f9cdc4f27c5dca6506b2bc4cfc7b3

I've checked the example and it worked out great.

I've released https://github.com/a-h/templ/releases/tag/v0.0.88 with the fix in it. Please feel free to reopen if I've missed something.

**Comment by JonPichel** [comment]
Hi, I am new to templ and I am loving it so far. I am experiencing the same issue as Case 2 using the vscode extension.

```html
		<head>
			<title>lexdomus - { title }</title>
			<meta charset="UTF-8">
			<meta name="">
			<link href="/assets/styles.css" rel="stylesheet">
		</head>
```

This throws this error and can't compile unless I close the `meta` and `link` tags: `<link>: mismatched end tag, expected '</link>', got '</head>'`

**Comment by a-h** [comment]
Hi @JonPichel, glad you're enjoying templ. 😀 

Templ is like JSX in that all tags have to be closed. It helps in validating the HTML structure. It's documented in https://templ.guide/syntax-and-usage/elements#tags-must-be-closed
