### ISSUE TITLE
Setting children from go code

### ISSUE THREAD

**Issue by rotemhoresh** [a-h/templ#909]
The title basically, e.g.:

```templ
// comp.templ
templ Comp() {
    <div class="error">
        { children... }
    </div>
}
```

```go
// render.go
Comp().Render(ctx, w)  // how to set children components / raw HTML from here?
```

**Comment by a-h** [comment]
To pass children in code, you can use the `templ.WithChildren` function to create a context that has children:

```go
ctx := templ.WithChildren(ctx, child)
err := Comp().Render(ctx, sb)
```

The inverse (getting the children from within Go code) is done with the `templ.GetChildren` function.

https://github.com/a-h/templ/blob/e2511cd57e5ecd28ce6e3d944c87f1e31e20b596/runtime.go#L60-L82

If you want to concatenate multiple children, we haven't (currently) got an API for that. The consensus is that adding `templ.Join` for that would be useful, as per https://github.com/a-h/templ/issues/788

**Comment by a-h** [comment]
I've updated the docs to include this information. Feel free to re-open etc. if needed.

**Comment by pulsone21** [comment]
I have also a question regarding this topic.

Count children in templ

I have this `List` templ component.
```golang
templ List(placeholder, url, trigger string) {
	<div
		hx-get={ url }
		hx-swap="outerHTML"
		hx-trigger={ trigger }
	>
		if len(children) > 0 {
			<ul role="list" class="scroll-smooth h-full overflow-y-auto divide-y-2 divide-base flex flex-col gap-2">
				{ children... }
			</ul>
		} else {
			<p class="text-overlay1">
				{ placeholder }
			</p>
		}
	</div>
}
```
The idea behind that component is that you have a general wrapper arround a list which automatically sets up everything you need, you only need to specify what items are in there. 

To use it it should look something like this:
```golang
<div>
 @List(){
for _, i := range Items {
 @ItemComponent
}
}
</div>
```

As you can see i also setup a placeholder text. My issue is now that i can't check if i provided children or not. How can i check if children's are provided or not?

**Comment by a-h** [comment]
Looks like this conversation is continuing at https://github.com/a-h/templ/issues/975#issuecomment-2561999767

I'll pick it up there.
