### ISSUE TITLE
Parser chokes on "<" in if statements

### ISSUE THREAD

**Issue by kalafut** [a-h/templ#930]
v0.2.778

Pretty straightforward:

```go 
// ✅
if i > 1 {
    foo
}

// ✅
if i == 1 {
    foo
}

// ❌ (compilation errors about unterminated if)
if i < 1 {
    foo
}
```

Putting the expression in parens doesn't help.

**Comment by phenpessoa** [comment]
I'm unable to reproduce. This compiles just fine for me:

```templ
package main

templ foo(x int) {
	if x < 1 {
		<div>
			a
		</div>
	}
	if x == 1 {
		<div>
			b
		</div>
	}
	if x > 1 {
		<div>
			c
		</div>
	}
}
```

**Comment by kalafut** [comment]
Strange. For that exact code I get:

```
parsing error: if: unterminated (missing closing '{\n') - https://templ.guide/syntax-and-usage/statements#incomplete-statements: line 3, col 0
```

**Comment by kalafut** [comment]
OK, false alarm. It looks like the LSP with VSCode got into a funky state. I realized it was formatting stuff on save into something like this, which *is* invalid syntax:

```
templ foo(x int) {
	if x < 1 {  <div>
			a
		</div>
	}
```
A restart fixed it.

I'll keep an eye out for it this reoccurs, but I hadn't restarted VSCode in many days so I'm not terribly surprised nor concerned.

**Comment by chama-chomo** [comment]
Hello, apparently I experience the same issue here, restart doesn't help

<img width="1660" alt="image" src="https://github.com/user-attachments/assets/c2658415-ae47-4701-929d-9f9341293c09">

**Comment by a-h** [comment]
I haven't tested this yet, but I assume that it works OK if you put the expected new lines in place?

```
templ Resolution(width int) {
  if width > 1900 && width < 3800 {
    "FHD"
  } else if width > 3800 {
    // etc.
  }
}
```

**Comment by chama-chomo** [comment]
thx, my formatter is just not satisfied whatever indentation I use and basically messes the code like I've shown in my previous post. I guess the problem will be on formatter side then.

**Comment by a-h** [comment]
That is very ugly indeed. As a temporary workaround, I'd suggest dropping into Go.

```templ
func resolution(w int) templ.Component {
  res := "SD"
  if w < 3800 && w> 1080 {
    res = "FHD"
  } else if w > 3800 {
    res = "UHD"
  } else if w< 1900 && w> 1080 {
    res = "HD"
  }
  return templ.Raw(res)
}
```

**Comment by chama-chomo** [comment]
thanks!

**Comment by bictorman** [comment]
Hi,

I also just run into this, with this function:
```go
templ SerpPaginationNextButton(p *siteprops.PaginationProps) {
  if p.Current < p.NumPages {
    <a href={ templ.SafeURL(PageLink(p.Current+1, p.Path)) }>
	    <span>next page</span>
    </a>
  }
}
```

It's a bug in the VSCode extension `v0.0.29` , @phenpessoa code also breaks there.

Easiest workaround is to **invert the comparison so it doesn't look like an opening bracket** , this works:
```go
if p.NumPages  > p.Current {
```
