### ISSUE TITLE
Idea: web components with templ

### ISSUE THREAD

**Issue by gedw99** [a-h/templ#95]
So you render to browser and browser is web components.

https://github.com/18alantom/strawberry/tree/main#features

the demo is nice. It’s so simple.

I know people are using templ with htmx and it nice for sure.

strawberry can do what templ does but with no compile and with htmx like reactivity .

So was thinking that templ can render with data to strawberry which then takes over.

there are some interesting possibilities.

chip in ideas if you see any . It’s just a brain storm right now.

**Comment by gedw99** [comment]
@joerdav true -  there is nothing holding back producing web components.

strawberry is a templating system for web components that needs NO compilation.

**Comment by gedw99** [comment]
https://github.com/18alantom/strawberry/blob/main/docs/api.md

It’s a bit like htmx

**Comment by joerdav** [comment]
Nice, it looks like an interesting project! Is there anything more to do on this issue or is it more of a discussion issue? @a-h maybe we want to enable discussions on github for this kind of conversation, since we don't have a slack/discord community yet.

**Comment by joerdav** [comment]
Closing as there is no action needed.
