### ISSUE TITLE
Nix templ version

### ISSUE THREAD

**Issue by moibraheem3** [a-h/templ#950]
Nix Flake version is `0.2.786`  while go get is `0.2.778`. I checked the `.version` file and found out it was `0.2.786` not `0.2.778`.  
I am unsure if it was intentional or if it's a bug.

**Comment by a-h** [comment]
I see you closed this. It is intentional.

Hopefully you realised you can use a flake reference like `github:a-h/templ/v0.2.778` to use a specific version, or leave off the version suffix to get the tip of main.

**Comment by moibraheem3** [comment]
Sorry about that. 

I was getting an error, so I thought it was due to the version difference. However, when I tried the older version, I got the same error. Then I realized it was a syntax error, not a CLI compatibility issue.

Sorry. I should carefully read the error message before posting an issue.
