### ISSUE TITLE
Using the storybook package

### ISSUE THREAD

**Issue by rotemhoresh** [a-h/templ#957]
Sorry if it comes out a bit silly, but I have never used storybook, and most of the docs are for react or other frontend frameworks.

I have managed to set up a server renderer, like in the [example](https://github.com/a-h/templ/blob/main/storybook/_example/local/main.go) using the templ/storybook package.
But the result is not the storybook dashboard, but just the components themselves.

Now, I saw in the [server renderer example by storybook](https://storybook-server-demo.netlify.app/) that it, too, has only the components themselves.
But the [example](https://4vl613fmb9.execute-api.eu-west-2.amazonaws.com/?path=/story/footertemplate--default) deployed by you has a dashboard.

My questions:
1) How can I have have the full storybook dashboard?
2) also, How can I add dependencies for the components (alpine.js, tailwindcss)?

**Comment by a-h** [comment]
It looks like Storybook changed their installation process which busted the workflow - i.e. the storybook JavaScript project wasn't properly initialized, which resulted in not having a UI etc.

I fixed it 4 days ago in https://github.com/a-h/templ/commit/3eaa56a05e5c365539ea199fbc0158fe2a758f2f which hasn't been released yet, but you can test out the main branch.

If that doesn't work for you, if you publish a sample project on Github, I can eyeball it.

**Comment by rotemhoresh** [comment]
Thanks! I'll check it out.
