### ISSUE TITLE
Explore batching strings

### ISSUE THREAD

**Issue by eventgraph** [a-h/templ#96]
```html
templ hello() {
	<h1>Hello World</h1>
}
```
generates
```go
// Element (standard)
_, err = templBuffer.WriteString("<h1>")
if err != nil {
	return err
}
// Text
var_2 := `Hello World`
_, err = templBuffer.WriteString(var_2)
if err != nil {
	return err
}
_, err = templBuffer.WriteString("</h1>")
if err != nil {
	return err
}
if !templIsBuffer {
	_, err = io.Copy(w, templBuffer)
}
return err
```

There is a lot of extra checks and possible buffer thrashing going on when this could be condensed to
```go
_, err = templBuffer.WriteString("<h1>Hello World</h1>")
if err != nil {
	return err
}
```

Basically as long as the results are `WriteString` or const strings concat into a single call

**Comment by a-h** [comment]
Yeah, you're absolutely right. It would be an improvement to the generator and would produce a small speed increase.

I had thought of doing this, but hadn't got around to it.

The template file parser at https://github.com/a-h/templ/blob/main/parser/v2/templatefile.go parses a templ file. This result is sent to the generator which creates code https://github.com/a-h/templ/blob/main/generator/generator.go

The generator could look inside the children of elements, and if the element only contains text, make a single string constant to write out. At the moment, text is just another node, so the contents are written out one-by-one: https://github.com/a-h/templ/blob/12d06aff2dbffc59ececa66b6525f6304688b302/generator/generator.go#L862-L864

Perhaps the way to do it would be to get each parser type to implement a function that returns a raw string if it, and all of its children, can. In which case, the generator just writes out that raw string.

**Comment by delaneyj** [comment]
https://github.com/shiyanhui/hero has about the fastest and tightest code I've seen.    Might be a decent one to look at,  sharing bytebuffers in a pool is also a huge win for longer running templates.

**Comment by joerdav** [comment]
@delaneyj I think we're on the back foot a bit vs hero, templ hasn't taken the plunge into using `unsafe` yet.

I might take a look at implementing a PR for this string batching functionality though when I get a minute.

**Comment by a-h** [comment]
I think that ordered, my goals should be Ergonomics, Safety, Maintainability, Speed.

My main goal initially was to make sure that it's way faster than React, since it's a mainstream accepted tool. 

Current benchmarks (see benchmarks directory) for React give me 96,781 operations per second, which I can turn into nanoseconds per operation to match Go benchmarks by 1,000,000,000 / 96,781 = 10,332 ns/op.

The templ benchmark is currently giving 843 ns/op.

I think that 12x faster than React is OK for now, so my current focus is fixing bugs around the LSP and tooling, and dealing with any rough bits with usage.

It's always good to go faster but I wouldn't want to take on `unsafe`.

I'm currently thrashing around on some formatting stuff, then I'll move on to the next thing!

**Comment by a-h** [comment]
Nice work on that PR @joerdav 

I'm seeing an improvement of around 17% on my basic benchmark.

## Before

```
0 0 /Users/adrian/github.com/a-h/templ/benchmarks/templ % xc run
+ go test -bench .
goos: darwin
goarch: arm64
pkg: github.com/a-h/templ/benchmarks/templ
BenchmarkCurrent-10              2858404               414.3 ns/op           536 B/op          6 allocs/op
BenchmarkIOWriteString-10       18057364                66.48 ns/op          352 B/op          2 allocs/op
PASS
ok      github.com/a-h/templ/benchmarks/templ   2.982s
```

## Grab the PR

0 0 /Users/adrian/github.com/a-h/templ/benchmarks/templ % gh pr checkout 104

## After

```
0 0 /Users/adrian/github.com/a-h/templ/benchmarks/templ % xc run
+ go test -bench .
goos: darwin
goarch: arm64
pkg: github.com/a-h/templ/benchmarks/templ
BenchmarkCurrent-10              3404298               342.2 ns/op           536 B/op          6 allocs/op
BenchmarkIOWriteString-10       17741658                66.27 ns/op          352 B/op          2 allocs/op
PASS
ok      github.com/a-h/templ/benchmarks/templ   2.922s
```

## Results

(414ns) - (342ns) / 414ns = 17% faster.

**Comment by delaneyj** [comment]
Great work, 17% is great even without going unsafe
