### ISSUE TITLE
Suggestion: `templ lsp` should print an error when gopls is not installed

### ISSUE THREAD

**Issue by whmountains** [a-h/templ#967]
Steps to reproduce:

1. Ensure `gopls` is NOT installed.
2. Run `templ lsp`

Expected behavior: an error message is printed, prompting the user to run `templ info` for more details.

Actual behavior: nothing is printed at all

This was quite confusing to me as someone who is new to Go and Templ.  Both Zed and VS Code printed cryptic error messages about a closed channel or something.  I immediately checked the LSP logs for additional clues, but there was nothing.  I then tried running `templ lsp` manually.  When it silently exited I thought it had daemonized itself or something.  It was only when I tried to kill the daemon that I realized it was not there and started running other cli commands out of desparation.

This is not a bug and I expect a careful reading of the documentation would have given me some clues.  But it seems like an opportunity to make a trivial change that could improve the experience for a percentage of new users.  I work with several less common languages like Elixir, where buggy LSP servers are the norm, so I was perhaps slower to blame myself than I should have been.

 - OS: MacOS
 - templ CLI version: `v0.2.778`
- Go version: `go1.23.2 darwin/amd64`
- `gopls` version: `golang.org/x/tools/gopls v0.16.2`

**Comment by tjbarber** [comment]
When I tried this I encountered this error:

![image](https://github.com/user-attachments/assets/c4ef2652-c4e3-4cdd-abc1-bfef8a1b64e2)

If you're not getting any error message printed, it's likely that the LSP is running properly when you run it from the command line and your editor isn't configured properly. 

You're saying that you ran `templ lsp` and it immediately quit as opposed to just running non-interactively?

**Comment by whmountains** [comment]
Thanks for attempting to reproduce!  That is very strange, because I can 100% confirm that `templ lsp` exits immediately for me with no error message when `gopls` is not installed.  I uninstalled it and tested again just now to confirm.

<img width="571" alt="SCR-20241025-karq" src="https://github.com/user-attachments/assets/394a4a83-6706-4cde-b6aa-5e42fc5664c0">

It exits with status 1 but no error message.

I happen to be using a less common shell called nushell, so I temporarily set zsh to be my login shell and tried again, unfortunately with the same result.  Note that my ZSH is absolutely stock, with no `.zshrc` at all.

<img width="571" alt="image" src="https://github.com/user-attachments/assets/6cd9fde9-8e44-447a-9688-fda6d7bef433">

> You're saying that you ran templ lsp and it immediately quit as opposed to just running non-interactively?

Yes!  I don't blame you for double checking.  Once I installed gopls, it still prints nothing but it stays running until I force it to exit by pressing Control-C.  Also, my editor immediately started working correctly once I installed gopls and ran the command to restart the language server.  I had repeatedly restarted the language server before installing gopls but it would always immediately error out.

This problem is stranger than I thought.  It's not particularly important, but I do hope we can get to the bottom of what's causing the difference in behavior.

**Comment by joerdav** [comment]
Just one thought from me, are you sure there isn't another version of gopls hanging around somewhere? Try `where gopls`

**Comment by a-h** [comment]
Can you run `templ info`? It will tell you where `gopls` is.

On my Mac, the output currently looks like this:

```
(✓) os [ goos=darwin goarch=arm64 ]
(✓) go [ location=/run/current-system/sw/bin/go version=go version go1.23.1 darwin/arm64 ]
(✓) gopls [ location=/Users/adrian/go/bin/gopls version=golang.org/x/tools/gopls v0.16.2 ]
(✓) templ [ location=/Users/adrian/go/bin/templ version=v0.2.781 ]
```

But let's also trace through the code just to make sure.

The entrypoint of the `templ` CLI is: https://github.com/a-h/templ/blob/bb5e41b1cc6d4edb5cb2e173650320bb28fd74e0/cmd/templ/main.go#L22

The LSP command is a subcommand: https://github.com/a-h/templ/blob/bb5e41b1cc6d4edb5cb2e173650320bb28fd74e0/cmd/templ/main.go#L56

So, it ends up running the public `Run` function of the `lspcmd` package: https://github.com/a-h/templ/blob/bb5e41b1cc6d4edb5cb2e173650320bb28fd74e0/cmd/templ/main.go#L378

There's a bit of setup: https://github.com/a-h/templ/blob/bb5e41b1cc6d4edb5cb2e173650320bb28fd74e0/cmd/templ/lspcmd/main.go#L32

But then it ends up at https://github.com/a-h/templ/blob/bb5e41b1cc6d4edb5cb2e173650320bb28fd74e0/cmd/templ/lspcmd/main.go#L72

And we see where the code starts gopls: https://github.com/a-h/templ/blob/bb5e41b1cc6d4edb5cb2e173650320bb28fd74e0/cmd/templ/lspcmd/main.go#L83-L91

There's an info log item, there's a section at https://templ.guide/commands-and-tools/ide-support#troubleshooting-1 that mentions how to enable logs.

Note that if an error is returned from `pls.NewGopls` the program stops: https://github.com/a-h/templ/blob/bb5e41b1cc6d4edb5cb2e173650320bb28fd74e0/cmd/templ/lspcmd/main.go#L88-L91

So, let's make sure that `NewGopls` does that: https://github.com/a-h/templ/blob/bb5e41b1cc6d4edb5cb2e173650320bb28fd74e0/cmd/templ/lspcmd/pls/main.go#L73-L80

Here's the function that looks for `gopls`: https://github.com/a-h/templ/blob/bb5e41b1cc6d4edb5cb2e173650320bb28fd74e0/cmd/templ/lspcmd/pls/main.go#L34-L70

I can't see a bug in there, but I guess there's a chance that you haven't set the executable bit on the `gopls` binary...

**Comment by a-h** [comment]
Closing, due to lack of response from @whmountains - feel free to reopen if you have further details.

Thanks!
