### ISSUE TITLE
refactor: remove a-h/pathvars library

### ISSUE THREAD

**Issue by lhorie** [a-h/templ#968]
**Describe the bug**
Currently, templ depends on a-h/path-vars, which doesn't have a license file. This means that even though templ itself is MIT licensed, it cannot be consumed by organizations that have strict policies around licensing/SBOM because introducing templ to a codebase would also introduce unlicensed transitive dependencies.

**To Reproduce**
Go to https://github.com/a-h/pathvars and notice there's no LICENSE file

**Expected behavior**
Dependencies of templ need to have clear licenses

**Screenshots**
N/A

**Logs**
N/A

**`templ info` output**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.6.1
 - templ CLI version (`templ version`): v0.2.778
- Go version (`go version`): go1.23.2

**Additional context**
A tentative fix is proposed here: https://github.com/a-h/pathvars/pull/3

**Comment by a-h** [comment]
Thanks for picking that up. Just an oversight.

I expect we can remove pathvars from templ now that standard library routing supports the same functionality.

**Comment by a-h** [comment]
OK, I'll take a PR for this one. Let's find a-h/pathvars and remove it. The standard library router should provide all of the path variable support we need now.

**Comment by a-h** [comment]
Closed in #999
