### ISSUE TITLE
Explore multi type support

### ISSUE THREAD

**Issue by delaneyj** [a-h/templ#98]
Right now templ it positioned explicitly at HTML.  Would be nice if .html.templ used the HTML lsp.

For example if you want to write a bash script with if statements that'd breaks the current lexer.  I like the simplicity for HTML but want to use for other format.  Even stuff like generated Go code.

**Comment by stephenafamo** [comment]
I would like this too.

For example, I would like to use templ to manage the templates for [Bob](https://github.com/stephenafamo/bob) since it does make things much easier.

**Comment by joerdav** [comment]
I think this having been discussed at length elsewhere, templ is going to for now continue only supporting HTML.
