### ISSUE TITLE
vscode: syntax broken when using children

### ISSUE THREAD

**Issue by nicolasparada** [a-h/templ#99]
Syntax gets broken when using children composition.

<img width="2560" alt="Screenshot 2023-05-27 at 22 50 26" src="https://github.com/a-h/templ-vscode/assets/7969166/c310f6b4-0773-4ec6-bd30-d25ba57f1155">

<details>
<summary>Code</summary>

```
package main

templ layout() {
	<header>
		<h1>My Site</h1>
	</header>
	<main>
		{ children... }
	</main>
}

templ hello(name string) {
	@layout() {
		<div>Hello, { name }!</div>
	}
}

```
</details>

See line 13 the syntax highlight stops working.
I tried moving the layout in the example to its own file but the highlight does not work either.

The code does work tho 👍

**Comment by a-h** [comment]
I've just released v0.0.9 of the extension which includes the syntax highlighting.

Thanks for taking the time to report the issue, and to provide a quality bug report.
